### ISSUE TITLE
Infinite loop if csv is empty

### ISSUE THREAD

**Issue by DMGPage** [box/spout#120]
box/spout 2.3.0
I have empty CSV file with two empty lines and, if I try to read it, it starts infinite loop:
isEmptyLine
getNextUTF8EncodedLine
getEncodedEOLDelimiter
isEmptyLine
getNextUTF8EncodedLine
getEncodedEOLDelimiter
isEmptyLine
getNextUTF8EncodedLine
getEncodedEOLDelimiter
isEmptyLine
getNextUTF8EncodedLine
getEncodedEOLDelimiter
isEmptyLine
getNextUTF8EncodedLine
getEncodedEOLDelimiter
isEmptyLine
...

**Comment by adrilo** [comment]
I can't reproduce the issue. See https://github.com/box/spout/pull/121
Can you share here what you CSV file contains? I guess it's not 100% empty

**Comment by DMGPage** [comment]
I can reproduce this bug in my home and work pc. My file have two empty lines. Ok you can access file here: http://files.fm/u/tnmribx

**Comment by adrilo** [comment]
Gotcha! I can repro it now

**Comment by DMGPage** [comment]
When I can wait stable version release of this bug fix?

**Comment by adrilo** [comment]
I'd like to include one more fix in the next release. So hopefully this week or next week.

**Comment by adrilo** [comment]
@DMGPage, it's ready as part of 2.3.1

**Comment by DMGPage** [comment]
Thank You
