### ISSUE TITLE
Doesn't work together with stream wrappers

### ISSUE THREAD

**Issue by Bob4ever** [box/spout#132]
Hi. I want to use Spout together with a custom stream wrapper registred by [stream_wrapper_register](http://php.net/manual/en/function.stream-wrapper-register.php).

The problem now is that spout calls realpath on every path since #126, realpath returns a false for the stream wrapper paths and it will throw a "Could not open file for reading." exception.

**Comment by adrilo** [comment]
Hey @Bob4ever, can you provide a small snippet of what you are doing?

**Comment by Bob4ever** [comment]
I'm using league/flysystem together with twistor/flysystem-stream-wrapper.

```PHP
// I have a xlsx file in /some/path/test.xlsx

// Get a Filesystem object.
$filesystem = new Filesystem(new Local('/some/path'));
// register stream wrapper
FlysystemStreamWrapper::register('fly', $filesystem);

$reader = ReaderFactory::create(Type::XLSX);
$reader->open('fly://test.xlsx');
// error - "Could not open $filePath for reading."
```

**Comment by adrilo** [comment]
I see. Do you know if XMLReader is compatible with custom stream wrappers? Can you do something like this:

```php
$xmlReader = new XMLReader();
$xmlReader->open('fly://test.xlsx#xl/sheets/sheet1.xml');
```

or does it throw an exception?

**Comment by Bob4ever** [comment]
Ok I see the problem. The XMLReader does only support opening files by path and to unzip the files you are already a using a [stream wrapper](http://php.net/manual/de/wrappers.compression.php). Stacking streamwrappers isn't possible by just adding the paths like "zip://fly://test.xlsx#xl/sheets/sheet1.xml". The only solution I get in my mind is to build dynamicly a streamwrapper to resolve the problem. 

I think we can close this. It would be to much work for a small feature.

**Comment by adrilo** [comment]
Yes, this seems a bit overkill for such a small feature. Moving away from using "zip://" would degrade performance, as I'd need to unzip the XLSX first before accessing its files (and for large XLSX files, it can take a while).
I'll close this issue then. Sorry I could not help!
