### ISSUE TITLE
Symfony / PSR-7 support

### ISSUE THREAD

**Issue by barryvdh** [box/spout#134]
What do you think about support Symfony of PSR-7 Responses?

Symfony supports a 'StreamedResponse', that allows you use a callback, so that headers etc can be added in the app lifecycle, but the output is only written when closing.

Example how it could be used now:

```php
use Symfony\Component\HttpFoundation\StreamedResponse;
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Common\Type;

function getExcel()
{
    $writer = WriterFactory::create(Type::XLSX);

    $response = new StreamedResponse(function() use ($writer) {
        
        // Open to browser
        $writer->openToFile('php://output');
        
        // Add headers
        $writer->addRow($columns);

        // Add all the rows
        foreach ($items as $item) {
            $writer->addRow($values);
        }

        // Close the writer
        $writer->close();
    });

    $response->headers->set('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    $response->headers->set('Content-Disposition','attachment; filename="result.xlsx"');

    return $response;
}
```

You already have the header information etc, so we could wrap the open/close and the headers, perhaps something like this:

```php
function getExcel()
{
    $writer = WriterFactory::create(Type::XLSX);

    $response = $writer->streamResponse('results.xlsx', function($writer) {
            // Add headers
            $writer->addRow($columns);

            // Add all the rows
            foreach ($items as $item) {
                $writer->addRow($item->attributesToArray());
            }
        });

    return $response;
}
```
Not sure how to do Streaming in PSR-7 though.

For regular responses, it would be easier:

```php

function getExcel()
{
    $writer = WriterFactory::create(Type::XLSX);

    $response = $writer->openResponse('results.xlsx');
    
    // Add headers
    $writer->addRow($columns);

    // Add all the rows
    foreach ($items as $item) {
        $writer->addRow($item->attributesToArray());
    }

    return $response;
}
```
In that case, the output could just be added to the response. Returning the response would handle the headers/content correctly.

**Comment by adrilo** [comment]
Hey @barryvdh,

Having a tighter integration of Spout into the main PHP frameworks (Symfony, Laravel, ...) is something that would be great! I started looking at it few months ago but my knowledge of these frameworks is pretty limited/outdated (last time I used Symfony, it was the 1.4 version!).

Although this would be a great addition, I think the development of the Symfony/Laravel plugins needs to happen in a separate repo (which I'll be happy to contribute to). I'll read more about the StreamedResponse to have a better understanding of what can be done with it.

I assume that it will be useful for reading files, not writing though. You make a GET request to an API that returns the content of an XLSX file, sending each line to the client as Spout is done reading it.

Would you be interested in working on that?

**Comment by adrilo** [comment]
Hey @barryvdh,

Check out the new wiki page about how to use Spout with Symfony's StreamedResponse: https://github.com/box/spout/wiki/%5BSymfony%5D-Stream-content-of-a-large-spreadsheet

What do you think of it? Is there anything that should be added/removed/changed?

**Comment by barryvdh** [comment]
I don't think you need the `$response->send()` in the last example, just return the response.

Also, the headers are not added now, right?

**Comment by adrilo** [comment]
You are right about the response. Regarding the headers, is it necessary to set them if the response type is html?

**Comment by adrilo** [comment]
I added the headers.

**Comment by maiermic** [comment]
Where is the example? The Wiki does not exist anymore. I found a guide [[Symfony] Stream content of a large spreadsheet](http://opensource.box.com/spout/guides/symfony-stream-content-large-spreadsheet/), but that is only about reading and not about writing CSV to a PSR-7 Response object.

**Comment by adrilo** [comment]
There's no such example but if you can create one, I'd be happy to add it to the guide
