### ISSUE TITLE
XLSX float numbers with ',' not '.'

### ISSUE THREAD

**Issue by bitbuit** [box/spout#136]
My country (spain), uses "," instead of "." for the decimal symbol.

I use **addRow($array)** function and when i export to XLSX and open the Excel, the cell is a string not numeric.

I try to convert it with **number_format** function, but obviously the cell remains string.

Bug or feature?

**Comment by adrilo** [comment]
Hi @bitbuit!

I tried reproducing the issue but Excel (2010, Mac version) works as expected. What I observed is that Excel uses the decimal separator defined at the OS level (`.` or `,` in my case).

Other Excel versions may behave differently though. Can you tell me which Excel version as well as wich OS you are using?

BTW, I used this code to write a numeric value to a cell: `$writer->addRow([12.34]);`.

**Comment by bitbuit** [comment]
Hi @adrilo !
I enhanced my search about this, and sorry because the problem is mine, i pass a STRING not a NUMBER! My data source was a string field (i think that was number), and obviously not works.

Previously i cast the value into a float and works well!

**Comment by adrilo** [comment]
Glad you figured it out!
