### ISSUE TITLE
How to extract images in file excel ?

### ISSUE THREAD

**Issue by caohothang** [box/spout#137]

**Comment by adrilo** [comment]
Hi @caohothang! Unfortunately, Spout does not support extracting images.

**Comment by caohothang** [comment]
hi @adrilo 
Can you know another plugin support extract images and large file exel ?

**Comment by adrilo** [comment]
Spout is the only PHP library that supports large Excel files but it can't extract images. I'd say your best chance is by using PHPExcel with all the caching optimizations it has. However, if your file is really big, it won't work... Sorry I can't help you more

**Comment by caohothang** [comment]
@adrilo Thanks for your support
