### ISSUE TITLE
Too big xlsx

### ISSUE THREAD

**Issue by ivanchenkoandriy** [box/spout#140]
http://i.imgur.com/5PQx25U.png
csv file size 14 MB
must remove empty fields
http://i.imgur.com/PwSDQFL.png

/vendor/box/spout/src/Spout/Writer/XLSX/Internal/Worksheet.php
http://i.imgur.com/zSJq5la.png

after remove empty fields
http://i.imgur.com/kSG1Mze.png
but very slowly opened
compared to xlsx created from csv with help excel

**Comment by ivanchenkoandriy** [comment]
/vendor/box/spout/src/Spout/Writer/XLSX/Internal/Worksheet.php
http://i.imgur.com/zSJq5la.png

**Comment by ivanchenkoandriy** [comment]
after remove empty fields
http://i.imgur.com/kSG1Mze.png
but very slowly opened
compared to xlsx created from csv with help excel

**Comment by adrilo** [comment]
Good catch! Feel free to submit a pull request :)

**Comment by ivanchenkoandriy** [comment]
I tried, but asked some agreement approved and signed by than
I'm from Ukraine
I do not know much English, so I could not pull
Thank you for your project
I wish you success in the project
Бажаю успіхів

**Comment by adrilo** [comment]
No worries. I'm pushing the change for you.
