### ISSUE TITLE
Array index not consistent

### ISSUE THREAD

**Issue by seegithub** [box/spout#144]
Hi,

hi, I am very impressed with the performance of this library, but there was an error when I want to read the excel file, it happened like this :

I have 3 rows of data , the contents is No, Name, and Address. Then when it is done for each line of its looping will be formed 
array (
     [0] => 1,
     [1] => seegithub,
     [2] => Indonesia
)  

but when there is an empty data on column let say on column name, so its array index not consistent, array arrangement looked like this:
array (
     [0] => 1,
     [1] => Indonesia
)

this break my code, Can blanks column still exist in array, example llike this ?
array (
     [0] => 1,
     [1] => ,
     [2] => Indonesia
) 

Thanks, sorry for my bad english sir.

**Comment by adrilo** [comment]
Hey @seegithub, I tried with a file containing:

foo |       | bar
-----|------| ----

This is what is returned:
```
array(3) {
  [0] =>
  string(3) "foo"
  [1] =>
  string(0) ""
  [2] =>
  string(3) "bar"
}
```

Can you give me more details on what your file with the blank column looks like?

**Comment by seegithub** [comment]
Hi,

sorry for late response, it looks like my excel file that has an error, i am sorry thank for this great work.
