### ISSUE TITLE
Where i can download this extension ?

### ISSUE THREAD

**Issue by khoiruddin** [box/spout#147]
php_xmlreader
php_simplexml

**Comment by adrilo** [comment]
It should be pre-installed with PHP:
- http://php.net/manual/en/xmlreader.installation.php
- http://php.net/manual/en/simplexml.installation.php

It's possible that these two extensions are disabled though. You'll need to enable them before being able to use Spout

**Comment by khoiruddin** [comment]
OK, thanks :+1:
