### ISSUE TITLE
Page breaks feature (RowBreaks)

### ISSUE THREAD

**Issue by bitbuit** [box/spout#148]
Hello! Now i'm work in a project that i need do a Page Breaks i searched and i found some information about this. 

http://openxmldeveloper.org/discussions/formats/f/14/t/928.aspx

I'll try to modify the library but i need help! Can i Help me?

I upload a file with 4 manual RowBreaks at lines (2, 5, 12, 15)

[breaks.xlsx](https://github.com/box/spout/files/35721/breaks.xlsx)

Norbert.

**Comment by adrilo** [comment]
Hey @bitbuit,

To support row breaks, I would add a top-level function to the XLSX writer (src/Spout/Writer/XLSX/Writer.php): `addRowBreak()`. It would be similar to the `addRowToWriter()` function in the same function.

I'm not familiar with how to add row breaks but from the link you sent, it seems like it's just a bunch of XML tags. Also, it seems like you need to add all the row breaks at once. This means that you'll need to keep track of where the row breaks are, and write the `<rowBreak>` content on close, when you know where all row breaks will be.

Hope that helps!

**Comment by bitbuit** [comment]
Hey @adrilo !

I have a problem! Now i implemented the RowBreak in the file: XLSX/Internal/Worksheet.php:

```php
    protected function writeRowBreaks()
    {
        $l = sizeof($this->rowBreaks);
        if ($l == 0) return;

        $data = '<rowBreaks count="' . $l . '" manualBreakCount="' . $l . '">' . PHP_EOL;
        foreach ($this->rowBreaks as $v) 
        {
            $data .= '  <brk id="' . $v . '" man="true" max="16383" min="0"/>' . PHP_EOL;
        }
        $data .= '</rowBreaks>';

        $wasWriteSuccessful = fwrite($this->sheetFilePointer, $data);
        if ($wasWriteSuccessful === false) {
            throw new IOException("Unable to write rowBreaks in {$this->worksheetFilePath}");
        }

    }
```

and modify close() function:

```php
    public function close()
    {
        fwrite($this->sheetFilePointer, '    </sheetData>' . PHP_EOL);
        $this->writeRowBreaks();
        fwrite($this->sheetFilePointer, '</worksheet>');
        fclose($this->sheetFilePointer);
    }
```

and add an atribute: 

```php
    /** @var array List of the row breaks */
    protected $rowBreaks = [10, 20];
```

And it works very good! But it's necessary to create the top-level function: addRowBreak()
You suggest that that put it in (https://github.com/box/spout/blob/45980195cd038149d7d153bc1eb3e78e5c8cf8be/src/Spout/Writer/XLSX/Writer.php)

But i don't know how to do it, correctly. Pleaase can you help me?

**Comment by bitbuit** [comment]
Hi @adrilo , i solved the problem and i want to contribute it.

Please contact me.

**Comment by adrilo** [comment]
Hey @bitbuit,

I'm glad you solved your problem. To contribute, please read the instructions here: https://github.com/box/spout/blob/master/CONTRIBUTING.md. It should help you setting up a fork and submitting a pull request!
