### ISSUE TITLE
xlsx mime type

### ISSUE THREAD

**Issue by garak** [box/spout#149]
I'm creating an xlsx file (e.g. using ``Type::XLSX``).
I expect to get a file with mime type ``application/vnd.openxmlformats-officedocument.spreadsheetml.sheet``, instead I'm getting one with ``application/zip``.

**Comment by adrilo** [comment]
Hmmm this is weird. Are you calling the `openToBrowser()` function?

**Comment by garak** [comment]
No, I'm just using ``openToFile`` and ``close`` to create the file.
I checked the mime type using ``file -b --mime mygeneratedfile.xlsx``

**Comment by adrilo** [comment]
Oh I see. Then it makes sense, as an XLSX is simply a ZIP file with the "xlsx" extension.
Let me check if there is a way to set the mimetype of the file on save.

By the way, why do you need to check the mime type?

**Comment by garak** [comment]
My use case is a generated xlsx file, that I have to serve afterwards.
I'd like to rely on the mime type took from file, instead of forcing it with an HTTP header.
There must be a way, since running the same command (``file -b --mime``) on other xslx files gives me the correct type.

**Comment by adrilo** [comment]
How did you create the other xlsx files? Excel? Which version of Excel?
With Excel 2010 on Mac/Windows, `file -b --mime` returns `application/zip`.

**Comment by garak** [comment]
I know that ``application/zip`` is also a valid mime type for xlsx, anyway we know that a generic user would expect an excel file to be served/opened as a spreadsheet, not like an archive.
Unfortunately, I don't own any copy of Excel to try, anyway you can find many sample files online (like [this one](http://dl.sample-files.com/doc/sample_Office2013_EXCEL_XLSX_1.xlsx.zip)), all with the "correct" mime type.

**Comment by adrilo** [comment]
Hmmm even with the file you sent me I have:

```
$ file -b --mime ..../1.xlsx
application/zip; charset=binary
```

**Comment by garak** [comment]
Of course it is, it depends on the configuration of your magic.
The point is that library is generating files with a magic number that is not the same as the "official", so even with the correct magic configurated (e.g. on a standard Ubuntu), you get a generic mime instead of a specific one.

**Comment by garak** [comment]
Here is a different try. Write a script called ``fileinfo.php``:
```php
<?php
$finfo = new \finfo(FILEINFO_MIME_TYPE);
echo $finfo->file($argv[1]).PHP_EOL;
```
With a such file, ``php fileinfo.php 1.xlsx`` is returning ``application/vnd.openxmlformats-officedocument.spreadsheetml.sheet``, while ``php fileinfo.php file_generated_with_spout.xlsx`` is returning ``application/zip``

**Comment by adrilo** [comment]
Cool! I can reproduce the issue :)

```
$ php file.php spout-test/test-numeric2.xlsx
application/octet-stream
```

I don't have `application/zip` but `application/octet-stream`... Anyway, I'll try to take a look at it to figure out how the mime type is being set

**Comment by adrilo** [comment]
Hey @garak,

After pulling my hair out for a few hours, I finally figured out why the mime type is wrong. It turns out the order in which the XML files gets added to the final ZIP file (an XLSX file being a ZIP file with the xlsx extension) matters for the heuristics used to detect types.

Currently, files are added in this order:
```
[Content_Types].xml
_rels/.rels
docProps/app.xml
docProps/core.xml
xl/_rels/workbook.xml.rels
xl/sharedStrings.xml
xl/styles.xml
xl/workbook.xml
xl/worksheets/sheet1.xml
```

The problem comes from inserting the "docProps" related files. It seems like the heuristic is to look at the first few bytes and check if it finds `Content_Types` and `xl`. By having the "docProps" files inserted in between, the first `xl` occurrence must happen outside of the first bytes the algorithm looks at and therefore concludes it's a simple zip file.

I'll try to fix this nicely

**Comment by garak** [comment]
Great! Hope to see a new tag released soon.
Thank you.
