### ISSUE TITLE
Delete Sheet1

### ISSUE THREAD

**Issue by jamesryanbell** [box/spout#150]
Hi

Is there a way to prevent Sheet1 from being created when working with custom sheets?

Or is there a method to delete sheets that I can use after everything is complete?

Thanks,
James

**Comment by adrilo** [comment]
Hi @jamesryanbell,

If you want to skip sheet1, you can simply create a new sheet and start using it before writing any data:

```php
$writer = WriterFactory::create(Type::XLSX);
$writer->openToFile($filePath);

// add new sheet before writing any data
$writer->addNewSheetAndMakeItCurrent();

// the row will be written in Sheet2
$writer->addRows([.....]);

$writer->close();
```

Hope that helps!

**Comment by jamesryanbell** [comment]
Hi @adrilo

I am looking to export a file without Sheet1 completely. This would just skip sheet1.

Thanks
James

**Comment by adrilo** [comment]
Hmmm I'm not sure to understand what you are trying to do then.
You are creating a new XLSX file and do not want to have Sheet1 in there. Then what should the first sheet be?

**Comment by jamesryanbell** [comment]
I have a dataset I will be splitting across different sheets, each sheet will be named based on the category it falls into.

The end result I want is to only have the custom named sheets. Currently I have this working but I am still left with the auto generated Sheet1 which is empty.

**Comment by adrilo** [comment]
You need to call this before creating a new sheet:

```php
$sheet = $writer->getCurrentSheet();
$sheet->setName('My custom name');
```

For instance, this code gives a spreadsheet whose first and only sheet is named "foo":
```php
$writer = WriterFactory::create(Type::XLSX);
$writer->openToFile('test.xlsx');

$sheet = $writer->getCurrentSheet();
$sheet->setName('foo');

$writer->addRow(['bar']);
$writer->close();
```

**Comment by BreiteSeite** [comment]
While i agree that this is a way of accomplishing this, from a code perspective this can lead easily to error-prone and unnecessary code.
Imagine you have 10 methods, that each adds their own sheet.

```
public function addSheet1(Writer $writer);
public function addSheet2(Writer $writer);
public function addSheet3(Writer $writer);
...
public function addSheet10(Writer $writer);
```

Now how do you ensure, that the method, that gets called first uses the `getCurrentSheet()` instead of the `addNewSheetAndMakeItCurrent()` function? I mean it's possible, but you need to create another method maintaining the state (more than one sheet already created etc). This unnecessary bloats the code.

I agree with the author of this issues that it would be nice to prevent creation of the default sheet and/or at least to support deletion of sheets.

**Comment by termene7** [comment]
Same issue here. It would be amazing if we could skip sheet1

**Comment by nickhagen** [comment]
I had this same issue, here is the solution that I used, loop through your categories and add this to select the right sheet, essentially if you are in the first category, rename Sheet1, otherwise add a new Sheet and rename it.
```
foreach ($categories as $category => $data) {
            if ($category === array_key_first($categories)) {
                $sheet = $writer->getCurrentSheet();
            } else {
                $sheet = $writer->addNewSheetAndMakeItCurrent();
            }

            $sheet->setName($category);
            $header = array_keys($users[0]);
            $writer->addRowWithStyle($header, $headerStyle);
            $sheet->addRows($data);
}

$writer->close();
```
