### ISSUE TITLE
What are the a ways to overcome the Access denied Error when Spout tries to Use the default System TEMP directory?

### ISSUE THREAD

**Issue by in1gotech-jdjaviniar** [box/spout#156]
I let Spout use the default system directory but I got this error:

````RecursiveDirectoryIterator::__construct(C:\WINDOWS\TEMP/xlsx5673f4d7f325a6.46823532,C:\WINDOWS\TEMP/xlsx5673f4d7f325a6.46823532): Access is denied. (code: 5)````

**Comment by in1gotech-jdjaviniar** [comment]
Since I do not know how to grant `Spout` access to the default system folder I just created a 'temp' folder in my project and used `$writer->setTempFolder($customTempFolderPath);` to point the temp folder to appropriate directory.

**Comment by adrilo** [comment]
:+1:
