### ISSUE TITLE
Is there a feature that will allow an application to open a template file and write data directly to it?

### ISSUE THREAD

**Issue by in1gotech-jdjaviniar** [box/spout#157]

**Comment by adrilo** [comment]
Hi @in1gotech-jdjaviniar,

Can you give me an example of what you'd like to do? I'm not sure to understand correctly

**Comment by in1gotech-jdjaviniar** [comment]
For example, I already have a an `XLSX` file that  contains pre-formatted headers, I want to load or open that file using Spout and write data after the headers. In the documentation You can create new XLSX file using the Writer factory but I want something like `PHPExcel`'s [feature](https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/10-Reading-and-Writing.md#generating-excel-files-from-templates-read-modify-write) that allows you to load an existing file and write to it.

**Comment by adrilo** [comment]
I just created some wiki pages, documenting how to do what you are trying to do: https://github.com/box/spout/wiki.

Please re-open this issue if this does not exactly fit your needs.
