### ISSUE TITLE
getSheetIterator() returns sheets not in the right order

### ISSUE THREAD

**Issue by casperbakker** [box/spout#163]
(First: we love box/spout, it works really well and we use it a lot. Thanks!)

We use box/spout for a 'product import' where we only use the first sheet. This works well in most cases but now we experienced something weird. Looks like some versions of Excel declare their sheets in [Content_Types].xml in a different order then they are displayed in Excel. Excel opens them in the 'right' way, but box/spout in the order they appear in the xml.

When we open such a 'bad' Excel in the latest Excel for Mac, it opens normally. When we save a copy of it from that Excel, the sheets in the xml are in the right order and now box/spout returns the sheets in the right order.

Apparently, Excel uses another location where they store the order of sheets. **Is it possible to change the order of sheets in box/spout to exactly as they appear in Excel?**

![screen_shot_2015-12-24_at_14_08_15](https://cloud.githubusercontent.com/assets/886975/11995330/376b679c-aa4f-11e5-978e-5ab64624f6ad.png)

We now 'fixed' it by looping through the sheets until we find one with at least 1 row in it. But it looks like a bug to us. Maybe there is a way to fix this in box/spout the right way?

**Comment by adrilo** [comment]
Hi @casperbakker, glad you like the library :)
Regarding the issue, thanks for reporting it. To help fixing it, do you mind copying here the copy of the `xl/workbook.xml` file? I believe that this file contains the correct order, but just want to make sure.

**Comment by casperbakker** [comment]
Hi @adrilo 

Looks like you're right. Hereby from both files the xl/workbook.xml file.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
    <fileVersion appName="xl" lastEdited="4" lowestEdited="4" rupBuild="4507"/>
    <workbookPr defaultThemeVersion="124226"/>
    <bookViews>
        <workbookView xWindow="0" yWindow="90" windowWidth="28755" windowHeight="12585"/>
    </bookViews>
    <sheets>
        <sheet name="Blad1" sheetId="1" r:id="rId1"/>
        <sheet name="Blad2" sheetId="2" r:id="rId2"/>
        <sheet name="Blad3" sheetId="3" r:id="rId3"/>
    </sheets>
    <calcPr calcId="125725"/>
</workbook>
```

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x15" xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main">
    <fileVersion appName="xl" lastEdited="6" lowestEdited="4" rupBuild="26311"/>
    <workbookPr/>
    <mc:AlternateContent xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006">
        <mc:Choice Requires="x15">
            <x15ac:absPath url="/Users/stephan/Downloads/" xmlns:x15ac="http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac"/>
        </mc:Choice>
    </mc:AlternateContent>
    <bookViews>
        <workbookView xWindow="5960" yWindow="2540" windowWidth="29640" windowHeight="17320"/>
    </bookViews>
    <sheets>
        <sheet name="Blad1" sheetId="1" r:id="rId1"/>
        <sheet name="Blad2" sheetId="2" r:id="rId2"/>
        <sheet name="Blad3" sheetId="3" r:id="rId3"/>
    </sheets>
    <calcPr calcId="125725" concurrentCalc="0"/>
    <extLst>
        <ext uri="{7523E5D3-25F3-A5E0-1632-64F254C22452}" xmlns:mx="http://schemas.microsoft.com/office/mac/excel/2008/main">
            <mx:ArchID Flags="2"/>
        </ext>
    </extLst>
</workbook>
```

**Comment by casperbakker** [comment]
Thanks @adrilo !
