### ISSUE TITLE
Get validation error message after opening created .xlsx file

### ISSUE THREAD

**Issue by cannect** [box/spout#168]
Hello,

I just create .xlsx files with this code: 

```
        $writer = WriterFactory::create( Type::XLSX );

        $writer->openToBrowser( $filename );

        // Headers
        $writer->addRow( array( 'Order #', 'Customer name', 'Total ordered', 'Date' ) );

        // Then a foreach
        $writer->addRow( array( (int) 0000, 'Customer name', (float) 23.12, '20-01-2016' ) );
        $writer->close()

```

And thats it.
After opening this file in Excel 2013 I get the message that the file is corrupted and needs to be repaired. Also the float 'Total ordered' is not a float in Excel at all.

How can I prevent the needs to be repaired message of every file?

Thanks!

**Comment by adrilo** [comment]
Hi @cannect, do you mind attaching a sample file that causes this error? It would be super helpful

**Comment by cannect** [comment]
Hi @adrilo,

Thanks for your attention. See the attached file below.

[Bestellingen export 05-01-2016 - 14-01-2016.xlsx](https://github.com/box/spout/files/95530/Bestellingen.export.05-01-2016.-.14-01-2016.xlsx)

**Comment by jonsito** [comment]
I can confirm that attached file is also marked as damaged an cannot be repaired with LibreOffice 5

**Comment by adrilo** [comment]
I confirm that I also see the error message with the file you sent me.
However, when I try to create a file with the same content, it does work for me. Also, unzipping your file and zipping it again fixes the issue.

Two questions:
- is your encoding set to UTF-8?
- which version of PHP/Zip are you using? (you can get the zip version by running `php -i | grep -C 2 "Zip version"`)

**Comment by cannect** [comment]
Hi @adrilo,

Here are the results of the commands: 
```
Zip => enabled
Extension Version => $Id: abc21c7f1559e732dba6db94c69ecf638ae5fa3f $
Zip version => 1.11.0
Libzip version => 0.10.1
``` 

Also my encoding is by default set to UTF-8? I just create the writer with: `$writer = WriterFactory::create( Type::XLSX );`

**Comment by adrilo** [comment]
According to http://php.net/manual/en/xml.encoding.php, the default source encoding is ISO-8859-1.
Can you try setting the encoding to UTF-8 first, and let me know if this fixes the issue?

**Comment by cannect** [comment]
Hi @adrilo,

I cannot find where to set the encoding via the WriterFactory? I looked in the source and I did not found a way to set it via the Spout class?

**Comment by adrilo** [comment]
Setting the page encoding is different from setting the encoding used by PHP. Using header() only tells the browser which encoding was used to build the page and how it should be rendered.

What you need to do instead is calling `mb_internal_encoding('UTF-8');` - this is a PHP function, not a Spout one. This should be one of the first thing you do. If you use a framework, add it to the front controller, otherwise add it at the top of your PHP file, before using Spout.

**Comment by cannect** [comment]
@adrilo, 

You are right about that. However when using `mb_internal_encoding('UTF-8');`, the validation message still appears. To double-check I did a var_dump on `mb_list_encodings()` and saw `UTF-8` was listed. I am out of options now, is there anything I can do to get this working?

**Comment by adrilo** [comment]
@cannect, thanks for checking. I'm suspecting it's an issue with the libzip library.
When I unzip the XLSX file you sent me and zip it again with the zip library installed on my machine (Zip 1.12.5, Libzip 0.11.2), it works. This means that the content inside the XLSX file is correct.

Do you have the possibility to upgrade the PHP zip library installed on your machine/server? Or upgrade PHP directly?

**Comment by cannect** [comment]
I updated PHP to 5.5. But the Zip and Libzib seems not to be updated. I don't mind updating PHP to 5.6 now because on my VPS run multiple websites. I cannot foresee the impact on every bit of PHP code on every website, and if it will successfully run on 5.6. 

So I googled how to update Zip and Libzip. However there is where I am stuck now. But I do not ask you to give support for that. ;-) 
But I just let you know that I cannot update PHP now, and upgrading Zip and Libzip is beyond my knowledge. We have to live with the validation messages or (don't think so, but it is an option) switch to another XLSX writer.

So huge thanks for all the help for @adrilo !

**Comment by MustangZhong** [comment]
@cannect 
I got the same issue, my zip config below:

Zip => enabled
Extension Version => $Id: c203148334b6f80d27bc5d23fad5ec3ca7dcf444 $
Zip version => 1.12.5
Libzip version => 0.11.2

PHP version: 5.6.17

any idea?
thanks!

**Comment by adrilo** [comment]
Thanks for chiming in @MustangZhong! We have the same zip version but I can't repro the issue on my machine...

Can you try downgrading Spout to v2.1.0 for instance. Just want to make sure no regressions were introduced in the latest versions?

**Comment by adrilo** [comment]
@cannect can you also try downgrading Spout?

**Comment by MustangZhong** [comment]
@adrilo Thanks for your reply.
The issue was occured on my testing server. but on the production server, it works fine.
so it's quite strange. the config of these two server are the same. so I guess there's somting wrong on my testing server.

thanks again. Good day!

**Comment by adrilo** [comment]
Hey @MustangZhong, I'm glad the error is gone for you.

It would be great if you could help me figure out why it happened, as other users are experiencing the same issue. Are you using the same PHP version of both servers (dev and prod)?

**Comment by shadz3rg** [comment]
This is not a library issue. 
Use `exit;` immediately after `$writer->close();` as with downloading files.

**Comment by adrilo** [comment]
@MustangZhong @cannect, can you try what @shadz3rg suggested?

**Comment by MustangZhong** [comment]
it works！thanks oleg！

Mustang Zhong

**Comment by carolinecdsantos** [comment]
Thanks @shadz3rg ! It's worked for me! :+1:

**Comment by amardeepthadisetty** [comment]
Thank you, it worked for me !!!!

**Comment by mathieumuller** [comment]
IMO the answer of @shadz3rg should be in the documentation

**Comment by japita-se** [comment]
why it works?!

**Comment by alan469394** [comment]
response the blob object include other string or something ,
So, use exit; immediately after $writer->close(); can make sure your blob object which is not including other data type.
i guess~
if you check blob obj , may have status(array) at last line.
