### ISSUE TITLE
How To Get Data From Database and store to XLSX with spout

### ISSUE THREAD

**Issue by tarikhagustia** [box/spout#171]

**Comment by adrilo** [comment]
Hi @tarikhagustia,

You can take a look at the code in this repo: https://github.com/adrilo/spout-pdo-example.
It's probably more complex than what you need, but if you reuse it, it will give you a solid and scalable foundation to get data from a DB and store it in an XLSX file.

Let me know if you have additional questions.

**Comment by tarikhagustia** [comment]
oke thanks, if i want to show the file automaticaly, how? 
thanks before..

**Comment by adrilo** [comment]
Use openToBrowser() instead of openToFile()
