### ISSUE TITLE
Incompatible EOL on CSV reader...

### ISSUE THREAD

**Issue by sfichera** [box/spout#172]
Hi, I've found the following issue...

When you try to use the reader with CSV files that were generated by OSX version of Excel, the rowIterator has a problem while reading lines because the EOL on those files is **\r **instead of **\n**...
For the moment I've added an ugly hack to the openReader function that detects the EOL based on file information...

protected function openReader($filePath)
**        $EOLFix =  "\n";
        $output = shell_exec('file ' . $filePath);
        if (strpos($output, 'CR') !== false) {
            $EOLFix =  "\r";
        }**

        $this->filePointer = $this->globalFunctionsHelper->fopen($filePath, 'r');
        if (!$this->filePointer) {
            throw new IOException("Could not open file $filePath for reading.");
        }

        $this->sheetIterator = new SheetIterator(
            $this->filePointer,
            $this->fieldDelimiter,
            $this->fieldEnclosure,
            $this->encoding,
            $this->globalFunctionsHelper,
**            $EOLFix**
        );
}

Clearly this isn't the most elegant solution, also it won't work on windows environments nor when you has no access to execute shell commands. But I've covered my current needs... So I'm opening this issue looking forward for a final and better solution... :-)
Please keep in mind that my CSV files are huge so, do a replace of EOL at file upload/save time is not an option.

**Comment by adrilo** [comment]
Hi @sfichera, thanks for filing this issue.

I guess, the best way to solve it is to introduce a way to tell Spout what EOL character should be used (similar to the `setFieldDelimiter` and `setFieldEnclosure` functions).
Alternatively, Spout can try to normalize line endings before parsing them (replacing "\r" and "\r\n" with "\n") but as you said, this method will fall apart with large files.

So I'd definitely go with option 1 and add a `setEndOfLineCharacter` function to the Reader. Would you be interested in giving it a try? It's an easy way to contribute to the project :)

**Comment by sfichera** [comment]
Sure! I'm glad to help...

**Comment by nCrazed** [comment]
Excellent timing, just ran into a similar problem.

@adrilo any chance of this change being merged and released sometime soon?

**Comment by adrilo** [comment]
Yes, we just need one test for this change and I'll merge and release a new version!

**Comment by sfichera** [comment]
Hi Adrien, hoy are you?

Please note that yesterday I've already committed a test case related to this...

https://github.com/sfichera/spout/commit/86e26632f6b82e5ce418a3b01aa504f011e1f402

:-)

**Comment by adrilo** [comment]
Just released v2.4.2 :) Thanks for contributing @sfichera!
