### ISSUE TITLE
Packagist URL

### ISSUE THREAD

**Issue by IlyaBakhlin** [box/spout#174]
It would be nice if the project had the Packagist URL in the description.

**Comment by adrilo** [comment]
Can you help me understand why? The main packagist page only contains things you can find on the Github page. And I believe the other linked pages (Stats, Dependencies, ...) are not super useful if what you want is just use the library.

Am I missing something?

**Comment by IlyaBakhlin** [comment]
In my opinion, when you open some repository of PHP library, it would be nice to fill the web site field with the Packagist URL. I think it makes the repository more complete.

Because, as I understand, nobody creates a web page for a repository, but Packagist does, so you can use it.

It's just my opinion.

**Comment by IlyaBakhlin** [comment]
By the way, where do you get those images with the downloads count, version number, etc?

**Comment by adrilo** [comment]
I'm using https://poser.pugx.org/ for the badges, which extracts data from Packagist.
I'll leave the website blank for now, as I think Packagist should be used to find packages or get stats about a project but not as a homepage. Eventually, we'll have an actual page for the project.
