### ISSUE TITLE
Stream wrapper support (at least for CSV)

### ISSUE THREAD

**Issue by VirtualRJ** [box/spout#176]
As mentioned in #132 with the addition of a `realpath()` in the `open()` it is not possible to open a file with a streamwrapper. Among other stream wrappers Amazon S3 uses stream wrappers to bring support for standard file operations using `s3:\\[filepath]`. I'm trying to read a CSV file from S3, but the only issue is the `realpath()` (I tested it without the `realpath()`). I understand it's much harder to find a solution for `XMLReader()`, but that class is not used for CSV files. Is there some way to skip the realpath check for streamwrappers (for example with config setting or param)?

**Comment by adrilo** [comment]
Potentially, a check can be added to see if the given file path is a custom stream wrapper. If it is, there is no need to use realpath. However, this is only useful for CSV as other file types don't support stream wrappers. Not sure if it's worth it and if there is a clean way to do this.

Feel free to submit a pull request though :)

**Comment by adrilo** [comment]
@VirtualRJ, please let me know if the commit I just pushed fixes your issue.

**Comment by VirtualRJ** [comment]
@adrilo looks like a nice clean solution. will test as soon as I get the possibility.
