### ISSUE TITLE
Select sheets for reading

### ISSUE THREAD

**Issue by graham4915** [box/spout#180]
Hello,

Thanks for this library. I have been trying to use it however the files I need to read are very large and I would like to instruct spout to only read a sheet with a specific fixed name 'summary' (whose position can change). How can I proceed ?
Would it then be possible to output this sheet only to CSV ?

I haven't found an answer in the readme.
Thank you for your help !

**Comment by adrilo** [comment]
Hi @graham4915,

The trick is to go through all the sheets until you find the one you are interested in. Then read all the rows from this sheet and export to a CSV. Here is how to do it:

```php
$inputFilePath = '....';
$outputFilePath = '....';

$reader = ReaderFactory::create(Type:XLSX);
$reader->open($inputFilePath);

$writer = WriterFactory::create(Type::CSV);
$writer->openToFile($outputFilePath);

foreach ($reader->getSheetIterator() as $sheet) {
    // only read data from "summary" sheet
    if ($sheet->getName() === 'summary') {
        foreach ($sheet->getRowIterator() as $row) {
            $writer->addRow($row); // write the read row to the CSV file
        }
        break; // no need to read more sheets
    }
}

$writer->close();
$reader->close();
```

Hope that helps! Let me know if you have additional questions.

**Comment by aferrop** [comment]
Good! please, include this trick in the readme

**Comment by adrilo** [comment]
Done! https://github.com/box/spout/wiki/Read-data-from-a-specific-sheet-only
