### ISSUE TITLE
XML Reader error

### ISSUE THREAD

**Issue by samirhshaikh** [box/spout#185]
hi,

I have installed version 2.4.2 of spout class. I am getting following error when performing basic read operation on a XLSX file.

PHP Fatal error:  Call to undefined method Box\\Spout\\Reader\\Wrapper\\XMLReader::readOuterXml() in /srv/sandbox/ws/branches/development-v2/htdocs/DL/3rdparty/vendor/box/spout/src/Spout/Reader/XLSX/Helper/SharedStringsHelper.php on line 184

I have already enabled php_zip, php_xmlreader, and php_simplexml. I am using PHP 5.5.26

Thanks.

**Comment by adrilo** [comment]
According to http://php.net/manual/en/xmlreader.readouterxml.php, "This function is only available when PHP is compiled against libxml 20620 or later."
