### ISSUE TITLE
XLSX Writer file not closed properly

### ISSUE THREAD

**Issue by SauloARS** [box/spout#190]
Hi,

Reporting a bug: after using `$writer->close();` the file is not being released.
My Code:

```
$writer = WriterFactory::create(Type::XLSX);
$writer->openToFile($filename);
(...)
$writer->close();
(...)
unlink($filename);
```

Unlink returns an error (Permission Denied). Using windows cmd del also doesn't work.
The file can be deleted after the php process finishes.

My fix was to add one line to the close() function, in Box\Spout\Writer\AbstractWriter.php

```
public function close()
{
    $this->closeWriter();
    $this->isWriterOpened = false;
    fclose($this->filePointer); // Added this line
}
```

**Comment by adrilo** [comment]
Good catch!
