### ISSUE TITLE
Add a comment to a cell

### ISSUE THREAD

**Issue by mirabs** [box/spout#198]
Hi;

Is it possible to add a comment to a cell with Spout?

**Comment by adrilo** [comment]
Unfortunately, it's not.

**Comment by skeleton** [comment]
Hi @adrilo,

do you accept contribution to add this feature?

Thanks

**Comment by adrilo** [comment]
Of course. We want to have feature parity for ODS and XLSX though, so make sure to add support for both formats (and add tests!).
