### ISSUE TITLE
Total number of rows for a sheet.

### ISSUE THREAD

**Issue by FernandoBasso** [box/spout#201]
If I iterate over thousands of rows on a sheet, I need a way to calculate how much I have done already so I can also update UI or other things.

So, the question is: Is there already some way to get the total number of rows for a sheet?

I know I can manually count the number of rows as they are being read, but it would be useful in some situations to know that before starting the iteration.

**Comment by tomikulmala** [comment]
+1

**Comment by adrilo** [comment]
This is similar to #170. I gave some details about why this is unfortunately not possible (or at least not consistently). The only reliable option is to process 2 the file twice (which you don't want to do :P)

**Comment by FernandoBasso** [comment]
Okay. Thanks for the link to the other issue. I completely understand. For the task I have at hand now, I'll just update the user on the number of rows already processed rather than the percentage remaining. It will do just fine.

Thanks a lot for for everything.

**Comment by sanketin2** [comment]
Currently it's reading all the data in row so looping that for just getting total number of rows would be very slow. If any function that just give us row exists and we increment the counter to getting total rows would be great. Example: "while ($reader->hasNextRow()) { $totalRows++; }" 

I am looking this kind of solution for xls/xlsx.
