### ISSUE TITLE
Formula extraction support for XLSX files

### ISSUE THREAD

**Issue by yort** [box/spout#204]
Hi guys,

It is possible to add support for extracting of formula from XLSX cells?

I am not looking at parsing of formula for calculating values, instead just returning the formula itself would be helpful.

It looks like formula is always in a <f> element within which ever value (eg. within <c> elements).

I attempted a dirty hack by adding in another formatting function at https://github.com/box/spout/blob/master/src/Spout/Reader/XLSX/Helper/CellValueFormatter.php#L92 but its just that a dirty hack.

Is there a way to add support for formula extraction, or a way to extend the reader to support this extraction?

Thanks
YorT

**Comment by adrilo** [comment]
Hi @yort, this is not currently supported but I can add it to the roadmap for v3.
v3 should introduce a more granular reader/writer. So instead of rows, you can deal with cells directly. This could give you the possibility to query multiple things about the current cell (like the formula). Currently, it does not make sense to return the formulas for the whole row as some cells may not have any formulas.

**Comment by yort** [comment]
Thanks @adrilo, I didnt know v3 was being worked on. Is there a time line for it as yet?

Thanks
YorT

**Comment by adrilo** [comment]
Well to be honest, v3 is not being worked on. But I'm gathering ideas and needs for when I'll have more time to work on it :)

**Comment by adrilo** [comment]
A formula is defined like this in an XLSX file:

```
	<sheetData>
		<row r="1" spans="1:2">
			<c r="A1">
				<v>1</v>
			</c>
			<c r="B1">
				<v>2</v>
			</c>
		</row>
		<row r="2" spans="1:2">
			<c r="A2">
				<f>SUM(A1,B1)</f>
				<v>3</v>
			</c>
		</row>
	</sheetData>
```

**Comment by adrilo** [comment]
I think the cost of adding and maintaining such a feature, for both XLSX and ODS, is much greater than the value it would provide (the vast majority of people are interested in the computed value, not the formula itself).
Therefore, I'm going to close this issue.
