### ISSUE TITLE
use keyword error

### ISSUE THREAD

**Issue by nasser-halabi** [box/spout#210]
Hi,
I've read a lot of positive reviews about the library and would love to use it. just to mention that I'm a beginner.
I've installed composer on the same folder my my project, installed spout and got the vendor folder which contains box and spout. 
the problem is when ever I use the "use" keyword to test the reader I get a white blank page on my website.
I tried changing the use command to : 
use vendor\box\spout\src\Spout\Reader\ReaderFactory;
But with no luck.
Removing the "use" word give a fatal error obviously. can you guys point me in the right direction.
thanks.

**Comment by madflow** [comment]
Check your PHP version. It should be >= 5.3.0

Then read:

http://php.net/manual/en/language.namespaces.rationale.php
https://getcomposer.org/doc/01-basic-usage.md#autoloading

And do:

```
// composer install box/spout
// test.php, relative to your vendor directory

require_once __DIR__.'/vendor/autoload.php';

use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;

$reader = ReaderFactory::create(Type::XLSX); // for XLSX files
//$reader = ReaderFactory::create(Type::CSV); // for CSV files
//$reader = ReaderFactory::create(Type::ODS); // for ODS files

$reader->open($filePath);

foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        // do stuff with the row
    }
}

$reader->close();
```

**Comment by nasser-halabi** [comment]
I have php 5.4.0
I really am confused do i have to modify the autoload.php? 
I tried adding the 'require_once' but didn't do anything still white page, I copied the scr folder to the same level of vendor folder still nothing happened.
what am i missing here :( .
thanks

**Comment by madflow** [comment]
Blank pages usually have an error attached to them. What does that error say? 

Also check the requirements https://github.com/box/spout#requirements - maybe you are missing something here.

However - I suspect a Composer/Namespace issue and not an issue with this library.  Since you state you are a beginner - maybe you can setup a minimal example with Composer and PHP namespaces and come back when you have familiarized yourself with the concepts?

**Comment by nasser-halabi** [comment]
Thank you for your reply madflow,
you're right I had a problem with the use keyword which I put inside my function instead of the public area in php code. I also had to add require_once __DIR__.'/vendor/autoload.php'; just below the use keyword for the code work.
