### ISSUE TITLE
XLSX Reader trims text nodes 

### ISSUE THREAD

**Issue by madflow** [box/spout#219]
The XLSX Reader trims cell values like this:

```
<si>
    <r>
        <rPr><sz val="10"/><rFont val="Arial"/><family val="2"/><charset val="1"/></rPr>
        <t>go to
        </t>
    </r>
    <r>
        <rPr><sz val="10"/><color rgb="FF0000FF"/><rFont val="Arial"/><family val="2"/><charset val="1"/></rPr>
        <t>https://github.com</t>
    </r>
    <r>
        <rPr><sz val="10"/><rFont val="Arial"/><family val="2"/><charset val="1"/></rPr>
        <t>
            please</t>
    </r>
</si>
```

but not like this:

```
<si>
    <t xml:space="preserve">text</t>
</si>
```

[sheet_with_hyperlinks.xlsx](https://github.com/box/spout/files/270022/sheet_with_hyperlinks.xlsx)

This results in:

```go tohttps://github.complease```

instead of:

```go to https://github.com please```

The ```preserve``` attribute is kind of vague: https://www.w3.org/TR/xml/#sec-white-space ```the value "preserve" indicates the intent that applications preserve all the white space.```

I do not believe, that in its absence the whitespaces, carriage returns, tabs etc. should be stripped from start and end of the string. Actually: all whitespace characters should be stripped if this is wanted behaviour.

```This specification does not give meaning to any value of xml:space other than "default" and "preserve". It is an error for other values to be specified; the XML processor MAY report the error or MAY recover by ignoring the attribute specification or by reporting the (erroneous) value to the application. Applications may ignore or reject erroneous values.```

Imho we should

* ignore it (preferred by me)
* introduce a config flag for this

**Comment by adrilo** [comment]
`space="preserve"` behavior is pretty clear: do no touch the whitespaces.
In case this attribute is missing, whitespaces should be trimmed. However, it's totally ok to add a space between each `<t>` tags that are part of the same `<si>` tag. I believe that this is how it should be implemented.

What do you think?

**Comment by madflow** [comment]
It is not that clear to me. For me this in an implicit presumption what whitespaces are and where they should be removed. I bet there are whitespaces that PHP trim() does not remove. 

But ... I have no strong opinion how this should be handled in spout. If there is a rule how to handle ```si/r/t``` - than lets do it!

Btw: This came up when copy-pasting the resource test from #218 to the xlsx tests ;)

**Comment by adrilo** [comment]
The spec says that when no attribute is specified, it's up to the parser to decide what to do with the whitespaces. I looked at how Microsoft decided to actually handle whitespaces and it seems like they aggressively remove all of them, for perf and memory reasons:
https://msdn.microsoft.com/en-us/library/ms256097(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/ms762315(v=vs.85).aspx

> As a result, a node in an XML DOM document "knows" that at least one occurrence of white space follows or precedes it, but does not know exactly how much white space there was. This method is efficient, reducing both the size of each XML file and the number of calculations required to redisplay the XML in a browser.

So I think I'll implement something similar where I'll keep only one space between each node.

**Comment by madflow** [comment]
:+1: Sounds good!
