### ISSUE TITLE
Unable to recover original row index from XLSX reader

### ISSUE THREAD

**Issue by KiNgMaR** [box/spout#230]
Hi there @adrilo et al,

in an XLSX file, completely empty rows seem to be omitted from the XML altogether. This means that for a sheet like the following example

    1 | Title  |      |
    2 |        |      |
    3 | Data   | Data |
    4 | Data   | Data |

the indices returned from `$reader->getSheetIterator()` will be assigned like this:

    0 | Title
    1 | Data
    2 | Data

which means that it's not possible to recover the original row positions (indices). This is an issue if you want to point to users to specific rows / cells in their sheets.

One possible solution would be to modify the `RowIterator` so that the index (key) returned matches the actual row number, i.e.:

    1 | Title
    3 | Data
    4 | Data

However, this clearly is a BC break, so before I make a PR, I would like to hear your opinion on this one... Thanks!

**Comment by adrilo** [comment]
Hey @KiNgMaR,

As you noticed, Spout ignores empty lines. I understand that this may not be the best behavior.
A non-breaking change can be implemented, adding the option to choose whether empty lines should be kept or ignored. This would result in:

```
0 | Title
1 | 
2 | Data
3 | Data
```

It still not what you're proposing. I'm not sure if it's better to have the row index be the row number in the spreadsheet or just an indicator that has nothing to do with the spreadsheet's structure.

If anyone has a preference, please speak up :)

**Comment by madflow** [comment]
I would prefer an option to preserve empty lines.

**Comment by KiNgMaR** [comment]
Hey,

the root issue is not really that spout actively _skips_ empty rows, it's that empty rows do not even appear in the XML:

    <row r="1" x14ac:dyDescent="0.2" ht="15.75" spans="1:17">
        ...
    </row>
    <row r="3" x14ac:dyDescent="0.2" spans="1:17">
        ...

Maybe we can have two options? One that preserves empty lines (also relevant for the other readers) and one that uses the actual row indices as keys for the iterator (not relevant for CSV). Then again these may be too many options... hence my original proposal to simply use the row indices as keys :)

One alternative would be to add the row index somewhere inside the returned row. But as it's an array, using something like _rowindex feels weird and also breaks BC in a most horrible way.

**Comment by Rushleader** [comment]
I like the idea of the option that preserves the row indexing (and adds empty rows where required). Should be the cleanest way. 
Default option should be just load the rows and skip empty I think

**Comment by adrilo** [comment]
Thanks for your input! Very valuable :)
I believe the default should be:
- preserve row indexes: because in 99% of cases, row indexes do not matter. What matters is having the rows in order of appearance.
- have an option to skip/preserve empty rows: they are both very valid use cases - if you only care about the content or if you also care about its structure (or let's say if you want to add a new row without changing the rest of the spreadsheet

Adding the option to preserve empty rows is not a breaking change and can be added anytime. Changing the row index is a breaking change unfortunately. So it will have to be rolled out as part of v3.

I think this would cover pretty much all the cases. Am I missing or overseeing something?

**Comment by KiNgMaR** [comment]
Sounds good to me :) Regarding the BC break, what do you think about defaulting the option to preserve row indices to false for v2 and then enabling it by default for v3?

**Comment by adrilo** [comment]
Do you think it's useful to have such an option? I believe most people don't care whether the indices are [1,2,3] or [1,3,4]. And I don't see why someone would want to keep the indices the way they are now.
Adding options adds some complexity to the library, so I'd be very careful about the new APIs/options we add.

Enabling the option by default for v3 is also a breaking change (as the default behavior will differ) so I'd rather stick to the original proposal.

**Comment by adrilo** [comment]
Small update as I'm looking back at this issue:
For XLSX files generated by Spout, empty rows are preserved on write and correctly read. It does not work for ODS files though (and still does not work for files where the row is missing from the XML file)
