### ISSUE TITLE
ODS Writer does not accept associative arrays

### ISSUE THREAD

**Issue by madflow** [box/spout#231]
Consider the following snippet:

```
$writer = WriterFactory::create(Type::ODS);
$writer->openToFile('okay.ods');

$data = [
  "Associative"=>"Array",
];

$data2 = [
  "Array",
];


$writer->addRow($data);
$writer->addRow($data2);

$writer->close();
```

This results in:

`PHP Notice:  Undefined offset: 0 in /home/flo/Projects/Php/spout/src/Spout/Writer/ODS/Internal/Worksheet.php on line 147`

And a Workbook looking like this:

```
| |
|Array|
```

This works in xlsx and csv.

Bug of feature?

**Comment by madflow** [comment]
#192 Okay - Feature then ;)

**Comment by adrilo** [comment]
Actually, if it works with XLSX and CSV, maybe it's better to also add it to ODS. That would make the developer experience consistent. I'll run some perf tests to see how bad this would be to add this

**Comment by adrilo** [comment]
Alright I ran some quick tests. I used an array and a hash table with 100 values/keys. I then iterated over it 100,000 times. Here is the ugly code:

```php
$hash = []; $array = [];
for ($i = 0; $i < 100; $i++) {
  $hash['index'.$i] = 'foo';
  $array[] = 'foo';
}

$start = microtime(true);

$numTimes = 100000;
for ($i = 0; $i < $numTimes; $i++) {
  foreach ($array as $val) {
//  foreach (array_values($array) as $val) {}
//  foreach (array_values($hash) as $val) {}
}

$duration = microtime(true) - $start;
echo "=> $duration seconds\n";
```

Results:
- `$array`: 0.5 seconds
- `array_values($array)`: 0.8 seconds
- `array_values($hash)`: 2.3 seconds

I guess using array_values the change would not be too bad for perfs.

**Comment by adrilo** [comment]
I can push a change to fix that.
XLSX writer uses `foreach ($dataRow as $cellValue)` which works both for arrays and associative arrays. On the other hand, ODS writer uses `for ($i = 0; $i < $cellsCount; $i++)` because it relies on numeric indexes.
