### ISSUE TITLE
Cannot read XLSX file

### ISSUE THREAD

**Issue by anevidomy** [box/spout#233]
Hello!
I just want to read XLSX file (in attachment), but got the error:
Notice: Undefined offset: 0 in W:\home\local\test\library\Spout\Reader\XLSX\Helper\SheetHelper.php on line 109 Fatal error: Call to a member function getAttribute() on a non-object in W:\home\local\test\library\Spout\Reader\XLSX\Helper\SheetHelper.php on line 111

Spout version - 2.4.4

[1.xlsx](https://github.com/box/spout/files/285193/1.xlsx)

**Comment by adrilo** [comment]
Hey @anevidomy, do you know how the file was created? I looked at its structure and it differs from the standard...

In the XML file describing the workbook (`workbook.xml`), here is what there is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<x:workbook xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
	<x:sheets>
		<x:sheet name="Sheet1" r:id="rId1" sheetId="1" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/>
	</x:sheets>
</x:workbook>
```

Here is what is should be:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
	<sheets>
		<sheet name="Sheet1" sheetId="1" r:id="rIdSheet1"/> 
	</sheets>
</workbook>
```

The standard does use a `x:` prefix for the namespace.
Now, it seems like Microsoft tool to handle XLSX file does use `x:` (https://msdn.microsoft.com/en-us/library/office/gg278316.aspx). Is that the tool you used to generate the file?

**Comment by anevidomy** [comment]
Thank you for answer!
I got this file from our client for test and really don't know how it was created, but it can be opened in MS Excel 2007 and the next Excel reader - http://excelviewer.softgateon.net

In any case, Spout version 2.4.0 doesn't show error for this file - I sow it's code, there are some checks which don't exist in 2.4.4 (therefore I got Fatal error because these variables are empty):
row 116:        if (count($relationshipNodes) === 1) {
row 123:       if (count($sheetNodes) === 1) {

**Comment by adrilo** [comment]
There is no error but is Spout able to read the values?

**Comment by anevidomy** [comment]
in Spout 2.4.0 - no, it will return empty rows all the time and without end of file (so I added check - if a hundred rows are empty then stop reading file)

**Comment by adrilo** [comment]
@anevidomy, I merged a fix for your issue. Can you give it a try?

**Comment by anevidomy** [comment]
Thank you a lot!
Sure, I can check it today, but where can I take source code of fixed Spout version?

**Comment by anevidomy** [comment]
Tested it - perfect!!!!! Now I can read my file and parse all values.
Thank you a lot!!!
