### ISSUE TITLE
Problem when use openToBrowser

### ISSUE THREAD

**Issue by Bernd2069** [box/spout#241]
Excel 2016 (Office 365) says that the file has a problem and wants to repair the file.
With opentoFile everything works fine. 
![image](https://cloud.githubusercontent.com/assets/19753006/15801978/d6b7ef06-2aa5-11e6-9ea1-c03363465eb1.png)

<?php
require_once(dirname(__FILE__)."/Spout/Autoloader/autoload.php"); 
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Common\Type;
use Box\Spout\Writer\Style\StyleBuilder;
use Box\Spout\Writer\Style\Color;

$writer = WriterFactory::create(Type::XLSX);
$writer->openToBrowser("test.xlsx"); 
$row = array("test1", "test2");
$writer->addRow($row);
$writer->close();
?>

**Comment by mrlopezhouston** [comment]
I am having this same issue. Works fine with opentoFile but would rather stream output.

**Comment by mrlopezhouston** [comment]
In my case the issue was actually any additional spaces outside of the php brackets that was effecting the stream. After spaces were removed it streamed normally without prompting a repair.

**Comment by Bernd2069** [comment]
Yes, also my problem  is solved when I removed some spaces.
Thank you

**Comment by adrilo** [comment]
Glad you figured it out. Spout should still be able to fix this automatically. It's just a matter of adding `ob_end_clean()` when `openToBrowser()` is used. This will remove any characters already outputted that will corrupt the file. I'll push a change for that
