### ISSUE TITLE
Fatal error: Uncaught exception 'Box\Spout\Common\Exception\EncodingConversionException' with message 'The conversion from UTF-16LE to UTF-8 failed.' 

### ISSUE THREAD

**Issue by joyqhs** [box/spout#244]
Fatal error: Uncaught exception 'Box\Spout\Common\Exception\EncodingConversionException' with message 'The conversion from UTF-16LE to UTF-8 failed.'

**Comment by adrilo** [comment]
Well, the error looks explicit. Can you send me the file you are trying to read?

**Comment by adrilo** [comment]
@joyqhs ^^

**Comment by adrilo** [comment]
No response within 2 months, closing this issue
