### ISSUE TITLE
there is no way to disable textWraping through the API

### ISSUE THREAD

**Issue by Gamesh** [box/spout#247]
since enhancement https://github.com/box/spout/pull/83
Spout automatically wraps cells that contains newlines and we want to disable that, but current API does not provide any means for that.

Style builder only has an option to enable wraping but not to disable.
`Style->shouldWrapText` if only set to true by setShouldWrapText method. 

Perhaps you could modify that method and add a parameter that would allow to toggle this option?

**Comment by adrilo** [comment]
As a workaround, can you remove the newlines before passing data to `addRow()`?

**Comment by Gamesh** [comment]
not really, they are needed as excel is used for data export which another application import.

i've found another workaround, extended the Style class and overridden the method shouldWrapText it now returns always false and passed in the newly created style into the addRowWithStyle method. 
```php
class NoWrapStyle extends Style
{
    /**
     * @inheritDoc
     */
    public function shouldWrapText()
    {
        return false;
    }
   /**
     * @inheritDoc
     */
    public function setShouldWrapText()
    {
        return $this;
    }
}
```
but the ability to change it through the api still would be great.

**Comment by Hastegan** [comment]
@Gamesh I had this problem for exports / imports as well. I fixed it by adding the missing methods to the api. I will make a merge request soon (I need to add unit testing tests to be ok).
An other problem with line wrapping occurs with large sheets, Excel just hangs for a few minutes to calculate the wrapping.
