### ISSUE TITLE
Exception' with message 'DateTime::__construct():

### ISSUE THREAD

**Issue by jakgab** [box/spout#249]
On php hosting server occurs an error:

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): 
It is not safe to rely on the system's timezone settings. 
You are *required* to use the date.timezone setting or the d
ate_default_timezone_set() function. In case you used any of those methods 
and you are still getting this warning, you most likely misspelled the timezone identifier.
 We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
 ' in /home/...../Spout/Writer/XLSX/Helper/FileSystemHelper.php:184 
 Stack trace: #0 /home......./Spout/Writer/XLSX/Helper/FileSystemHelper.php(184):
 DateTime->__construct()

**Comment by adrilo** [comment]
Make sure to call `date_default_timezone_set()` (http://php.net/manual/en/function.date-default-timezone-set.php) before calling Spout. You'll need to set the default timezone to whatever makes sense for your program (can be UTC or your actual timezone).

**Comment by jakgab** [comment]
Ok. Thanks.
You are right, this is not the framework's job.
I have corrected it.
2016. jún. 9. du. 7:10 ezt írta ("Adrien Loison" <notifications@github.com
