### ISSUE TITLE
Compatibility with Codeigniter

### ISSUE THREAD

**Issue by wibrahimy** [box/spout#251]
Is this library work with codeigniter? and if it works, how to use it?

Thanks,
Ibrahimy

**Comment by adrilo** [comment]
Hi @wibrahimy,

Spout should work with CodeIgniter, as CodeIgniter supports libraries installed via Composer.
You can look at this link to enable auto-loading for composed libraries: https://www.codeigniter.com/user_guide/general/autoloader.html

You can follow the install guide (in the README of this repo) to install Spout via Composer. Then, you'll be able to use Spout as it's described in the README.

**Comment by alejandro11k** [comment]
with composer works ok but I need to install this without using composer.
isolated in a specific module.
Any detailed help? 
thanks

**Comment by adrilo** [comment]
@alejandro11k You can take a look at this section of the documentation: http://opensource.box.com/spout/getting-started/#manual-installation
