### ISSUE TITLE
Fails to find sheets that are not all lowercase, e.g: Sheet1.xml 

### ISSUE THREAD

**Issue by cmanley** [box/spout#257]
I'm trying to read XLSX files generated by Crystal Reports. Unfortunately, Crystal Reports doesn't use lowercase names for the sheet xml files. Because of this, I get these errors with Spout:
PHP Notice:  Undefined offset: 0 in vendor/box/spout/src/Spout/Reader/XLSX/Helper/SheetHelper.php on line 109
PHP Fatal error:  Call to a member function getAttribute() on null in vendor/box/spout/src/Spout/Reader/XLSX/Helper/SheetHelper.php on line 111

See attachment with a small demo file.

[Sheets.zip](https://github.com/box/spout/files/330390/Sheets.zip)

**Comment by adrilo** [comment]
Hey @cmanley, I tried reading the file you sent and it works fine.
The way sheets are read has been changed recently so I guess you're not using the latest version. Can you please try with the latest version and tell me if that works better?

**Comment by cmanley** [comment]
That fixed it. Thanks!
B.t.w. The version I downloaded was yesterday or today with the composer command in the README.

**Comment by adrilo** [comment]
Yeah, I haven't released a new version with all the recent changes
