### ISSUE TITLE
setEndOfLineCharacter() on CSV writer

### ISSUE THREAD

**Issue by Gavrisimo** [box/spout#258]
Hello,

are there any plans to have `setEndOfLineCharacter()` method in `Box\Spout\Writer\CSV\Writer` class?

The reader `Box\Spout\Reader\CSV\Reader` already has that.

What I am trying to do is something like this:

```
        $this->writer = WriterFactory::create(Type::CSV);

        $this->writer->setFieldEnclosure('');
        $this->writer->setEndOfLineCharacter("\r\n");

        $this->writer->openToFile($data_file_location);
        $this->writer->addRows($data);
        $this->writer->close();
```

Any idea how to do that?

**Comment by madflow** [comment]
Hi, I cannot comment on if there are any plans introduce ```setEndOfLineCharacter()``` in the CSV writer.

The writer uses `fputcsv` and PHP always appends a ```\n``` EOL I suppose. https://github.com/php/php-src/blob/adc95c511495f00cd1a90feff5fff7968e38fc4a/ext/standard/file.c#L1976

So I looks like I would be a hacky way to do that like in http://stackoverflow.com/questions/4080456/fputcsv-and-newline-codes

**Comment by adrilo** [comment]
The answers on the Stackoverflow thread are incorrect. Please do not do that! They are missing a lot of the safety provided by `fputcsv` (quotes escaping for instance). So it will work for the simple cases, but will fail as soon as you start passing more complex values to it.

If `fputcsv` does not allow developers to customize the line ending, I don't think I'll add this to Spout. If you really need it, a workaround would be to add `\r` at the end of the last value of each row. Something like this:

```php
$this->writer = WriterFactory::create(Type::CSV);
$this->writer->openToFile($data_file_location);
foreach ($data as $row) {
    $rowLength = count($row);
    $row[$rowLength-1] = $row[$rowLength-1] . "\r";
    $this->writer->addRow($row);
}
$this->writer->close();
```

Would that help? @Gavrisimo

**Comment by Gavrisimo** [comment]
@adrilo yeah that would help. I'll give it a go and let you know how that works for me.

Btw this is the only thing stoping me to completely remove PHPExcel from our app. :)

Have you seen what they are doing?

https://github.com/PHPOffice/PHPExcel/blob/c4782b660619be139a64d96a545f6a422ca74c20/Classes/PHPExcel/Writer/CSV.php#L312-L351

Is that something you guys can do as well or is that something completely different from how spout is handling things? :)

**Comment by adrilo** [comment]
It's not necessarily different but there are some differences. The most visible one is the way enclosures are handled. `fputcsv` only adds enclosure if needed while the `fwrite` rewrite adds enclosures every time. This can easily be changed though.

Anyways, in general I'd like to stick to built-in implementations. When a new PHP version is released, built-in functions can see their perfs improved, their security holes patched, ... and benefit from the help of a lot of people. So if we rewrite the function ourselves, we lose these benefits and we may introduce some non-obvious bugs.
Now, if the built-in implementation is not good enough, it's still possible to fork (as PHPExcel did). But it's not my preferred approach.

Have you tried my workaround yet?

**Comment by Gavrisimo** [comment]
@adrilo that kinda helped, thanks! The next issue was that I had to remove enclosure characters, but `fputcsv` was complaining about that.

Unfortunately I need to have this `.csv` file in this format, no enclosure with `\r\n` line ending, so I resorted to `fwrite`:

```php
$fp = fopen('file.csv', 'w');

foreach ($data as $row) {
    fwrite($fp, implode(',', $row) . "\r\n");
}

fclose($fp);
```

**Comment by adrilo** [comment]
👍 No enclosure means that this will break whenever a value will contain a ",".
But as long as you are aware of that and it's ok for you, then your solution works.
