### ISSUE TITLE
Is there a way to open the file from URL or an external server?

### ISSUE THREAD

**Issue by vergel-mercado** [box/spout#259]
Fatal error: Uncaught Box\Spout\Common\Exception\IOException: Could not open http://00.00.00.00/thefilename.xlsx for reading! Stream wrapper used is not supported for this type of file. in C:\xampp\htdocs\Spout\Reader\AbstractReader.php:73 Stack trace: #0 C:\xampp\htdocs\Spout\index.php(14): Box\Spout\Reader\AbstractReader->open('http://00.00.00.00...') #1 {main} thrown in C:\xampp\htdocs\Spout\Reader\AbstractReader.php on line 73

The above is the error that I got. Please note that the IP above is not the real IP. Thanks

**Comment by adrilo** [comment]
You may be able to do it with CSV files. But it does not work for other file types. You'll have to download the file locally first.
