### ISSUE TITLE
missing globalFunctionsHelper

### ISSUE THREAD

**Issue by rlukasz** [box/spout#262]
Hi, 
Here is direct call of fgetcsv. Should be by globalFunctionsHelper.
https://github.com/box/spout/blob/master/src/Spout/Reader/CSV/RowIterator.php#L156

**Comment by adrilo** [comment]
Thanks @rlukasz! Want to submit a quick PR?

**Comment by rlukasz** [comment]
Sure @adrilo, how to push it?

**Comment by adrilo** [comment]
https://help.github.com/articles/creating-a-pull-request/

Or because the change is really simple, you can go https://github.com/box/spout/blob/master/src/Spout/Reader/CSV/RowIterator.php, click the edit icon, make the change and submit the pull request. I'll then approve and merge your change

**Comment by rlukasz** [comment]
Pull request created. Thanks for a guidance.

Pozdrawiam,
Łukasz Rajczyk

2016-07-03 23:19 GMT+02:00 Adrien Loison <notifications@github.com>:

**Comment by adrilo** [comment]
Fixed as part of #263
