### ISSUE TITLE
XLSX: error parsing file with missing "r" cell attributes

### ISSUE THREAD

**Issue by krzysztof-sikorski** [box/spout#267]
I have a problem reading an automatically-generated XLSX file. The file was sent from a Microsoft-owned product, so I assume its format does not violate XLSX specification... although I may be wrong :disappointed: 

I can open the file manually in Libre Office, but Spout throws an exception with a "Cannot get column index from an invalid cell index" message. After a bit of digging I found that error is caused by sheet's XML file (`sheet1.xml`) - row and cell elements do not contain "r" attributes, so `CellHelper::getColumnIndexFromCellIndex` method is called with NULL parameter.

The bug is quite easy to reproduce:
- create a simple XLSX spreadsheet (even filling a single cell is enough)
- unpack the XLSX file
- open the `xl/worksheets/sheet1.xml` file in unpacked archive
- delete "r" attribute from at least one `<c>` element
- save changes and repack the XLSX file
- try to read the modified file in Spout

I attach such simple file as an example: [test.xlsx](https://github.com/box/spout/files/356972/test.xlsx)

**Comment by adrilo** [comment]
Hi @krzysztof-sikorski ! Thanks for filing this issue.

I just checked the official specs, and you are right: "r" is an optional param for the `<c>` tag. What's not said is what the behavior should be in case it's missing but I'll assume it should 1,2,3...

If you feel like it, feel free to submit a Pull Request. I'll be happy to guide you through it!
Otherwise, we'll try to tackle it as soon as we can

**Comment by krzysztof-sikorski** [comment]
Libre Office displays cells in order of their appearance inside row element, just as you assumed. I do not have access to MS Office so I cannot check if it behaves the same way.

Unfortunately I cannot help you much with patching. I found the bug at work and there was a business decision to just switch the report format in tool's settings, so the only thing I could do was to drop a bug report here. And I do not have enough free time to tackle the bug off-work.

**Comment by adrilo** [comment]
Sounds good. I'll push a fix soon.
