### ISSUE TITLE
Borders must be in correct order

### ISSUE THREAD

**Issue by dan-sorion** [box/spout#271]
With Excel 2013 (not sure which other versions this affects) the borders must be created in the order Left, Right, Top, Bottom. Any other order causes the style XML to be removed by Excel as invalid and display an error. Could the writer for the XLSX be adjusted to ensure that no matter what order the set calls are made in the BorderBuilder that the correct order is output? Thanks.

**Comment by madflow** [comment]
I can look into it.

**Comment by dan-sorion** [comment]
Took me a while to figure out why Excel kept rejecting the files I was creating but once I figured it out it was easy enough to add the borders in the correct order, just thought it might help other users in the future.

Thank you for working on this project, I'm converting code from PHPExcel as memory usage was ballooning to ridiculous levels (I've had well over 1GB on RAM usage on files that in spout are using up around 100MB) and this is a breath of fresh air :)
