### ISSUE TITLE
Setting default row style

### ISSUE THREAD

**Issue by dan-sorion** [box/spout#272]
Is there a way to override the default row style? I've looked through the code and it appears to be all done via constants and protected functions so I'm guessing not. For example, if I want to use Arial 11 for all cells in an XLSX file, and the existing default is Calibri 12, then using AddRowWithStyle for every row for tens/hundreds of thousands of rows is somewhat inefficient due to all of the setRowStyle / resetRowStyleToDefault calls which are wrapped around each addRow call.

I know I could use AddRowsWithStyle however this would mean having to create an array with all of the row data first, and in the case of hundreds of thousands of rows this could have an impact on PHP memory usage which is what I'm trying to avoid - for example if the original data is coming from a database then reading it out row by row and writing to XLSX will consume a lot less memory than reading all of the data into an array first.

**Comment by adrilo** [comment]
There is no way to do that. However, using a custom style or the default style should have an insignificant impact on the performance. Just make sure to reuse the same style. And there is nothing preventing you from sending data to Spout directly from your DB query.

Try something like this:
```php
$style = (new StyleBuilder())
           ->setFontName('Arial')
           ->setFontSize(11)
           ->build();

$writer = WriterFactory::create(Type::XLSX);
$writer->openToFile($filePath);

$stmt = $dbh->prepare($sql);
$stmt->execute();
while ($row = $stmt->fetch(PDO::FETCH_ASSOC) {
    $writer->addRowWithStyle($row, $style);
}

$writer->close();
```

Makes sense?

**Comment by dan-sorion** [comment]
My point is that when using addRowWithStyle for each row of data there are calls to set the style and then reset it which are repeated for each row. Say I have 1 million rows - that's 2 million unnecessary calls to set the style and then reset it to default. If the default style could be overridden just once that would allow using addRow and avoiding all of those unnecessary calls. And if you think that 1 million rows is an overstatement, I'm already generating files with 100,000 to 200,000 rows for 1 month of data from my database and getting requests from users for 6 months ...

I personally think it would be beneficial to add a method to allow the default style to be changed, maybe as part of the constructor, but I'll try do some comparison runs to look at resource usage and timings both with an without a style to see what the performance benefits might be.

**Comment by adrilo** [comment]
I understand your point. Optimizations are never needed on small datasets but changing one little thing can have a huge impact when dealing with millions of rows (and we - Box - also generate reports with millions of rows so I definitely know it's not an overstatement).

Before making a change that optimize performance, I definitely need some benchmarks to see if it's worth doing it. It'd be great if you could come up with some numbers.

**Comment by dan-sorion** [comment]
I've tried running some benchmarks today and I think it's probably not going to make much difference. On a 350,000 row sheet with 10 columns there was very little difference in the timing between using a style or not, plus it's also quite hard to benchmark accurately when I don't have a test server I have exclusive access to. If I can set up a clean VM to test on then I'll see if I can put together a definitive set of benchmarks, although I'm away for a couple of weeks so won't be able to look at it again till mid August.

**Comment by adrilo** [comment]
Thanks for looking into it. If I have time, I'll try to get some numbers too.

**Comment by adrilo** [comment]
Hi @dan-sorion, I just ran some tests. Here are the results:

2 columns, 350,000 rows:
 - not overriding default style: ~40 seconds
 - overriding default style: ~32 seconds

2 columns, 500,000 rows :
 - not overriding default style: ~54 seconds
 - overriding default style: ~47 seconds

2 columns, 1,000,000 rows :
 - not overriding default style: ~115 seconds
 - overriding default style: ~93 seconds

So overriding the default style yields to a 20% gain. That's not bad! I think it's worth adding the method to the API.

**Comment by adrilo** [comment]
Same tests, for ODS files:

2 columns, 350,000 rows:
 - not overriding default style: ~29 seconds
 - overriding default style: ~24 seconds

2 columns, 500,000 rows :
 - not overriding default style: ~47 seconds
 - overriding default style: ~35 seconds

2 columns, 1,000,000 rows :
 - not overriding default style: ~98 seconds
 - overriding default style: ~82 seconds

**Comment by dan-sorion** [comment]
Just wanted to say thanks for implementing this. I've only just had chance to update and try it out, works great.

**Comment by adrilo** [comment]
No problem :)
