### ISSUE TITLE
CellValueFormatter::formatDateCellValue() doesn't respect $shouldFormatDates

### ISSUE THREAD

**Issue by sandrokeil** [box/spout#279]
There is not check in `\Box\Spout\Reader\XLSX\Helper\CellValueFormatter::formatDateCellValue` if `$shouldFormatDates` is enabled. 

I don't want to convert dates to PHP `DateTime`. How can I disable it?

**Comment by adrilo** [comment]
Hi @sandrokeil, there is a bug in Spout. I missed the `formatDateCellValue` function when I added the `shouldFormatDate` option... Thanks for reporting it! I'll push a fix asap.

To help me make sure Spout behaves correctly, can you please send me a test file containing a date value? My version of Excel does not want to use the "date" type and uses "numeric" type + date formatting...

**Comment by sandrokeil** [comment]
[test.xlsx](https://github.com/box/spout/files/374034/test.xlsx) Works this one?

**Comment by adrilo** [comment]
It is using a "numeric" type combined with date formatting. Therefore, it never goes into the `formatDateCellValue` function...
How did you find this bug by the way? By looking at the code?

**Comment by sandrokeil** [comment]
Yes by debugging and looking at the code. Maybe I can provide more details tomorrow.
