### ISSUE TITLE
Is there a way to get a file pointer from the Writer object?

### ISSUE THREAD

**Issue by djagya** [box/spout#285]
Can we maybe add a simple getter for `filePointer` to the `AbstractWriter`?

It's useful to have an access to the pointer and only way to get it right now - is to inherit needed writers and add the getter in the each class, that is not very convenient.

If you're ok with that, I can send a PR.

**Comment by adrilo** [comment]
Hi @djagya!

I don't think it's a good idea to expose this, as this should be internal to the library. Spout should act as a black box to hide the complexity of creating spreadsheets. Exposing an internal variable is breaking this contract.

Can I ask why you want to get access to the `filePointer`? You may have a good use case

**Comment by djagya** [comment]
Hi,
I need the pointer to see the file size during the process of adding rows (before file is closed).
Now I think that it's better to implement such function directly in the AbstractWriter, if this functionality is/will be used by someone.
Otherwise I'll just inherit base classes.

**Comment by adrilo** [comment]
Unless you're working with CSVs, getting a pointer to the final file won't help: XLSX and ODS files are composed by a bunch of XML files, zipped together in the last step of the creation process. So while you're writing data, only the different XML files get bigger (so there are multiple file pointers involved).

I'm going to close this issue then. If you're using a CSV file, feel free to inherit the base classes. BTW, why do you need the file size? Is it to display some kind of progress bar?

**Comment by djagya** [comment]
Ah ok, didn't know about this nuances, thanks. Sure, the issue can be closed then.

I have few different file size limits based on selected options, but the approx size calculations from e.g. first few hundred rows or from the sizes of columns are not precise enough, so I wanted to monitor the file size during the document creation.

**Comment by adrilo** [comment]
I see. What you can do is create a new folder and use it as a custom temp folder (https://github.com/box/spout#using-custom-temporary-folder). All files will be created in this folder so you can monitor its size over time. Just note that this will give you the combined size of all XML files which is different than the final size of the XLSX/ODS file, as the zipping process reduces it. But it may give you a better estimate.

**Comment by djagya** [comment]
Wow, great, thanks for the idea! Yeah, it should be already good enough 👍
