### ISSUE TITLE
XLSX Reader error when run

### ISSUE THREAD

**Issue by Dwikarya** [box/spout#286]
hello, i get an error when try to read xlsx.
i try the code to read xlsx like in basic example but i get this error 

Warning: XMLReader::open(zip://Test/pegawaibaru.XLSX#xl/sharedStrings.xml): failed to open stream: operation failed in C:\xampp\htdocs\web pln\libs\Spout\Reader\XLSX\Helper\SharedStringsHelper.php on line 86

Warning: XMLReader::open(): Unable to open source data in C:\xampp\htdocs\web pln\libs\Spout\Reader\XLSX\Helper\SharedStringsHelper.php on line 86

Fatal error: Uncaught exception 'Box\Spout\Common\Exception\IOException' with message 'Could not open Test/pegawaibaru.XLSX for reading! (Could not open "xl/sharedStrings.xml".)' in C:\xampp\htdocs\web pln\libs\Spout\Reader\AbstractReader.php:105 Stack trace: #0 C:\xampp\htdocs\web pln\atesting.php(64): Box\Spout\Reader\AbstractReader->open('Test/pegawaibar...') #1 {main} thrown in C:\xampp\htdocs\web pln\libs\Spout\Reader\AbstractReader.php on line 105

i use spout version 2.5.0 and php version 5.6.3
when i replace spout with version 2.4.4 it works, it takes 235 sec to read 7323 rows and 46 col.
what should i do to fix it version 2.5.0?

**Comment by zanurano** [comment]
i have same error when open file type xlsx.
anybody help?

**Comment by adrilo** [comment]
Hey @Dwikarya and @zanurano,
To be able to debug your issue, I will need the file you're trying to read; you can attach it here. Also, can you tell me how the file was created? (software - Excel, OpenOffice, ... - or using another library)

**Comment by zanurano** [comment]
this is my code..

<?php
require_once 'src/Spout/Autoloader/autoload.php';
$filePath = 'JEMBER2.xlsx';

use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;

$callStartTime = microtime(true);
$reader = ReaderFactory::create(Type::XLSX); // for XLSX files

$reader->open($filePath);
$i=0;
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        // do stuff with the row
		$arr = split(";",$row[0]);
		echo $arr[0]." ".$arr[1]." ".$arr[2]." ".$arr[3]." ".$arr[4]."<br />";
		$i++;
    }
}
$reader->close();
$time = number_format($time_elapsed_secs = microtime(true) - $callStartTime,2 ,'.','');
echo "<hr />";
echo "Memory peak: ".memory_get_peak_usage()."<br />";
echo "Memory usage: ".memory_get_usage()."<br />";
echo "Time: ".$time."<br />";
?>

thank for your attention.

**Comment by adrilo** [comment]
Your code looks good. Would you be able to attach `JEMBER2.xlsx` here? I need the actual file to be able to debug. If it contains sensitive data, could you please create a test file for me to reproduce the issue?

**Comment by Dwikarya** [comment]
this is my code and xlsx :
http://bit.ly/CodeAndXlsx

for xlsx i exported from sap

**Comment by zanurano** [comment]
this is my file
https://drive.google.com/open?id=0B3FVIsGgc2HxZzY0dFRoay1QUGs

**Comment by zanurano** [comment]
this is my file exce
[l]([url](http://bit.ly/2aUjG7M))

**Comment by adrilo** [comment]
Your files are working just fine for me. Can you give me more infos:
- Which version of Spout are you using?
- Which version of PHP are you using?

**Comment by Dwikarya** [comment]
i use spout version 2.5.0 and php version 5.6.3

**Comment by zanurano** [comment]
spout 2.5.0and PHP Version 5.6.3

can u help me please.. thx

**Comment by madflow** [comment]
Maybe it helps:

Both users are on Windows. I quickly added an ```appveyor.yml``` in my fork and ran the unit tests in the CI server.

These tests fail: 

```
1) Box\Spout\Reader\Wrapper\XMLReaderTest::testGetRealPathURIForFileInZip with data set #0 ('C:\Users\appveyor\AppData\Local\Temp\1', 'C:\Users\appveyor\AppData\Loc...t.xlsx', 'test.xml', 'zip://C:\Users\appveyor\AppDa...st.xml')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'zip://C:\Users\appveyor\AppData\Local\Temp\1/test.xlsx#test.xml'
+'zip://C:\Users\appveyor\AppData\Local\Temp\1\test.xlsx#test.xml'
C:\projects\spout\tests\Spout\Reader\Wrapper\XMLReaderTest.php:165
2) Box\Spout\Reader\Wrapper\XMLReaderTest::testGetRealPathURIForFileInZip with data set #1 ('C:\Users\appveyor\AppData\Local\Temp\1', '/../../../C:\Users\appveyor\A...t.xlsx', 'test.xml', 'zip://C:\Users\appveyor\AppDa...st.xml')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'zip://C:\Users\appveyor\AppData\Local\Temp\1/test.xlsx#test.xml'
+'zip://#test.xml'
C:\projects\spout\tests\Spout\Reader\Wrapper\XMLReaderTest.php:165
3) Box\Spout\Writer\CSV\WriterTest::testWriteShouldThrowExceptionIfCannotOpenFileForWriting
Failed asserting that exception of type "\Box\Spout\Common\Exception\IOException" is thrown.
4) Box\Spout\Writer\ODS\WriterTest::testAddRowShouldThrowExceptionIfCannotOpenAFileForWriting
Failed asserting that exception of type "\Box\Spout\Common\Exception\IOException" is thrown.
5) Box\Spout\Writer\XLSX\WriterTest::testAddRowShouldThrowExceptionIfCannotOpenAFileForWriting
Failed asserting that exception of type "\Box\Spout\Common\Exception\IOException" is thrown.
FAILURES!
Tests: 434, Assertions: 1044, Failures: 5.
Command exited with code 1
```

**Comment by zanurano** [comment]
So what should we do?

thnx...

**Comment by madflow** [comment]
@zanurano Sorry - this was actually addressed at @adrilo. I just wanted to help to debug. "If" this is a Windows specific artifact than we should fix it in upstream and you do not have to do anything.

**Comment by Gavrisimo** [comment]
I'm getting this error as well:

```
IOException in /var/www/portal/vendor/box/spout/src/Spout/Reader/AbstractReader.php line 105:
Could not open /var/www/portal/storage/app/payroll-upload/000/098/679/Stripped Floyd's - 931061-00868 - 2016-07-15 - 5460.52.xlsx for reading! (XMLReader::open(): Unable to open source data)
```

Here is the stripped file:

[Stripped Floyd's - 931061-00868 - 2016-07-15 - 5460.52.xlsx.zip](https://github.com/box/spout/files/404615/Stripped.Floyd.s.-.931061-00868.-.2016-07-15.-.5460.52.xlsx.zip)

```
➜  portal git:(feature/gh-287-phase-out-phpexcel) ✗ php -v
PHP 7.0.9 (cli) (built: Aug  1 2016 19:45:58) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

System is CentOS 6.8

**Comment by adrilo** [comment]
@Gavrisimo your file loads just fine on my Mac. Just in case, can you try adding this before you call Spout: `libxml_disable_entity_loader(false);`

**Comment by adrilo** [comment]
@madflow Thanks! This is really helpful. Looks like Spout has some problems on Windows. I should probably use AppVeyor too :)

I'll look into the issues more this weekend or next week

**Comment by zanurano** [comment]
so spout can run on my windows?

**Comment by Gavrisimo** [comment]
@adrilo yeah, it loads fine, but it fails to load in spout. Here is how I am loading it:

```php
            libxml_disable_entity_loader(false);

            $reader = ReaderFactory::create($type);
            $reader->open($payrollFile->path);
```

It is still failing with the same message.

**Comment by adrilo** [comment]
@Gavrisimo, can you please open a new issue ticket? Your issue is different than the original one.

**Comment by adrilo** [comment]
@Dwikarya @zanurano, I did not manage to reproduce your issue on Windows 8, XAMPP, PHP 5.6.23 and 7.0.8, Spout 2.5.0... So in order to fix the issue, I'll need you to help me debug it.

@Dwikarya you said it is working with 2.4.4, so I want to find which commit actually broke Spout.

Do you have `git` installed on your machine? If so, could you clone Spout (`git clone git@github.com:box/spout.git`) and `require_once` the autoload file from the cloned version? Then could you tell me the last commit that worked (`git reset --hard HEAD^` to go back to the previous commit).

If you don't have `git` and used `composer` to install Spout, can you use it to install different versions. You can use the commit hashes here: https://github.com/box/spout/commits/master. You can install a specific version of Spout by using `dev-master#251c0bebc1c6379a5620cb9d053bb48d609fa9ab` instead of an actual version (where 251c0bebc1c6379a5620cb9d053bb48d609fa9ab is the commit hash).

If you don't have `git` nor `composer`, let me know, I'll find another way to debug.

Thanks!

**Comment by adrilo** [comment]
Also, @Dwikarya and @zanurano, can you tell me which version of `libxml` you are using? You should be able to find it on the phpinfo page.

**Comment by adrilo** [comment]
[CLEANUP] Closing issue - no response for 2 months

**Comment by tim-bezhashvyly** [comment]
Isn't setting `libxml_disable_entity_loader` to `false` opens the gate for XXE attacks?

**Comment by adrilo** [comment]
Yes it will, but there is a bug with the PHP implementation that causes XMLReader to become unstable when `libxml_disable_entity_loader` is used

**Comment by PawWorks** [comment]
I just started working with Spout and well I had the same issue where it would spit the "(Could not open "xl/sharedStrings.xml".)' " error at me.  and adding the libxml_disable_entity_loader before calling spout was the only way to get it to work.
my server:
Windows Server 2012 R2 Standard Edition
Apache/2.4.12 (Win32)
PHP Version 5.6.5

**Comment by adrilo** [comment]
@PawWorks can you attach the file you were using?

**Comment by dsmith64** [comment]
Okay, from a fresh rookie, I have a solution for Windows 10 users. My configuration: Windows 10 Pro, xampp (xampp-win32-5.6.30-0-VC11.zip), PHP 5.6.30. I was receiving the same error, and discovered that Spout said the file did not exist. I created a folder in the root of the same drive xampp is on, and used
$filePath = "/xlsx/spreadsheet.xlsx";
Also, I tried using an xls spreadsheet, and it fails to open that file. Opened the file in Excel 2007, saved it as an xlsx format, and it works now,
I have since moved the xlsx folder into the /xampp/htdocs/project folder, and used:
$filePath = "/xampp/htdocs/project/xlsx/spreadsheet.xlsx";
succesfully. I know this is late to the party, but maybe it will help someone.
-Dan

**Comment by dsmith64** [comment]
It does work, but I should have tested a few more scenarios. You can use relative paths rather than the absolutes i used in the other post. My xampp folder structure:
/xampp/htdocs/project/index.php
/xampp/htdocs/project/spout
/xampp/htdocs/project/xlsx
Using a similar structure requires $filePath to use "../../../filename.xlsx" to access the file

**Comment by jal-morales** [comment]
**I have the same problem, look at the code.**

<?php 
require_once 'vendor/box/spout/src/Spout/Autoloader/autoload.php';

use  Box \ Spout \ Reader \ ReaderFactory ; 
use  Box \ Spout \ Common \ Type ;


$reader = ReaderFactory::create(Type::XLSX);//lleer un archivo xlsx
$filePath='ejemplo.xlsx';
$reader->open($filePath);

foreach ($reader->getSheetIterator() as $sheet) 
{
    foreach ($sheet->getRowIterator() as $row) 
    {
        // do stuff with the row
        $cells = $row->getCells();
        echo "$cells";
        
    }
}

$reader->close();
 ?>

**here is the error:**
Fatal error: Uncaught Error: Class 'Box\Spout\Reader\ReaderFactory' not found in C:\xampp\htdocs\Libreria_SPOUT\ejemplo1\index.php:9 Stack trace: #0 {main} thrown in C:\xampp\htdocs\Libreria_SPOUT\ejemplo1\index.php on line 9

**Comment by jal-morales** [comment]
<?php 
require_once 'vendor/box/spout/src/Spout/Autoloader/autoload.php';

use  Box \ Spout \ Reader \ ReaderFactory ; 
use  Box \ Spout \ Common \ Type ;


$reader = ReaderFactory::create(Type::XLSX);//lleer un archivo xlsx
$filePath='ejemplo.xlsx';
$reader->open($filePath);

foreach ($reader->getSheetIterator() as $sheet) 
{
    foreach ($sheet->getRowIterator() as $row) 
    {
        // do stuff with the row
        $cells = $row->getCells();
        echo "$cells";
        
    }
}

$reader->close();
 ?>

**Comment by adrilo** [comment]
@jal-morales you probably upgraded Spout to version 3. Some classes have been moved/renamed (`ReaderFactory` that is mentioned in your error is one of them). Please look at https://github.com/box/spout/blob/master/UPGRADE-3.0.md for more info on how to upgrade.

**Comment by dds1985** [comment]
Fatal error: Uncaught Error: Class 'spout\src\spout\Reader\ReaderFactory' not found in C:\xampp\htdocs\uploadExcel.php:35 Stack trace: #0 {main} thrown in C:\xampp\htdocs\uploadExcel.php on line 35

please helf me to solve this error

**Comment by adrilo** [comment]
See comment right above yours! You're using the v3 of Spout but wrote code that is meant for the v2. Please follow the upgrade guide if you upgraded from v2 or take a look at the doc if you started from the v3 directly.

**Comment by dds1985** [comment]
i copied v3 of spout after error occurs like that

**Comment by dds1985** [comment]
ok sir, i got it. thank you

**Comment by syamsulnew** [comment]
> 
> 
> See comment right above yours! You're using the v3 of Spout but wrote code that is meant for the v2. Please follow the upgrade guide if you upgraded from v2 or take a look at the doc if you started from the v3 directly.

Thx sir. You remember me about different version of Spout, it will different rules too.

If you see message : Class 'Box\Spout\Reader\ReaderFactory' not found
then you do use Spout version 3.x indeed. Download and use Spout version 2.x to match the old rules without any changing in your script. It work for me.
