### ISSUE TITLE
IOException in AbstractReader.php line 105

### ISSUE THREAD

**Issue by Gavrisimo** [box/spout#294]
Opening new issue like @adrilo requested. This is a continuation from here:

https://github.com/box/spout/issues/286#issuecomment-237965802

**Comment by Gavrisimo** [comment]
I'm getting this error as well:

```
IOException in /var/www/portal/vendor/box/spout/src/Spout/Reader/AbstractReader.php line 105:
Could not open /var/www/portal/storage/app/payroll-upload/000/098/679/Stripped Floyd's - 931061-00868 - 2016-07-15 - 5460.52.xlsx for reading! (XMLReader::open(): Unable to open source data)
```

Here is the stripped file:

[Stripped Floyd's - 931061-00868 - 2016-07-15 - 5460.52.xlsx.zip](https://github.com/box/spout/files/404615/Stripped.Floyd.s.-.931061-00868.-.2016-07-15.-.5460.52.xlsx.zip)

```
➜  portal git:(feature/gh-287-phase-out-phpexcel) ✗ php -v
PHP 7.0.9 (cli) (built: Aug  1 2016 19:45:58) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

System is CentOS 6.8

**Comment by Gavrisimo** [comment]
@Gavrisimo your file loads just fine on my Mac. Just in case, can you try adding this before you call Spout: `libxml_disable_entity_loader(false);`

----------

@adrilo yeah, it loads fine, but it fails to load in spout. Here is how I am loading it:

```php
            libxml_disable_entity_loader(false);

            $reader = ReaderFactory::create($type);
            $reader->open($payrollFile->path);
```

It is still failing with the same message.

**Comment by Gavrisimo** [comment]
@adrilo any luck figuring out this one? If there is anything I can do to help please let me know!

**Comment by adrilo** [comment]
I still can't repro :( Can you try renaming the file to something like "foo.xlsx". It may be caused by some special characters/spaces in the name

**Comment by Gavrisimo** [comment]
@adrilo seems that did the trick! Uploading a file named `foo.xlsx` or `Stripped Floyds - 931061-00868 - 2016-07-15 - 5460.52.xlsx` seems to be working. :)

The key here seems to be `'` character in the name of a file.

Any idea why that is and how to go about fixing it?

**Comment by Gavrisimo** [comment]
I've updated my script that handles these files to clean out a filename like so:

```php
    /**
     * Cleans up file name from all special characters...
     *
     * @param $string
     *
     * @return mixed
     */
    public function clean($string) {
        // Replaces all spaces with hyphens.
        $string = str_replace(' ', '-', $string);

        // Removes special chars.
        $string = preg_replace('/[^A-Za-z0-9\-\.]/', '', $string);

        // Replaces multiple hyphens with single one.
        return preg_replace('/-+/', '-', $string);
    }
```

@adrilo that said, I'm still not sure why is this happening and where should this be fixed.

**Comment by jappiewent** [comment]
Hello,

I got the same error and my filename is clean. Any thoughts?

Fatal error: Uncaught exception 'Box\Spout\Common\Exception\IOException' with message 'Could not open bestanden/j.xlsx for reading! (Could not open "xl/sharedStrings.xml".)' in C:\server\www\mail-import\src\Spout\Reader\AbstractReader.php on line 105

Jasper

**Comment by adrilo** [comment]
The `'` in the filename works fine for me... I tried with every PHP version (5.4, 5.5, 5.6 and 7.0), and all worked (it's on a Mac). @Gavrisimo can you tell me which version of libxml you're using? This command will do the trick: `php -i | grep '^libxml'`

**Comment by Gavrisimo** [comment]
```
➜  portal git:(develop) ✗ php -i | grep '^libxml'
libxml Version => 2.7.6
libxml
libxml2 Version => 2.7.6
```

**Comment by Gavrisimo** [comment]
I have no idea if I'm looking at the correct thing ( http://xmlsoft.org/news.html ), but seems I have some outdated software:

2.7.6: Oct 6 2009

The system I am working on is centos6, seems that's the version that comes bundled with it, dunno. I'll try to update it...

**Comment by Gavrisimo** [comment]
Well I found this:

http://serverfault.com/questions/266927/install-libxml2-2-7-x-on-centos-5-x/305682#305682

But it seems that the version of glibc I have installed does not satisfy the dependencies of the RPM, so I am gonna continue this at some later point in time, since I'm way over my head with this...

**Comment by adrilo** [comment]
So I just tried with libxml 2.7.6 and it... failed! Removing the apostrophe from the filename fixes it, as you observed already. I don't know if there is much we can do to fix that or if the only solutions are: clean the filename first / upgrade libxml.
I will look around to see if there's something that can be done, at the application level.

**Comment by adrilo** [comment]
@Gavrisimo, I checked the source code of the XMLReader extension (here: https://github.com/php/php-src/blob/PHP-5.3/ext/xmlreader/php_xmlreader.c) as well as the one for the libxml extension (here: https://github.com/php/php-src/commits/1c295d4a9ac78fcc2f77d6695987598bb7abcb83/ext/libxml/libxml.c). No major changes happened to this code that could have led to the bug you got.

A similar error is mentioned however in the libxml library (the libxml extension being a PHP binding for the lib): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=509967.  This means that there are no easy ways to fix this problem with code. It will require a library upgrade or doing some pre-cleanup of filenames, as mentioned earlier.
