### ISSUE TITLE
Spout with PHPExcel to handle images

### ISSUE THREAD

**Issue by JakePerillano** [box/spout#301]
Hi,

Is this possible? I have tried to use both PHPExcel and Spout to generate large excel files as well as generate excel files with image but they are generating different excel. 

I dont know if this is possible to create them in the same file.

Thanks.

**Comment by adrilo** [comment]
Spout does not support images but handles large Excel files well. PHPExcel does support images but crashes as soon as the spreadsheet becomes too big. You'll have to sacrifice something unfortunately. Or you can try adding images support to Spout!
