### ISSUE TITLE
how to set the starting position . Help

### ISSUE THREAD

**Issue by tuananhindex** [box/spout#310]

**Comment by adrilo** [comment]
@tuananhindex your question is rather vague. What are you trying to do exactly? Writing or reading a file? Are you trying to start from row 3, or from cell C5?

**Comment by tuananhindex** [comment]
@adrilo yes . i'm trying to start from row 3 , or from cell 5

**Comment by adrilo** [comment]
@tuananhindex There are no direct way of doing that. But you can still achieve what you want by doing this:

```php
$writer = WriterFactory::create(Type::XLSX);
$writer->openToFile('test.xlsx');
$writer->addRows([
    [''],
    [''],
    ['', '', 'foo', 'bar'],
]);
$writer->close();
```

With this code, the 2 first rows will be empty and on the 3rd row, the 2 first cells will be empty. So it's similar to starting at cell `C3`

**Comment by garygreen** [comment]
@adrilo that is not really similar to telling it to start from the 3rd row - if you are loading in an existing excel file that has headers etc it will overwrite it.

**Comment by adrilo** [comment]
Sure, but if you're loading an existing file, you have to start from row 1 if you want to copy cells over anyway. I understood the question was related to how to do it with a *new* file

**Comment by garygreen** [comment]
Basically what I'm trying to achieve is use an existing file as a template - that already has columns formatted, headers in place, styles etc. But it seems it's not currently possible as the new file completely overrides everything as it's a totally new file. I was hoping `->openToFile()` would keep the existing file similar to PHPOffice [`->load()`](https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/ReadingSpreadsheetFiles/03-Loading-a-Spreadsheet.md) but it seems to operate differently.
If there was a way to format columns by date, number, currency etc then I wouldn't need to do this but that doesn't seem possible currently either.

**Comment by adrilo** [comment]
Indeed it's not possible. Originally, Spout was just supposed to work with text data. Formatting was added later to the writers. Unfortunately, it is not implemented yet in the readers... Since using a template requires reading the template file to write it back to another file, all formatting is lost.
We are currently working on the v3 which should improve that. No ETA though.

**Comment by adrilo** [comment]
Also PHPExcel operates very differently and can afford doing what it does because it does not focus too much about the memory consumed. This leads to OutOfMemory errors for large/complex spreadsheets though. Spout took another approach, but this approach has some drawbacks: it's way more difficult to handle formatting, styles, etc...

**Comment by garygreen** [comment]
Yup, that's how I stumbled across Spout as I was getting out of memory errors with PHPExcel. The code and philosophy behind this package is so much better, but it is missing some basic functionality to replace PHPExcel. You mention that formatting was added to the writers... well if I can set a format for each of my columns that would solve my problem. Is it possible to set a format for a column as a whole? Docs is a bit vague for specifying date formatting etc, it seems you add it as a 'style' ?

**Comment by adrilo** [comment]
You can't specify the formatting of a cell/row/column yet... :(

**Comment by garygreen** [comment]
Oh bugger. Might try and give [this package](https://github.com/ellumilel/php-excel-writer) a go. Interestingly the xml style formatting for excel seems quite straight forward - would you happen to know how the formats for columns are defined? Would you have to set an id for each cell to reference a particular format?

**Comment by adrilo** [comment]
I don't have an answer to your questions. And yes, feel free to give it go, it definitely looks interesting!

**Comment by garygreen** [comment]
Just tested it and it works pretty well, [very easy](https://github.com/ellumilel/php-excel-writer/blob/master/examples/formula.php) to set the column header formats, I hope Spout does something similar in the future.

**Comment by adrilo** [comment]
👍 The API looks a bit unfriendly, but it that works for you :)
