### ISSUE TITLE
Unable to read dates with some XLSX files

### ISSUE THREAD

**Issue by adrilo** [box/spout#312]
The `cellXfs` section defined in `styles.xml` describe some of the transformations that need to be applied to the cells. To determine whether a cell contains a date, it currently needs to have 2 things:
- an attribute called `applyNumberFormat` set to "true"
- an attribute called `numFmtId` reference the date format

However, sometimes the `applyNumberFormat` is missing (but `numFmtId` is there). This causes the date formatting to be ignored...

An example can be found here: [tests.xlsx](https://github.com/box/spout/files/468072/tests.xlsx)

**Comment by adrilo** [comment]
cc @mjanis

**Comment by mjanis** [comment]
+ regex which checks for date characters has to be case insensitive
+ for performance i think result of function isNumFmtIdCustomDateFormat in StyleHelper needs to be cached by numFmtId so it is not tested on every cell with regex in loop. If i'm not wrong, result in one styles.xml for same fmtid always will be the same.[https://github.com/box/spout/blob/master/src/Spout/Reader/XLSX/Helper/StyleHelper.php#L250](https://github.com/box/spout/blob/master/src/Spout/Reader/XLSX/Helper/StyleHelper.php#L250)

**Comment by adrilo** [comment]
@mjanis Out of curiosity, do you know which software was used to generate the "tests.xlsx" file?

**Comment by mjanis** [comment]
@adrilo I do not know. We are getting these files from another company. I just removed column description and deleted ~700k lines in Libreoffice 5 on Ubuntu 16. 
Not @ job now, can send you full original file tomorrow.

**Comment by adrilo** [comment]
It's ok, I don't need the original file.

**Comment by mjanis** [comment]
Just checked core.xml file from original xlsx. Generator: PL/SQL Developer - oracle dev tool (www.allroundautomations.com)

**Comment by adrilo** [comment]
@mjanis just merged the fix :)
