### ISSUE TITLE
how to read file then perform add data now for keep structure old file . Help

### ISSUE THREAD

**Issue by tuananhindex** [box/spout#313]

**Comment by adrilo** [comment]
See https://github.com/box/spout/wiki/Add-data-to-an-existing-spreadsheet

**Comment by tuananhindex** [comment]
but file will be lost formats

**Comment by tuananhindex** [comment]
foreach ($reader->getSheetIterator() as $sheetIndex => $sheet) {
    // Add sheets in the new file, as we read new sheets in the existing one
    if ($sheetIndex !== 1) {
        $writer->addNewSheetAndMakeItCurrent();
    }

    foreach ($sheet->getRowIterator() as $row) {
        // ... and copy each row into the new spreadsheet
        $writer->addRow($row);
    }
}

It auto wrap text . How to lose wrap text . Thank

**Comment by adrilo** [comment]
Check this pull request: https://github.com/box/spout/pull/311
I haven't pushed a new version, so you'll need to use `dev-master`.
