### ISSUE TITLE
Please delete the temporary file

### ISSUE THREAD

**Issue by tacone** [box/spout#315]
Spout does not seem to delete the temporary files used to generate `.xlsx` exports.

This has caused a bit of trouble for us, as we ran out of space.

**Comment by adrilo** [comment]
All temporary files should be deleted once the file is generated. See code here: https://github.com/box/spout/search?utf8=%E2%9C%93&q=deleteFolderRecursively+OR+deleteFile&type=Code

What may happen though is if an error occurs while generating the report, the files are not deleted. And after a while, you'll run out of space... Can you check if you saw some exceptions being thrown in the error logs?

**Comment by tacone** [comment]
I can't, but that may very well be the case. What about trying to catch the exception, deleting the file and re-throwing?

**Comment by adrilo** [comment]
Some errors (like out of memory errors) don't throw an exception. Instead a fatal error occurs. It is possible to act on it, by register an exit_handler but I don't think this should be handled by Spout.
Now regarding actual exceptions, I think you made a great point! Spout can/should take the responsibility of cleaning up all temporary files if the exception leads to stopping the reading/writing.

Feel free to start contributing and submit a pull request for that change!
