### ISSUE TITLE
Can't read 15000 rows file

### ISSUE THREAD

**Issue by Napu** [box/spout#317]
I'm trying to upload something like this file, for privacy reasons i can't send you the exact same file, yet, the library only reads up to 1940 lines out of 14274.
 I'm using this code to go through the file:

$i=0;
$reader = ReaderFactory::create(Type::XLSX);
			
			$reader->open($filedir);
			
			foreach ($reader->getSheetIterator() as $sheet) {
				$sheetname=$sheet->getName();
				if($sheetname ="1.SI FACTURAR"){
					
					foreach ($sheet->getRowIterator() as $row) {
						
						var_dump($i);
						$i++;
					}
				}else{
					continue;
				}
				
				
			}
[Stress Test.xlsx](https://github.com/box/spout/files/493232/Stress.Test.xlsx)

**Comment by madflow** [comment]
Works fine here! All rows read dumped with the example file. Maybe ```max_execution_time``` is to small? What error do you get?

**Comment by adrilo** [comment]
I spotted an error in your code: `if($sheetname ="1.SI FACTURAR")` should have a double/triple equal !!

**Comment by Napu** [comment]
@adrilo i tried, what @madflow said, i thought i already changed that but it wasn't changed, i did it again and now it works.
Sorry for waisting your, time and thank you for helping me.

**Comment by adrilo** [comment]
👍
