### ISSUE TITLE
fopen() Failed to open stream: Permission denied

### ISSUE THREAD

**Issue by novalbayusetiawan** [box/spout#323]
I encountered an error when trying to write specific file

> ErrorException in GlobalFunctionsHelper.php line 25:
> fopen(public/file/c1/format_c1.xlsx): failed to open stream: Permission denied

This is my syntax

```
$writer = WriterFactory::create(Type::XLSX);
    $filePath = "public/file/c1/format_c1.xlsx";
    $writer->openToFile($filePath);
    $singleRow = ['No'=>1,'Nama'=>'Bayummic','Nilai'=>11,'Nim'=>14140101];
    $writer->addRow($singleRow); // add a row at a time
    $writer->close();
```

Thanks

**Comment by adrilo** [comment]
Well, looks like a permission issue. Make sure that your file can be read by php (`chmod +r public/file/c1/format_c1.xlsx`)
