### ISSUE TITLE
Can't open a new sheet or print document

### ISSUE THREAD

**Issue by mottykima** [box/spout#324]
After creating an excel file successfully, I open it and try manually to create a new sheet in it.
I get an error - 'The command cannot be used on multiple selections' 
Also, when trying to print the file, the software crashes.
If creating a copy of the file using 'save as...', these two issues do not present in the new file.
I am using Microsoft Office 2007.
Attached a file as example.
[spout.xlsx](https://github.com/box/spout/files/517490/spout.xlsx)

Thanks

**Comment by adrilo** [comment]
@mottykima Seems like you used a forked version to create your spreadsheet. The problem comes from these lines:

```xml
<sheetViews>
	<sheetView tabSelected="1" workbookViewId="0">
		<pane activePane="bottomLeft" state="frozen" topLeftCell="A2" ySplit="1"/>
		<selection activeCell="A2" pane="bottomLeft" sqref="A2"/>
	</sheetView>
</sheetViews>
```

Removing these lines fixes the problem. I can't help more than that as the code you use is not part of this repo.

**Comment by mottykima** [comment]
I added these lines in order to make a sticky header. (First row stays visible when scrolling down).
Is there any other way to implement such functionally?

**Comment by adrilo** [comment]
I have no idea. What I usually do is create a file using Excel, unzip it and look at the generated XML files to see how they are doing it. It's usually faster than reading the full ECMA spec for XLSX (but you can do that too if you want, here is the link: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-376,%20Fourth%20Edition,%20Part%201%20-%20Fundamentals%20And%20Markup%20Language%20Reference.zip)
