### ISSUE TITLE
`Worksheet::addRow($row)` does not accept associative arrays anymore.

### ISSUE THREAD

**Issue by kewlar** [box/spout#353]
`Worksheet::addRow($row)` now calls `Worksheet::isEmptyRow($dataRow)`) that expects `$row` to be an array with numeric, sequential, zero-based keys.

Issue introduced in v2.7.0 (changing behaviour from v2.6.0, that used to accept associative arrays).

**Comment by adrilo** [comment]
@kewlar thanks for opening this issue. It should be fixed in 2.7.1 (available now)

**Comment by kewlar** [comment]
I've just checked, and it does indeed. Awesome, thanks!
