### ISSUE TITLE
Basic Usage: Reader example with a CSV fails

### ISSUE THREAD

**Issue by gbittmann** [box/spout#356]
I took the basic example and switched to the CSV line, added $filePath to a CSV file and get the following error.

Catchable fatal error: Object of class Box\Spout\Reader\CSV\Sheet could not be converted to string

**Comment by adrilo** [comment]
I would need to see some code to figure out where the error comes from. It looks like you're trying to print a `Sheet` object. For CSV, even though there's only one sheet, you still need 2 `foreach` loops

**Comment by gbittmann** [comment]
Sorry to waste your time, that was exactly the problem. I added $sheets, and $rows as counters, but when I went to echo it I used $sheet instead thus generating the error message.
