### ISSUE TITLE
Send xlsx by email

### ISSUE THREAD

**Issue by slewitan** [box/spout#357]
I couldn't figure out if you currently have a way to send an xlsx by email so I want to make the following suggestion ...
add a flag "$download=true" in order to be able to not set the headers if one wants to capture the output

		public function openToBrowser($outputFileName **,$download=true** )
		{
			$this->outputFilePath = $this->globalFunctionsHelper->basename($outputFileName);

			$this->filePointer = $this->globalFunctionsHelper->fopen('php://output', 'w');
			$this->throwIfFilePointerIsNotAvailable();

			// Clear any previous output (otherwise the generated file will be corrupted)
			// @see https://github.com/box/spout/issues/241
			$this->globalFunctionsHelper->ob_end_clean();

			**if($download)**
			{
				// Set headers
				$this->globalFunctionsHelper->header('Content-Type: ' . static::$headerContentType);
				$this->globalFunctionsHelper->header('Content-Disposition: attachment; filename="' . $this->outputFilePath . '"');
				/*
				 * When forcing the download of a file over SSL,IE8 and lower browsers fail
				 * if the Cache-Control and Pragma headers are not set.
				 *
				 * @see http://support.microsoft.com/KB/323308
				 * @see https://github.com/liuggio/ExcelBundle/issues/45
				 */
				$this->globalFunctionsHelper->header('Cache-Control: max-age=0');
				$this->globalFunctionsHelper->header('Pragma: public');
			}

			$this->openWriter();
			$this->isWriterOpened = true;

			return $this;
		}
it would be used like this:

    $writer->openToBrowser($filename,**false**);
    add content ...
    ob_start();
    $writer->close();
    $message = ob_get_clean();
    code for sending attachment ...

Thanks.

**Comment by adrilo** [comment]
@slewitan I don't think it's a good idea to do it this way. It just adds unnecessary complexity since you can achieve the same thing by using `openToFile()` instead of `openToBrowser()` and use the written file as the attachment.

How does that sound?

**Comment by slewitan** [comment]
@adrilo I was thinking of doing that but I didn't want to deal with paths, temp files and/or clean up. Personally, I  find the way I did it less complicated, I guess everyone has there own styles and this fits into mine.

**Comment by adrilo** [comment]
I agree that your way is less complex for this use case. However, complexity is added to Spout for a really rare use case, so I don't think it's worth implementing the change. Feel free to fork Spout if you want to add your proposed change though.
