### ISSUE TITLE
Unable to read date

### ISSUE THREAD

**Issue by iBars** [box/spout#358]
![image](https://cloud.githubusercontent.com/assets/3519015/20466718/0cf7b73c-af89-11e6-809b-23cdb575adb8.png)

I want to read it at least as String.

Tested in .xlsx

**Comment by adrilo** [comment]
@NDruce do you mind sending me the file you used? I can't really do much without it. If it contains sensitive data, feel free to remove it before attaching it here

**Comment by NDruce** [comment]
[Парсер фильтра.xlsx](https://github.com/box/spout/files/602415/default.xlsx)

**Comment by adrilo** [comment]
The file you sent works ok for me. Here what Spout returned when using `$reader->setShouldFormatDates(true);`:

```
ID - Status - Username - Company link - User link - Date - New Status
1 - F - ø - https://www.yelp.com/biz/caravan-moving-santa-ana-5 - https://www.yelp.com/user_details?userid=vUfasYSuyGXtveB5IrnnFw - 11/8/2016
2 - R - Julia T. - https://www.yelp.com/biz/caravan-moving-santa-ana-5 - https://www.yelp.com/user_details?userid=mL5pEwUB32vKKhj_ToVxjw - 11/9/2016
3 - R - Emmy K. - https://www.yelp.com/biz/brisk-moving-company-pasadena - https://www.yelp.com/user_details?userid=cuIdqDF0m-6lwRBMFeC9GQ - 11/10/2016
5 - F - ø - https://www.yelp.com/biz/calstate-movers-riverside-3 - https://www.yelp.com/user_details?userid=z4Jv90x4_WIjwY98veYx2A - 11/10/2016
...
```

Date as text is not considered as a date, so Spout will just return the cell value with no other processing. Date as date is stored as a number that Spout will process to convert to a DateTime object or to a formatted string if `setShouldFormatDates` was set to true.

The date cells in your spreadsheet are defined with this custom format: `<numFmt formatCode="d/m/yyyy" numFmtId="165"/>`. Hence Spout will convert them to 22/5/2016 for instance.

If the date was returned as `null`, that probably means that an invalid date was passed in which seems strange as I am able to correctly read your file.

It may be a locale issue though. Just in case, can you try changing your regional settings and set your date format to be "MM/DD/YYYY" (the US format) and tell me if that works better?

**Comment by adrilo** [comment]
[CLEANUP] Closing issue as no answer was given in the last 3 months
