### ISSUE TITLE
Allow define additional headers for browser output

### ISSUE THREAD

**Issue by flavio-alves** [box/spout#361]
It wourd be great if we could define additional headers when we output to browser.

In my use case I must define "Access-Control-Allow-Origin" header because I have an api and I am serving data to my frontend that is in a different domain.

**Comment by adrilo** [comment]
Hey @flavio-alves, have you tried setting your header before calling `openToBrowser()`? I think it should work

**Comment by ayerkovich** [comment]
@flavio-alves how can I set headers?

**Comment by adrilo** [comment]
http://php.net/manual/en/function.header.php
