### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by amitRosenberg** [box/spout#367]
Hi all is  there a way to create a hyperlink?

thanks

**Comment by adrilo** [comment]
There is no direct way to create hyperlinks... You can try manually setting a value like this:
`$writer->addRow(['=HYPERLINK("https://github.com/box/spout", "Link to Spout")']);`

Please note that this is considered as a hack (if it even works).

**Comment by Germain-Italic** [comment]
Not working :(
