### ISSUE TITLE
CSV column names

### ISSUE THREAD

**Issue by garak** [box/spout#368]
It would be nice to get an option for CSV Reader about first line.
We know that often the first row of a CSV is a kind of "header" row, containing column names instead of actual data.
With a sensible option, the Reader could be aware of this, and so skipping the first line.
Another option, depending on the previous one, could force the Reader to use that columns as keys of the resulting array.

A small example.

File content:
```
name,email,age,city
Max,max@example.org,42,Rome
Bob,bm@gmail.com,33,London
```
With current behaviour, the Reader will return something like the following:

```php
$results = [
    ['name', 'email', 'age', 'city'],
    ['Max', 'max@example.org', '42', 'Rome'],
    ['Bob', 'bm@gmail.com', '33', 'London'],
];
```

with the proposed implementation, with relevant options enabled, the results would be like:
```php
$results = [
    ['name' => 'Max', 'email' => 'max@example.org', 'age' => '42', 'city' => 'Rome'],
    ['name' => 'Bob', 'email' => 'bm@gmail.com', 'age' => '33', 'city' => 'London'],
];
```

**Comment by adrilo** [comment]
@garak I'd rather have a common implementation across all writers (XLSX and ODS writers simply ignore the keys of associative arrays). Optionally, there could be a `setHeader()` function that would just be a copy of `addRow()` but it does not really help nor simplify the usage (and even makes it more complex).
So I won't move forward with your suggestion. Thanks though!

**Comment by arecaps** [comment]
@adrilo 
I was also hoping for such an option.
I am not sure that you understood this correctly, as the request is for **_reading_** files, not for **_writing_**.
This could be implemented for all readers.

**Comment by adrilo** [comment]
You're right @arecaps about the mix up! Although I still thinks that getting the column names is just a shortcut for reading the first row. As you'll need to call 2 different functions (to get the column names and the data), this is the same complexity as having `if ($rowIndex === 0) { $header = $row; } else { ... }`
It also creates a differentiation between files with and without headers in Spout, that is not really necessary to be able to process a file.

**Comment by diimpp** [comment]
This feature is really a must have and puts me in situation, where I need to use different library for reading csv.

Besides using header row as naming for each row keys, I would like not to see header row in rows variable.

**Comment by zenclive** [comment]
Bump on this one. Im considering moving from PhpSpreadsheet because, frankly, it's slow af.

For its faults though, PhpSpreadsheet has functions for working with column headings included 'getHighestColumn' and 'getCellByColumnAndRow' which make things easier.

I like the look of Spout but just feel like we could make it better and encourage adoption from frustrated PhpSpreadsheet users ;)

**Comment by adrilo** [comment]
@zenclive PhpSpreadsheet works very differently compared to Spout. It loads the whole spreadsheet in memory and then all the processing is done in memory. The main drawback is that it's slow and subject to out of memory errors when the file is big. But the advantage is that you have complete knowledge about the spreadsheet being processed: you have direct access to all cells, know how many columns there are for each row, etc. This is why PhpSpreadsheet is able to expose methods such as `getHighestColumn` or `getCellByColumnAndRow`.

On the other hand, Spout is using streaming, which means it processes files line by line. So when at line 20, it does not know about the lines >= 21. The last line could be the longest for instance so we can't expose a `getHighestColumn`. A `getCellByColumnAndRow` could be implemented but would require parsing the whole file from the beginning on every call. Not very efficient...

**Comment by jaspal747** [comment]
I have a written a simple helper class for this.

    <?php 

    /**
     * Simple helper class for Spout - to return rows indexed by the header in the sheet
     * Author: Jaspal Singh - https://github.com/jaspal747
     */

    class SpoutHelper {


    private $rawHeadersArray = []; //Local array to hold the Raw Headers for performance
    private $formattedHeadersArray = []; //Local array to hold the Formatted Headers for performance
    private $headerRowNumber = 1; //Row number where the header col is located in the file


    /**
     * Initialize on a per sheet basis
     */
    public function __construct($sheet) {

        $this->flushHeaders();
        $this->getFormattedHeaders($sheet);//Since this also calls the getRawHeaders, we will have both the arrays set at once
        return $this;
    }

    /**
     * Allow users to mention which row number contains the headers
     */
    public function setHeaderRowNumber($rowNumber = 1) {
        $this->headerRowNumber = $rowNumber;
    }

    /**
     * 
     * Set the rawHeadersArray by getting the raw headers from the headerRowNumber or the 1st row 
     *  Once done, set them to a local variable for being reused later
     *
     */
    public function getRawHeaders($sheet) {


        if (empty($this->rawHeadersArray)) {

            /**
             * first get column headers
             */
            foreach ($sheet->getRowIterator() as $key => $row) {

                if ($key == $this->headerRowNumber) {
                    /**
                     * iterate once to get the column headers
                     */
                    $this->rawHeadersArray = $row->toArray();
                    break;
                }
            }
        
            
        } else {
            /**
             * From local cache
             */
        }

        
        return $this->rawHeadersArray;
    }


    /**
     * 
     * Set the formattedHeadersArray by getting the raw headers and the parsing them
     *  Once done, set them to a local variable for being reused later
     *
     */
    public function getFormattedHeaders($sheet) {

        if (empty($this->formattedHeadersArray)) {

            $this->formattedHeadersArray = $this->getRawHeaders($sheet);

            /**
             * Now format them
             */
            foreach ($this->formattedHeadersArray as $key => $value) {

                if (is_a($value, 'DateTime')) { //Somehow instanceOf does not work well with DateTime, hence using is_a -- ?

                    $this->formattedHeadersArray[$key] = $value->format('Y-m-d');//Since the dates in headers are avilable as DateTime Objects
                } else {
                    
                    
                    $this->formattedHeadersArray[$key] = strtolower(str_replace(' ' , '_', trim($value)));
                }
                /**
                 * Add more rules here as needed
                 */
            }
        } else {
            /**
             * Return from local cache
             */
        }

        return $this->formattedHeadersArray;
    }


    /**
     * Return row with Raw Headers
     */
    public function rowWithRawHeaders($rowArray) {

        return $this->returnRowWithHeaderAsKeys($this->rawHeadersArray, $rowArray);
    }


    /**
     * Return row with Formatted Headers
     */
    public function rowWithFormattedHeaders($rowArray) {

        return $this->returnRowWithHeaderAsKeys($this->formattedHeadersArray, $rowArray);
    }


    /**
     * Set the headers to keys and row as values
     */
    private function returnRowWithHeaderAsKeys($headers, $rowArray) {

        return array_combine($headers, $rowArray);
    }

    /**
     * Flush local caches before each sheet
     */
    public function flushHeaders() {

        $this->formattedHeadersArray = [];
        $this->rawHeadersArray = [];

        return true;
    }
    
    }

And then in your main file you can do:

    
    $reader = ReaderEntityFactory::createReaderFromFile($filePath);
    $reader->open($filePath);

            /**
             * Now get the data
             */
            foreach ($reader->getSheetIterator() as $sheet) {

                $spoutHelper = new SpoutHelper($sheet);               
                $spoutHelper->setHeaderRowNumber(1); //Optional - defaults to 1      

                    foreach ($sheet->getRowIterator() as $key => $row) {

                        if ($key == 1) {
                            //echo "Skipping Headers row";
                            continue;
                        }

                        //Get the indexed array with col name as key and col val as value`
                        $rowWithHeaderKeys = $spoutHelper->rowWithFormattedHeaders($row->toArray());                   
                  }
             }
