### ISSUE TITLE
Check whether file is empty or not, also return 1st row only

### ISSUE THREAD

**Issue by MansionSelect** [box/spout#369]
How to find whether the uploaded file is empty or not? Also want to return only 1st row ie, the excel file headers row. How can I do these using Spout ?

    $reader = ReaderFactory::create(Type::XLSX); // for XLSX files
    $reader->open($xlsFilePath);
    foreach ($reader->getSheetIterator() as $sheet) {
        foreach ($sheet->getRowIterator() as $rowIndex => $row) {

       }
    }

**Comment by adrilo** [comment]
When you upload a file, you can check its size via the `$_FILES` variable (http://php.net/manual/en/features.file-upload.post-method.php).

If you only want to get the header, you can do it this way:

```
$reader = ReaderFactory::create(Type::XLSX);
$reader->open($xlsFilePath);

$header = [];
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        $header = $row;
        break;
   }
   break;
}
// $header only contains the first row
```
