### ISSUE TITLE
Get sheet by name

### ISSUE THREAD

**Issue by LubosRemplik** [box/spout#375]
Is it possible to get sheet by name OR do I need to use code like below to get sheet I want?

```
foreach ($reader->getSheetIterator() as $sheet) {
    if ($sheet->getName() == 'Sheet 1') {
        // work with sheet I want
    }
}
```

**Comment by madflow** [comment]
You second guess is correct - you will have to iterate over the sheets and break on the sheet you want.

https://github.com/box/spout/wiki/Read-data-from-a-specific-sheet-only
