### ISSUE TITLE
Incorrect handling of writing numbers in xlsx

### ISSUE THREAD

**Issue by chrisgraham** [box/spout#377]
Hi,

I see the latest spout code is still using PHP's is_numeric to decide whether to do an inline cell. In my fork a while ago I fixed this, but incorrectly.

PHP's is_numeric does not align with the requirements the xlsx format has on numeric fields.
E.g. this passes is_numeric:
`' 12.3e6'`

In my fork I tried to fix this by seeing if the string consists only of number characters (the decimals, -, and .). However this string would fail that:
`'3.2.4'`

So you really need to use a full regex:
```
if (preg_match('#^\-?\d+(\.\d+)?$#', $cellValue) != 0/*similar to is_numeric without having PHPs regular quirkiness*/) {
```

**Comment by adrilo** [comment]
Hi @chrisgraham! I think this is a trickier problem as the way numbers are formatted depends on the user locale. `1,000.45` or `1.000,45` are both valid numbers and I don't think your regex allows that.

**Comment by chrisgraham** [comment]
Hi,

Would that be valid in an xlsx though? I imagine the format specifies the English convention, so it's a separate issue anyway.

That said, this is the code our CMS uses to convert locale'd string representations of floats back to PHP floats...

```
/**
 * Take the given formatted float number and convert it to a native float. The inverse of float_format.
 *
 * @param  string $str The formatted float number using the locale.
 * @param  boolean $no_thousands_sep Whether we do *not* expect a thousands separator, which means we can be a bit smarter.
 * @return float Native float
 */
function float_unformat($str, $no_thousands_sep = false)
{
    $locale = localeconv();

    // Simplest case?
    if (preg_match('#^\d+$#', $str) != 0) { // E.g. "123"
        return floatval($str);
    }

    if ($no_thousands_sep) {
        // We can assume a "." is a decimal point then?
        if (preg_match('#^\d+\.\d+$#', $str) != 0) { // E.g. "123.456"
            return floatval($str);
        }
    }

    // Looks like English-format? It couldn't be anything else because thousands_sep always comes before decimal_point
    if (preg_match('#^[\d,]+\.\d+$#', $str) != 0) { // E.g. "123,456.789"
        return floatval($str);
    }

    // Now it must e E.g. "123.456,789" or "123.456", or something from another language which uses other separators...

    if ($locale['thousands_sep'] != '') {
        $str = str_replace($locale['thousands_sep'], '', $str);
    }
    $str = str_replace($locale['decimal_point'], '.', $str);
    return floatval($str);
}
```

**Comment by adrilo** [comment]
@chrisgraham I don't see any occurrence of `is_numeric` in the codebase. Can you tell me which file you were referring to?

**Comment by chrisgraham** [comment]
I'm sorry, it looks like I got very confused keeping track of changes. I don't know how I concluded you were using `is_numeric` either, you have your own isNumeric method but that is using `gettype`.
I'm, closing the issue.
