### ISSUE TITLE
XLSX reading error "Could not open ....xlsx for reading! "

### ISSUE THREAD

**Issue by ahmetkemall** [box/spout#379]
Hello,
Sometimes I'm getting this error while trying to open a xlsx ReaderFactory
_"Could not open /www/....E8F2A635F.xlsx for reading! (Could not open "xl/sharedStrings.xml".)"_

And then trying again it works fine, and again getting this error again.
How can i prevent this error ?

Thank you.

`            $reader = ReaderFactory::create(Type::XLSX);
            $reader->open($file['path']);

            $indexCount = 0;
            foreach ($reader->getSheetIterator() as $sheet) {
                if($workSheetIndex != $indexCount++)
                    continue;

                foreach ($sheet->getRowIterator() as $row) {
                    $columns = $row;
                    break;
                }
            }

            $reader->close();`

**Comment by madflow** [comment]
Can you provide a file (with fake data) where this error occurs?

**Comment by ahmetkemall** [comment]
Sure,
[1486025509.552D087289828409BB19CB2E8F2A635F.xlsx](https://github.com/box/spout/files/747369/1486025509.552D087289828409BB19CB2E8F2A635F.xlsx)

**Comment by madflow** [comment]
I can load the file without any errors. There already is similar Issues here: 

https://github.com/box/spout/issues/286

and here:

https://github.com/box/spout/issues/294

I am not quite sure which one applies - but they seem similar.

From a quick glance: Can you try setting ```libxml_disable_entity_loader(false);``` before reading the file and/or renaming it first to "foo.xlsx" in order to rule out filename problems.

**Comment by ahmetkemall** [comment]
Rarely this error showing up, the interesting thing when i try for same file again its loading with out errors.

I double checked this issue  now #286 it's similar

Have tried `libxml_disable_entity_loader` no problem until now, if i get similar problem again i will let you know

Thank you so much !

**Comment by madflow** [comment]
👍 Please kindly close this issue if it is resolved.

**Comment by ahmetkemall** [comment]
After so many tests.
Problem has solved,

Thank you..

**Comment by yujin1st** [comment]
Hello, i have the same issue with one file and using  libxml_disable_entity_loader doesn't solve issue.
previously i had this issue on 2.7 version https://github.com/box/spout/issues/441 and after updating to  v3.1.0  i got this error. 

php v7.3.11. File attached. Google can't properly open file, but office 365 does fine.
It's automatically created price list of one our supplier, so we can't do nothing with it. 

[eh02CQJ89ALtOrEfGjvD3PBHp.xlsx]
(https://github.com/box/spout/files/4254759/eh02CQJ89ALtOrEfGjvD3PBHp.xlsx)
![image](https://user-images.githubusercontent.com/2317913/75333612-c8dfc380-58c9-11ea-9650-2e5f94d5ba0f.png)
![image](https://user-images.githubusercontent.com/2317913/75333624-cd0be100-58c9-11ea-8d51-f56c052f8bf6.png)
