### ISSUE TITLE
Begin reading from specific row

### ISSUE THREAD

**Issue by BlitZ-UK** [box/spout#380]
Is there any way to begin reading from a specific line/row in a CSV file other than from the start (0) position? I understand there is a possibility that this is not feasible as the way it reads the files, has anyone had a workaround or solution for this?

Thanks

**Comment by adrilo** [comment]
Hi @BlitZ-UK,

All readers work - afaik - need to read the entire file to locate line endings and therefore where row X is. So when you say, start row 4, your reader will read from the 3 first rows to find the beginning of line 4.

This is basically what you can do here:

```
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $rowNumber => $row) {
        if ($rowNumber < 3) { // start with line 4
          ...
        }
    }
}
```

**Comment by BlitZ-UK** [comment]
Hi,

Thanks for that, although i was trying to avoid reading the entire file from the start (0) position (see first post). Nevermind, thanks anyway.

**Comment by javierrojas10** [comment]
For future people looking around on this, i think it will be better to put a if statement at first part for more order:
` if ($sheet->getIndex() == 1) {// This is to start en second sheet, getIndex is Zero-Based
                foreach ($sheet->getRowIterator() as $rowNumber => $row) {

                    //If row is 0, 1, 2 and 3 it will continue
                    if($rowNumber < 3){// or  $rowNumber == 0 to skip headers
                        continue;
                    }//Begins on 4
//Begin row data extract and functions`

**Comment by fyaconiello** [comment]
in extremely large files iterating over each row becomes inefficient. Is there any potential for seek like behavior: https://www.php.net/manual/en/splfileobject.seek.php

this would allow reading from large files to happen in batches B1:1-500, B2:501-1000, ..., BN:XX01-XXXX

**Comment by adrilo** [comment]
It is very tricky because XLSX are a bunch of XML files, so you don't know in advance where to move your file pointer to start reading data for a specific row/cell...
