### ISSUE TITLE
InvalidSheetNameException: The sheet ("blabla") is invalid. It did not respect these rules: - It should be unique ...

### ISSUE THREAD

**Issue by jgeert1** [box/spout#391]
I was using this class to open and process a number of excel files in a loop and got the message :

ox\Spout\Writer\Exception\InvalidSheetNameException: The sheet&#039;s name ("blabla") is invalid. It did not respect these rules:
 - It should be unique in Box\Spout\Writer\Common\Sheet->throwIfNameIsInvalid() (line 128 of D:\wamp\www\sites\all\libraries\spout-master\src\Spout\Writer\Common\Sheet.php).

By debugging the code I noticed that somehow the class was referring to sheetnames that were used in a previous processing (even though I cleared everything before reusing the class again).

I found that the file "spout-master\src\Spout\Writer\Common\Sheet.php" did not initialize the static variable "$SHEETS_NAME_USED" and as result the names in there show up again when you reuse the class.

So I changed (added the line in bold) the following function (in the same file) to resolve the issue:

```
public function __construct($sheetIndex)
    {
        **self::$SHEETS_NAME_USED = array();**
		$this->index = $sheetIndex;
        $this->stringHelper = new StringHelper();
        $this->setName(self::DEFAULT_SHEET_NAME_PREFIX . ($sheetIndex + 1));
		
    }
```

Kind regards,

Jos.

**Comment by adrilo** [comment]
Thanks @jgeert1! Can you make a pull request out of this? I'd be happy to merge it :)
