### ISSUE TITLE
Xlsx writer closes file even if already closed.

### ISSUE THREAD

**Issue by Zorato** [box/spout#392]
Hi,

Encountered an issue when trying to call close() method twice:
> [Box\Spout\Common\Exception\IOException]                       
>   Cannot perform I/O operation outside of the base folder: /tmp

It seems that writer checks for book to be present, even if isWriterOpened flag is false:
```
/**
     * Closes the writer, preventing any additional writing.
     *
     * @return void
     */
    protected function closeWriter()
    {
        if ($this->book) {
            $this->book->close($this->filePointer);
        }
    }
```

I don't have time to prepare PR now, so I suggest adding  `&& $this->isWriterOpened` condition in 
[src/Spout/Writer/XLSX/Writer.php:128](https://github.com/box/spout/blob/master/src/Spout/Writer/XLSX/Writer.php#L128).

Thanks in advance!
P.S. Let me know if you need a PR for this, I'll do my best to create one in a few days.
P.P.S. I tried to implement some cleanup / rollback functionality. I suppose creating a public method with `closeAndAttemptToCleanupAllFiles()` code inside would be nice ;)

**Comment by adrilo** [comment]
Hey @Zorato, thanks for filing this issue! I won't be able to look into it before a few days but I will as soon as I can. Thanks for your patience!
