### ISSUE TITLE
reading cell value incorrectly

### ISSUE THREAD

**Issue by mathsgod** [box/spout#400]
I have a excel file (https://github.com/box/spout/files/875118/space.problem.xlsx). when I using Reader to get the text value of cell, it added an space in the result

I extract my excel file, I found that my value are stored in sharedStrings.xml

`       <si>
		<r>
			<t>t</t>
		</r><r>
			<rPr>
				<sz val="12"/>
				<color rgb="FF000000"/>
				<rFont val="Calibri"/>
				<family val="2"/>
			</rPr><t>est</t>
		</r>
		<phoneticPr fontId="1" type="noConversion"/>
	</si>`

I alse found the Reader/XLSX/Helper/SharedStringsHelper.php line 239 $textValue .= ' ';
I wondering why add a space between each "t" node

**Comment by adrilo** [comment]
Hi @mathsgod, I took a look at this issue and I can confirm that you found the root cause.
The space was added to fix another issue, but this is wrong. I'm going to add a proper fix.
