### ISSUE TITLE
Bulk Read

### ISSUE THREAD

**Issue by nalsakas** [box/spout#404]
Right now I have to read line by line. Is there a way to read a bulk (ex: 100 lines) at a time? It would be great  and I think it would be more faster than reading line by line.

**Comment by adrilo** [comment]
Hi @nalsakas! There is no advantages reading many rows at a time. A spreadsheet is described in an XML file, row by row. Therefore if you want to read 100 lines, you still need to read it line by line until you reach row 100 so no perf gains.
Reading in bulk may also cause memory problem as you need to cache the results of the previous rows (imagine reading 10,000 rows in bulk, the data may not fit in your memory). This is why Spout takes a streaming approach.

Now, there is nothing preventing you creating a wrapper around the Spout API to implement this bulk functionality but I would highly suggest you not to, for the reasons I just mentioned.

**Comment by nalsakas** [comment]
Hello Adrilo,
Right now I am reading one line out of 65000 lines of excel and put it that line inside MySQL database. I am planning to gain speed on mysql  side if only I could bulk insert to database. This is what I want to try. Bulk size can be user defined. That way I don't think that it is going to be a memory problem.

**Comment by adrilo** [comment]
This optimization can be done in your code. You don't need to insert data after every row you read. Just add a if statement to make your insert. Something like this:

```
$bulkReadLimit = 100;
foreach ($reader->getSheetIterator() as $sheet) {
    $cache = [];
    foreach ($sheet->getRowIterator() as $rowIndex => $row) {
        $cache[] = $row;
        if ($rowIndex % $bulkReadLimit === 0) {
           // insert $cache in DB
           $cache = [];
        }
    }
}
```

**Comment by nalsakas** [comment]
Hmm, understood Adrien. Thanks for the tip.

**Comment by p1xel007** [comment]
@adrilo 

This code is working but the problem is it doesn't insert if the sheet has less rows than bulk read limit. Any help?

**Comment by adrilo** [comment]
Indeed, I wrote too fast and it should rather be:
```
$bulkReadLimit = 100;
foreach ($reader->getSheetIterator() as $sheet) {
    $cache = [];
    foreach ($sheet->getRowIterator() as $rowIndex => $row) {
        $cache[] = $row;
        if ($rowIndex % $bulkReadLimit === 0) {
           // insert $cache in DB
           $cache = [];
        }
    }
    // insert $cache in DB if not empty      <= This was missing
}
```
