### ISSUE TITLE
Unregister autoloader

### ISSUE THREAD

**Issue by moh3n9595** [box/spout#408]
Hi, I use a cms that this use autoloader. Now I want after using spout functions unregister this autoloader . anybody can help me? 

                        require('./model/libs/spout-2.7.2/src/Spout/Autoloader/autoload.php'); 
			$reader = ReaderFactory::create(Type::XLSX);
			$reader->open($file_path); 
                        //Some stuff..
                        $reader->close();
                        // Unregister my require! (autoloader)

**Comment by adrilo** [comment]
Hi @moh3n9595, it's not possible to unload already loaded classes. Why do you want to unload these classes though?

**Comment by moh3n9595** [comment]
Because I want use my autoloader in my cms that worked with psr0! So I need to some change in your code but I don't know what I do

**Comment by adrilo** [comment]
Well, you should be able to use multiple autoloaders at the same time.

Also, you can try unregistering all autoload functions:
```
foreach(spl_autoload_functions() as $function) {
    spl_autoload_unregister($function);
}
```

But this may have some unexpected consequences...

**Comment by moh3n9595** [comment]
Yeap! this work tnQ very much. And :

> But this may have some unexpected consequences...

it's a terrible sentence..

**Comment by adrilo** [comment]
Ahaha I know but that's the truth, as the code I wrote will unregister ALL autoload functions, not just the Spout one. You just need to be aware of that.
