### ISSUE TITLE
Can only read few columns

### ISSUE THREAD

**Issue by cevarief** [box/spout#41]
I try to read a large excel files (more than 30 columns with column range formulas) and 11 thousands rows. This library can only read 6 columns.

Any clue why ?

**Comment by adrilo** [comment]
What do you call "column range formulas"? Can you give an example?
Unfortunately, Spout does not support formulas... So I guess when it encounters a formula, it does not know how to process it and fails.

**Comment by cevarief** [comment]
Hi, thanks for quick answer.

Range formula like this =A:A-B:B
Rather than fail, what if i want it to just show its formula ? Which part should i modify.

**Comment by cevarief** [comment]
I tried without formula (copy and paste special as value to a new sheet), and the library can't read whole columns.

**Comment by adrilo** [comment]
I tried reading a XLSX file containing 100 columns and a 100 rows (10,000 cells then). It worked perfectly. And even with more rows (like you have), it should not make any difference - it will just be longer to process.

I suspect that even after copy/pasting values, it still exists data that Spout can't process.
You can look at the read() function in the XLSX reader: https://github.com/box/spout/blob/52faef01681e1aadba74f66518e77daf58c7d840/src/Spout/Reader/XLSX.php#L183. That's where I would add the logic to "support" formulas.
