### ISSUE TITLE
Unable to use in windows

### ISSUE THREAD

**Issue by Elvisonyedika** [box/spout#410]
I keep getting the following error trying to user reader.

( ! ) Warning: XMLReader::open(zip://phpExcelProject.xlsx#xl/worksheets/sheet1.xml): failed to open stream: operation failed in C:\wamp64\www\phpexcel\spout\src\Spout\Reader\XLSX\RowIterator.php on line 132
Call Stack
#	Time	Memory	Function	Location
1	0.0010	239800	{main}( )	...\index.php:0
2	0.0480	895888	Box\Spout\Reader\XLSX\RowIterator->rewind( )	...\index.php:14
3	0.0480	896056	open ( )	...\RowIterator.php:132

( ! ) Warning: XMLReader::open(): Unable to open source data in C:\wamp64\www\phpexcel\spout\src\Spout\Reader\XLSX\RowIterator.php on line 132
Call Stack
#	Time	Memory	Function	Location
1	0.0010	239800	{main}( )	...\index.php:0
2	0.0480	895888	Box\Spout\Reader\XLSX\RowIterator->rewind( )	...\index.php:14
3	0.0480	896056	open ( )	...\RowIterator.php:132

( ! ) Fatal error: Uncaught exception 'Box\Spout\Common\Exception\IOException' with message 'Could not open "xl/worksheets/sheet1.xml".' in C:\wamp64\www\phpexcel\spout\src\Spout\Reader\XLSX\RowIterator.php on line 133
( ! ) Box\Spout\Common\Exception\IOException: Could not open "xl/worksheets/sheet1.xml". in C:\wamp64\www\phpexcel\spout\src\Spout\Reader\XLSX\RowIterator.php on line 133
Call Stack
#	Time	Memory	Function	Location
1	0.0010	239800	{main}( )	...\index.php:0
2	0.0480	895888	Box\Spout\Reader\XLSX\RowIterator->rewind( )	...\index.php:14

Please kindly assist me.

**Comment by adrilo** [comment]
@Elvisonyedika Can you please attach the file that you're trying to read? There's probably something weird with it.

**Comment by Elvisonyedika** [comment]
Hi Loison,

Thanks for your response. please find attach a copy of the file I'm trying
to read.

**Comment by adrilo** [comment]
@Elvisonyedika Github does not support attaching files when you reply by email. You will need to reply through the Github website directly to attach your spreadsheet.

**Comment by Elvisonyedika** [comment]
[phpExcelProject.xlsx](https://github.com/box/spout/files/963977/phpExcelProject.xlsx)
find attached file here

**Comment by Elvisonyedika** [comment]
@adrilo please find attached the file here
[phpExcelProject.xlsx](https://github.com/box/spout/files/963981/phpExcelProject.xlsx)

**Comment by Elvisonyedika** [comment]
@adrilo any progress?

i will be grateful if you can assist

**Comment by adrilo** [comment]
I am able to read your file successfully (on a Mac though). But that means that your file is not corrupted.
Now, can you try giving Spout a full path instead of just "phpExcelProject.xlsx"? Something like `C:/.../.../phpExcelProject.xlsx`?

**Comment by Elvisonyedika** [comment]
Thanks so much @adrilo . Providing a full part solved the problem

**Comment by adrilo** [comment]
Glad it worked!
