### ISSUE TITLE
Uncaught exception 'Box\Spout\Common\Exception\IOException' with message 'Could not open

### ISSUE THREAD

**Issue by zegre** [box/spout#414]
i'm trying to read an excel and thrown this error, my code is:

controller:

require_once 'library/vendors/src/Spout/Autoloader/autoload.php';
use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;

public function readExcel(){
        $path = 'temp/excel.xlsx';
	$reader = ReaderFactory::create(Type::XLSX);
	$reader->open($path);
}

the structure of my project is:

controllers/controller.php
views/
temp/excel
library/vendors/src/Spout/

i'm testing with a other old library and this read fine, but how i need to read an excel with 150k of lines i'm testing this but i cant read this and has the permission 777.

**Comment by adrilo** [comment]
@zegre What's the entire error message?

**Comment by zegre** [comment]
Uncaught exception 'Box\Spout\Common\Exception\IOException' with message 'Could not open temp/excej.xlsx for reading! (Could not open temp/excel.xlsx for reading.)'

**Comment by adrilo** [comment]
This error can indicates 2 things:
- the file you're trying to read does not exist (`temp/excel.xlsx` does not exist)
- you don't have the permissions to read the file (in which case, make sure you set the proper permissions)

Can you verify both points?

**Comment by zegre** [comment]
the permissions are 0777 and the file exists in that path. with another old library I could read the file.

**Comment by adrilo** [comment]
Ok. Can you try using a full absolute path instead of "temp/excel.xlsx"?

**Comment by zegre** [comment]
i find the problem,  its problem of my framework and redirections, with de absolute path its works thanks you mate.
