### ISSUE TITLE
how to defind column data type ?

### ISSUE THREAD

**Issue by rhodesiaxlo** [box/spout#417]
saying  i was using spout to export our user data into csv files, the user id card number, which should be string formate like 422201198808046452, always display as float like 4.2+E16, i think this is a column data type issue, but i can figure out how to set the column data type, help me, pls :( , thx in advance.

**Comment by adrilo** [comment]
Hi @rhodesiaxlo,

You can try to cast the value to string before passing it to Spout:
```php
$cardNumber = 422201198808046452;
...
$writer->addRow([(string)$cardNumber, ...]);
```

Alternatively, you can use `$cardNumber + ''` to cast to string.
