### ISSUE TITLE
use a xlsx template file

### ISSUE THREAD

**Issue by Hightem** [box/spout#420]
Hello,

I would like to use the readerFactory to read a template file and then modify it to add a custom data in specific rows positions every time.

can I do that using Spout ?

Is it also to get the style of a file that I read with the readerFactory ?

Thanks in advance for your help

**Comment by adrilo** [comment]
Hi @Hightem, you can take a look at this guide: http://opensource.box.com/spout/guides/edit-existing-spreadsheet/

Please note that styles won't be copied over as the reader does not parse the styles of the original spreadsheet.
