### ISSUE TITLE
Php 7.1 issue with XLSX open

### ISSUE THREAD

**Issue by awisur** [box/spout#422]
I get the following error 1 out of 3 times when I execute the same code on the same file with php 7.1
In php 5.6 I get no error.

```
$reader = ReaderFactory::create(Type::XLSX);
$reader->open(SYSTEM_PATH . 'var/uploaded/importfiles/1495547547477_test.xlsx');

foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        // do stuff with the row
    }
}
$reader->close();
```

**This throws this error every other time i Run the code in Apache + php 7.1:**
Warning: XMLReader::open(): Unable to open source data in /www/.../Box/Spout/Reader/Wrapper/XMLReader.php on line 36

1	Box\Spout\Reader\AbstractReader->open( )	.../ImportController.php:347
2	Box\Spout\Reader\XLSX\Reader->openReader( )	.../AbstractReader.php:123
3	Box\Spout\Reader\XLSX\Helper\SharedStringsHelper->extractSharedStrings( )	.../Reader.php:79
4	Box\Spout\Reader\Wrapper\XMLReader->openFileInZip( )	.../SharedStringsHelper.php:92
5	open ( )	.../XMLReader.php:36

[1495547547477_test.xlsx](https://github.com/box/spout/files/1024934/1495547547477_test.xlsx)

**Comment by adrilo** [comment]
Hmmm I just tested it with your file, and it works 100% of the time.
```
$ php -v
PHP 7.1.5 (cli) (built: May 13 2017 13:30:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

Does the file change at all between your different tests?

**Comment by awisur** [comment]
Strange this is from my environment...

$ php -v
PHP 7.1.5 (cli) (built: May 13 2017 13:30:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans

**Comment by awisur** [comment]
Does this give any more meaning to you?

RawLog: Box\Spout\Common\Exception\IOException: Could not open /www/.../importfiles/1495547547477_test.xlsx for reading! (Could not open "xl/sharedStrings.xml".) in /www/.../Box/Spout/Reader/AbstractReader.php:126

**Comment by awisur** [comment]
Seems to be similar to this: https://github.com/box/spout/issues/379

**Comment by awisur** [comment]
libxml_disable_entity_loader(false); Seems to fix my problem aswell, since this is a somewhat common problem, might catch this error and provide the solution in the exception message? Anyway works now :)
