### ISSUE TITLE
reader->open is slow

### ISSUE THREAD

**Issue by tinybright** [box/spout#426]
It takes  40 second to  open a 16 * 16000 excel.

>                 $reader = ReaderFactory::create(Type::XLSX);
>                 Yii::log("start",CLogger::LEVEL_INFO,"debug.import");
>                 $path = PathUtil::getBaseSitePath().DIRECTORY_SEPARATOR.$path;
>                 $reader->open($path);
>                 Yii::log("end",CLogger::LEVEL_INFO,"debug.import");

**Comment by stevesweets** [comment]
Is the file especially large, or does it use shared strings?  Spout is fantastically better performant than other xlsx readers (by being intentionally limited in what it does), but still has to unzip the file and parse the xml.

40 seconds doesn't seem too far off par with the performance expectations:

https://github.com/triad-ltd/spout/tree/develop_3.0#frequently-asked-questions

**Comment by madflow** [comment]
Please attach an anonymized file so we can try to reproduce the issue.

**Comment by adrilo** [comment]
@stevesweets is right. With XLSX files using shared strings (and a lot of them), Spout has to go through the file listing all of them, split them in chunks and save the chunks on disk. This first processing is required to be able to map string index to string value (XLSX can define the content of cell "A1" as being the string at index 42, therefore you need to know what string corresponds to index 42).

This whole process is done when `open` is called. Although this could be moved to later (when you read the first row for instance), you still would have to process the shared strings file - and it would take as much time.
Assuming that all cells contain a different shared string, this means your XLSX file contains almost 1 million strings. Given the amount of memory available on your server, Spout decided that storing these 1 million strings in memory may crash your server (OutOfMemory error) and therefore starts using the on-disk cache. 40 seconds is therefore not too bad!
