### ISSUE TITLE
Problems reading XLSX

### ISSUE THREAD

**Issue by difasanditya** [box/spout#448]
Hi, I have this error while trying to read file.
I use Windows 10 Pro, with PHP version 5.6.3.
Already tried using `libxml_disable_entity_loader(false);` and still no luck.
Here's my code:

```
require_once "Spout/Autoloader/autoload.php";
use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;
$filePath = "file/form.xlsx";
$reader = ReaderFactory::create(Type::XLSX);
$reader->open($filePath);
$reader->close();
```

Error message:
```
Fatal error: Uncaught exception 'Box\Spout\Common\Exception\IOException' with message 'Could not open file/form.xlsx for reading! (Could not open "xl/sharedStrings.xml".)' in C:\xampp\htdocs\test\Spout\Reader\AbstractReader.php:126 Stack trace: #0 C:\xampp\htdocs\test\form.php(13): Box\Spout\Reader\AbstractReader->open('file/form.xlsx') #1 {main} thrown in C:\xampp\htdocs\test\Spout\Reader\AbstractReader.php on line 126
```

Here's my file:
[form.xlsx](https://github.com/box/spout/files/1164419/form.xlsx)

Thank you

**Comment by adrilo** [comment]
@difasanditya can you try using a full path for your file? Something like "C:/.../.../file/form.xlsx"
It works fine on a mac, so I'm suspecting there's something wrong with how Spout handles path on Windows.

**Comment by difasanditya** [comment]
@adrilo wow thanks, it works.

**Comment by adrilo** [comment]
Glad to hear that :) I really need to fix this bug though!
