### ISSUE TITLE
ODS output

### ISSUE THREAD

**Issue by Lewiscowles1986** [box/spout#45]
Hi I have a repo for fast-efficient writing to ODS,and I was wondering if it is a file-format you are interested to have as part of spout?

**Comment by adrilo** [comment]
Hi @Lewiscowles1986 !
Adding a new format is not straight forward, as it needs to support both reading and writing, and doing so in a scalable way. Spout also has an extensive test suite that covers most of the use cases.

I am not familiar with ODS but I'll be happy to check your repo to see how easy it is to integrate it. Is ODS a popular format?

**Comment by Lewiscowles1986** [comment]
Are you joking when you ask "Is ODS a popular format?". It's the open specification that libreoffice / openoffice use as a spreadsheet format. In some countries public sector departments have to save in open formats, and most of Europe is transitioning towards them for vendor agnostic IT files. 

Even newer MS Office installs offer users the chance to save by default in the open formats (not just MS open doc). It is far superior to Excel in terms of scalability and performance (I can open larger documents in OpenOffice / LibreOffice than Excel).

As a more personal example, my own business CRM & ERP software packages currently use ODS as an alternative for writing, because there were scalability issues with PHPExcel. For reading, I could do some work to integrate, to be honest I wanted to know if it was worth me doing the work and submitting a pull request ;).

**Comment by adrilo** [comment]
My question was more in terms of global usage. I agree that the format is really important for some people but my point was, if it represents less than 0.1% of the global usage, does it worth adding this format?
Anyway, I did my research and it seems like it represents a non negligible usage. So I think it would be a great addition to Spout and I'll be happy to help you get a pull request through.

**Comment by rogeriopradoj** [comment]
:+1:

**Comment by adrilo** [comment]
Just added an ODS writer: #99. Reader is coming with updated documentation but you can start playing with it if you want :)
@Lewiscowles1986, feel free to submit pull requests or comments on this since you have experience with an ODS writer before. The current implementation can most likely be improved :)

**Comment by Lewiscowles1986** [comment]
Do you know what, it stalled as I have a major work project ongoing atm and not much free time at PC, thanks ;)
