### ISSUE TITLE
Drop support for unmaintained php versions

### ISSUE THREAD

**Issue by garak** [box/spout#455]
I guess there's nothing much to say: you should drop php 5, or at least php 5.4 and 5.5, in the next major version

**Comment by madflow** [comment]
I can only say that we bumped the minimum version to 5.6 in the current development branch ```develop_3.0```: 

https://github.com/box/spout/blob/develop_3.0/composer.json#L15

So if this becomes the next major version  - support for PHP < 5.6 will be dropped.

**Comment by garak** [comment]
What about moving to >=7.0?

**Comment by adrilo** [comment]
5.6 will still be used a lot, as many providers won't have support for 7.x. So for now, we'll keep this version.

**Comment by garak** [comment]
Well, "drop support" does not mean any break for 5.6 users. They just don't get new versions (and they should expect something like that, being on a unmaintained version)

**Comment by adrilo** [comment]
You're right but I'm still not sure whether it's a good idea to drop support now. Supporting PHP >= 7.1 would probably be a better choice in terms of development productivity (typing!). But being able to deliver new features to a lot of users is also important. So it's a compromise...

For now, I'll keep 5.6 but it may change as the 3.0 release is not going out any time soon.

**Comment by garak** [comment]
Maintaining a double branch for a while should not be a big effort, you can easily automate conversions between 7.1 and 5.6
