### ISSUE TITLE
box/spout returns empty strings in iterator if a filter is set

### ISSUE THREAD

**Issue by swiffer** [box/spout#468]
If a Filter is set within an Excel File (rows not filtered but column filter is defined) all values of a row are empty string instead of the actual strings

**Comment by adrilo** [comment]
Hi @swiffer, do you mind providing an example of such a file so we can easily reproduce the issue?

**Comment by swiffer** [comment]
yes, of course -> just try out this one

https://bdew-codes.de/DownloadFile.axd?content=electricity&format=excel

**Comment by swiffer** [comment]
xl/tables/table.xml totalsRowShown is 0. The workbook is using shared strings as well.
But all sheetdata is in xl/worksheets/sheet.xml.

```xml
<?xml version="1.0" encoding="utf-8"?><x:table id="1" name="Table1" displayName="Table1" ref="A1:C908" totalsRowShown="0" xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><x:autoFilter ref="A1:C908" /><x:tableColumns count="3"><x:tableColumn id="1" name="Netzbetreibernummer" /><x:tableColumn id="2" name="Sitz" /><x:tableColumn id="3" name="Unternehmen" /></x:tableColumns><x:tableStyleInfo name="TableStyleLight9" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0" /></x:table>
```

**Comment by adrilo** [comment]
Hi @swiffer, the issue was fixed here: https://github.com/box/spout/commit/6d44cd26cc49c0fd59ffc01a4c187223c4b183cc

I'll release a new version so that you'll only need to upgrade to 2.7.3
