### ISSUE TITLE
TIME FORMAT

### ISSUE THREAD

**Issue by Karador1995** [box/spout#469]
Hi, I have a problem saving the time of my EXCEL file, the format I use is this example: 21:00:00, I add the following line to my project, but it gives me an error:

```
$reader->setShouldFormatDates(false);
```

I leave the code

```
public function guardar_horario(){

    
    if (!empty($_FILES['file']['name'])) {
      
    
    $pathinfo = pathinfo($_FILES["file"]["name"]);
     
 
        if (($pathinfo['extension'] == 'xlsx' || $pathinfo['extension'] == 'xls') 
           && $_FILES['file']['size'] > 0 ) {
         
        // Nombre Temporal del Archivo
        $inputFileName = $_FILES['file']['tmp_name']; 
    
        //Lee el Archivo usando ReaderFactory
        $reader = ReaderFactory::create(Type::XLSX);
        $reader->setShouldFormatDates(false);
        
        // Abrimos el archivo
        $reader->open($inputFileName);
        $count = 1;
 
        //Numero de Hojas en el Archivo
        foreach ($reader->getSheetIterator() as $sheet) {
             
            // Numero de filas en el documento EXCEL
            foreach ($sheet->getRowIterator() as $row) {
 
                // Lee los Datos despues del encabezado
                // El encabezado se encuentra en la primera fila
             if($count > 1) {


                $data = array(


                  'rut_usu' => $this->input->post('rut_usu'),
                  'hrs_ini' => $row[0],
                  'hrs_ter' => $row[1],
                  'lunes' => $row[2],
                  'martes' => $row[3],
                  'miercoles' => $row[4],
                  'jueves' => $row[5],
                  'viernes' => $row[6],
                  'sabado' => $row[7],
                  'fecha_ini' => $this->input->post('fecha_ini'),
                  'fecha_ter' => $this->input->post('fecha_ter')

               ); 
    
              
              $this->db->insert('horario',$data);

             } 
                $count++;
            }
        }
 
          // cerramos el archivo EXCEL
          $reader->close();
 
         } else {
 
          echo "Seleccione un tipo de Archivo Valido";
       }
 
     } else {
 
      echo "Seleccione un Archivo EXCEL";
     
       }


       }

 }
```

**Comment by adrilo** [comment]
@Karador1995 what do you mean by "it gives me an error"? Can you copy the error here? What happens and what do you expect?
We need more info to be able to help.

**Comment by Karador1995** [comment]
This is Error

`A PHP Error was encountered

Severity: Error

Message: Call to undefined method Box\Spout\Reader\XLSX\Reader::disableTimeAutoConversion()

Filename: controllers/cHorarios.php

Line Number: 91

Backtrace:`

I want to be able to enter the time as follows: 21:00:00 in the documentation appeared that line of code, so that the format will not change to the one that uses SPOUT

**Comment by Karador1995** [comment]
It does not recognize the format of the example time: 22:00:00, so columns with that format are not saved.

**Comment by Karador1995** [comment]
Could you tell me, why are not my columns saved in the following format? example 23:00:00 (TIME), this line of code is supposed to be to prevent Spout automatically converts it to its format?

$ reader-> setShouldFormatDates (false);

I'm reading a file to save it later. Please I need your help, more than two days that I do not give with a solution.

**Comment by adrilo** [comment]
`$reader->setShouldFormatDates(false);` can be omitted as it's the default value. This will return a `DateTime` object. If you want to get a string back (e.g. "23:00:00" if that's what you entered in your XLSX file), then you should pass `true` instead of `false`.

Now I don't know why the error you mentioned (`Call to undefined method Box\Spout\Reader\XLSX\Reader::setShouldFormatDates()`) occurs. Can you add a `var_dump($reader)` before calling `setShouldFormatDates()` and let me know what's printed?

**Comment by Karador1995** [comment]
var_dump ($ reader) shows this:

object(Box\Spout\Reader\XLSX\Reader)#21 (6) { ["tempFolder":protected]=> NULL ["zip":protected]=> NULL ["sharedStringsHelper":protected]=> NULL ["sheetIterator":protected]=> NULL ["isStreamOpened":protected]=> bool(false) ["globalFunctionsHelper":protected]=> object(Box\Spout\Common\Helper\GlobalFunctionsHelper)#22 (0) { } }

**Comment by adrilo** [comment]
Ok, then you should be able to use `setShouldFormatDates()`. Which version of Spout are you using?

**Comment by Karador1995** [comment]
spout-2.4.3

**Comment by Karador1995** [comment]
I am using Codeigniter, I do not know if it has to do with that, as I mentioned before, all the columns are saved if I remove this line:

$ reader-> setShouldFormatDates (false);

Except those that are in the format of the time I wrote.

**Comment by adrilo** [comment]
Alright, the function you're trying to use was added in v2.5.0... That's why it can't find it!
You need to upgrade Spout and that should work better.

**Comment by Karador1995** [comment]
OK thank you very much :D
