### ISSUE TITLE
 Trying to get property of non-object: /vendor/box/spout/src/Spout/Reader/XLSX.php:227

### ISSUE THREAD

**Issue by f8bar** [box/spout#47]
Hi,

I get the following error:
 Trying to get property of non-object: /vendor/box/spout/src/Spout/Reader/XLSX.php:227
reading the following Excel with the following code:
```
$data = array();
        $reader = \Box\Spout\Reader\ReaderFactory::create(\Box\Spout\Common\Type::XLSX);
        $reader->open($file);
        $counter = 0;
        $header = array();
        while ($reader->hasNextSheet()) {
            $reader->nextSheet();
            while ($reader->hasNextRow()) {
                $counter++;
                if ($counter == 1) {
                    $header = $reader->nextRow();
                    continue;
                }
                $data[] = array_combine($header, $reader->nextRow());
            }
        }
        $reader->close();
        return $data;
```
![2015-06-03 14_47_32-microsoft excel - template xlsx](https://cloud.githubusercontent.com/assets/1819228/7960268/847c2d46-09ff-11e5-8649-0b7817816bea.png)

**Comment by carobiscuit** [comment]
I am getting this same error -- if my last column is blank or contains blanks. If I move it and the last column is NOT blank I don't get this error anymore.

**Comment by adrilo** [comment]
@carobiscuit The symptom is the same as this issue but the underlying error is most likely different. Can you please create another issue and if possible attach a file that demonstrates this issue? Thanks!
