### ISSUE TITLE
Running to memory limit

### ISSUE THREAD

**Issue by matthieubrunet** [box/spout#470]
Hi there,
By reading the faq http://opensource.box.com/spout/faq/ I thought Spout wont have memory problem. But when I try to write a 100 000 row files, I get this error : "Allowed memory size of 134217728 bytes exhausted (tried to allocate 88 bytes)".
Why is this happening if the data is streamed to file and not kept in memory ?
Do you know a way to prevent it without changing PHP memory_limit ?

Thanks a lot !

**Comment by matthieubrunet** [comment]
My mistake, the error came from my datatbase driver, not from Spout

**Comment by ryzulla** [comment]
i got same problem. how to fix it?

**Comment by adrilo** [comment]
Spout was built to not use much memory so you're probably doing something wrong in your code, like storing the value of the rows in an array.

**Comment by pokebuddyb** [comment]
Probably same problem as https://github.com/box/spout/issues/373
