### ISSUE TITLE
Bad performance (follow-up from #468)

### ISSUE THREAD

**Issue by swiffer** [box/spout#471]
I can import the file already linked in #468 now. For no known reason performance seems to be really bad when comparing to other files.

6200 rows take more than 30 seconds to be processed.

**Comment by adrilo** [comment]
There's probably something wrong with the way you import your file. When I tried to read it, it's super fast:

```
$ > time php readfile.php
...
7769 | Heilbronn | NHL Netzgesellschaft Heilbronner Land GmbH & Co. KG
7770 | Ostfildern | Stadtwerke Ostfildern

real	0m0.778s
user	0m0.748s
sys	0m0.014s
```

Can you paste your code here so we can debug it?

**Comment by swiffer** [comment]
PHP 7.1.9

```php
<?php

include 'vendor/autoload.php';

use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;

$reader = ReaderFactory::create(Type::XLSX);
$reader->open('Spreadsheet.xlsx');

foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $rowNumber => $row) {
        /* row processing commented out for this benchmark */
    }
}

$reader->close();

?>
```

```bash
$ time php index.php

real    3m10,847s
user    0m0,015s
sys     0m0,030s
```

**Comment by swiffer** [comment]
the command where all the time is spent is `$reader->open(...)`

**Comment by swiffer** [comment]
is it related to #426 ?

**Comment by swiffer** [comment]
i disabled Windows Defender Real Time Protection and execution time immediately decreased to 20s.

**Comment by swiffer** [comment]
On Linux (gitlab-runner / phpunit test suite with code coverage enabled (xdebug)) xdebug seems to slow down processing from 30 seconds (total testsuite execution time) to 6 minutes

**Comment by adrilo** [comment]
The file `Spreadsheet.xlsx` that you are trying to read, is that the same one you sent as part of the other issue?
Also, can you try adding `var_dump(ini_get('memory_limit'));` and paste the output here?

**Comment by swiffer** [comment]
yes, it's the same file as provided in the other issue.

`var_dump(ini_get('memory_limit'))` shows `128MB`

i enabled the profiler in xdebug and ran the code again

![unbenannt](https://user-images.githubusercontent.com/2990373/31065646-559ad5a8-a747-11e7-8206-9cf0cf24e271.PNG)

```php
use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;

$reader = ReaderFactory::create(Type::XLSX);
$reader->open('Spreadsheet.xlsx');
```

**Comment by swiffer** [comment]
Tried multiple PHP versions (7.0.24 32bit/64bit) // (7.1.10 64bit) and multiple versions of box/spout. Performance was equally bad. No idea what's going on. Any help would be appreciated.

**Comment by adrilo** [comment]
Reduction to 8 seconds makes sense, as your change caused Spout to use an in-memory strategy instead of a file-based strategy to  to read cell data, which is way faster.

Now you're right, 8 seconds is still a lot. I'm not sure how to read your screenshots. Is there a way to know the total execution time of each function?

**Comment by madflow** [comment]
Just for lulz I wanted to try this myself. The linked file in #468 hast 908 rows. In the first post you say something about 6200 rows (?). For what it's worth: When I run the linked file (I had to re-save it for some reason, so spout would be able to read it), it is equally fast like @adrilo stated.

**Comment by swiffer** [comment]
Sorry guys, i was measuring time when running my testsuite in PHPUnit (6.3.1). It looks like PHPUnit slows down things in $sheet->getRowIterator() => $row quite a lot. I limited the Iterator two 10 rows when running PHPUnit reducing time so results are on pair with your examples.

Additionally i got equal results to yours when not running in PHPUnit now!
