### ISSUE TITLE
Backslash on CSV is escaping the double quote but it should not

### ISSUE THREAD

**Issue by garimpeirodouniverso** [box/spout#473]
I have something like the following CSV file:

"col1";"col2"
"val1\\";"val2"

The expected values from the second row would be _val1\\_ and _val2_ , because the backslash should not escape the double quote (the correct way of escaping the double quote would be to "double-double quote" instead, as per RFC-4180).

Instead, Spout will read it as _val1\\";val2"_ (as the first value), and ignore the second value.

Am I missing something? Is there a way to set the backslash as a non-escaper?

Thanks

**Comment by garimpeirodouniverso** [comment]
I just found out that the GlobalFunctionsHelper will call PHP's _fgetcsv_ without the last parameter, which is exactly the escape character (as per PHP default, it will be the backslash (\\).

I'm planning on making a PR in which the user may set the escape character if necessary (calling out Reader::setFieldEscape or something similar). To be RFC-4180 compliant, the escape character should be the same as the enclosure character by default.

**Comment by adrilo** [comment]
Hi @garimpeirodouniverso !

You're absolutely right! `fgetcsv` and `fputcsv`'s implementation is wrong, in regards to RFC-4180.
Feel free to submit a pull request. I think that the way to do it should be to use the enclosure character as the escape character.

So changing
```
fputcsv($this->filePointer, $dataRow, $this->fieldDelimiter, $this->fieldEnclosure);
``` 
into
```fputcsv($this->filePointer, $dataRow, $this->fieldDelimiter, $this->fieldEnclosure, $this->fieldEnclosure);```

**Comment by garimpeirodouniverso** [comment]
Hello @adrilo !

For the PR I am thinking about some solutions:

1) make the Escape Char parameterizable, just as in fgetcsv, and make the default as "\\" (for backwards compatibility matters)
2) make the Escape Char parameterizable, just as in fgetcsv, and make the default equals the Field Enclosure (for RFC-4180 compliant)
3) go full RFC compliant and make Escape Char always equals Field Enclosure (like your suggestion)

Personally I like 3rd solution for CSV because it enforce CSV standardization, but maybe it is too "ballsy". What are your thoughts?

**Comment by adrilo** [comment]
I like option 3 as well. I'm usually in favor of a simple API, where only important options can be accessible. Adding an API for the escape character means more maintenance for a really low usage, so I don't think that's worth it in the long run.

Since the change is not backwards compatible though, what you can do is create a PR based on `develop_v3.0`. This change will be merged as part of Spout 3.0.

**Comment by garimpeirodouniverso** [comment]
Great! Will do for Spout 3.0 then.

Thanks for the insights @adrilo !

**Comment by garimpeirodouniverso** [comment]
@adrilo PR made to Dev 3.0. Found out that we only need to change GlobalFunctionsHelper, since the calls to fgetcsv and fputcsv are wrapped there.

Although, the escape_char parameter on fputcsv and fgetcsv is from PHP 5.5.4+ (this is the reason why one of the tests failed I guess...).

**Comment by adrilo** [comment]
develop_3.0 is PHP 5.6 and above, so this should be ok.

**Comment by madflow** [comment]
See my comment here: https://github.com/box/spout/pull/475#issuecomment-336043460
