### ISSUE TITLE
Spout stops reading XLSX files with empty rows.

### ISSUE THREAD

**Issue by pacopa** [box/spout#474]
Spout stops reading when it finds empty rows in the middle of XLSX files and setShouldPreserveEmptyRows is true.

I attach a problematic file.
[file_with_white_rows_in_the_middle.xlsx](https://github.com/box/spout/files/1368897/file_with_white_rows_in_the_middle.xlsx)

**Comment by adrilo** [comment]
Hi @pacopa,

I tried reading your file with and without the `setShouldPreserveEmptyRows` setting. Here are the results:

Without:
```
$ php test.php
Ref_Pro | Descripción | EAN unitario | EAN envase | EAN embalaje | EAN palet | Precio | Tasas | Factor conversor | Un. Envase | Un. Embalaje | Un. Palet | Peso | Cubicación | Cant. desde 1 | Precio tarifa 1 | Cant. desde 2 | Precio tarifa 2 | Cant. desde 3 | Precio tarifa 3 | Cant. desde 4 | Precio tarifa 4 | Cant. desde 5 | Precio tarifa 5 | Grupo dto. | Observaciones de línea | Iva
4052 | LAMPARA DICROICA LED GU5,3 5,6W EQUIV.50W 365LM 2700K | 8422148001022 | 18422148001029 |  |  | 2.56 | 0.2 | 1 | 10 | 100 |  |  |  |  |  |  |  |  |  |  |  |  |  | A |  | 21
4053 | LAMPARA DICROICA LED GU5,3 5,6W EQUIV.50W 365LM 2700K | 8422148001022 | 18422148001029 |  |  | 2.56 | 0.2 | 1 | 10 | 100 |  |  |  |  |  |  |  |  |  |  |  |  |  | A |  | 21
 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
4054 | LAMPARA DICROICA LED GU5,3 5,6W EQUIV.50W 365LM 2700K | 8422148001022 | 18422148001029 |  |  | 2.56 | 0.2 | 1 | 10 | 100 |  |  |  |  |  |  |  |  |  |  |  |  |  | A |  | 21
```

With:
```
$ php test.php



Ref_Pro | Descripción | EAN unitario | EAN envase | EAN embalaje | EAN palet | Precio | Tasas | Factor conversor | Un. Envase | Un. Embalaje | Un. Palet | Peso | Cubicación | Cant. desde 1 | Precio tarifa 1 | Cant. desde 2 | Precio tarifa 2 | Cant. desde 3 | Precio tarifa 3 | Cant. desde 4 | Precio tarifa 4 | Cant. desde 5 | Precio tarifa 5 | Grupo dto. | Observaciones de línea | Iva
4052 | LAMPARA DICROICA LED GU5,3 5,6W EQUIV.50W 365LM 2700K | 8422148001022 | 18422148001029 |  |  | 2.56 | 0.2 | 1 | 10 | 100 |  |  |  |  |  |  |  |  |  |  |  |  |  | A |  | 21
4053 | LAMPARA DICROICA LED GU5,3 5,6W EQUIV.50W 365LM 2700K | 8422148001022 | 18422148001029 |  |  | 2.56 | 0.2 | 1 | 10 | 100 |  |  |  |  |  |  |  |  |  |  |  |  |  | A |  | 21
 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
4054 | LAMPARA DICROICA LED GU5,3 5,6W EQUIV.50W 365LM 2700K | 8422148001022 | 18422148001029 |  |  | 2.56 | 0.2 | 1 | 10 | 100 |  |  |  |  |  |  |  |  |  |  |  |  |  | A |  | 21
```

As you can see, all the rows are read and when `setShouldPreserveEmptyRows` is set to `true`, the 3 first empty lines are being returned.

Do you see another behavior? Did you expect something different? To me, this behavior is correct.

**Comment by pacopa** [comment]
Hi @adrilo,

You are right. Spout is working properly. 
There was an error in my code. I'm sorry to have bothered you with a false bug.

Thank you very much for your help.

**Comment by jupitern** [comment]
Hi,
I am trying to read a file that has a title in line 2 and line 1 and 3 are empty. Table titles are at line 4 and table data at line 5. When I read the file with spout table data is at index 3

How can I use the "setShouldPreserveEmptyRows" property? Is this the right code?

$reader = \Box\Spout\Reader\ReaderFactory::create(\Box\Spout\Common\Type::XLSX);
$reader->open($filepath.$filename);
$reader->setShouldPreserveEmptyRows(true);

foreach ($reader->getSheetIterator() as $sheet) {
            if ($sheet->getIndex() == 0) {
                $rowIterator = $sheet->getRowIterator();

                foreach ($sheet->getRowIterator() as $key => $row) {
                    echo "line $key \n";
                    var_dump($row);
...

Thanks

**Comment by adrilo** [comment]
Try calling `$reader->setShouldPreserveEmptyRows(true);` before `$reader->open`. Let me know if that makes any difference. Otherwise, it should work.

**Comment by jupitern** [comment]
yap. that works. is thar information in the docs? I tried search everywhere and didn't find it.
Thanks.

**Comment by adrilo** [comment]
The documentation hasn't been updated so it's not in there. Also Spout used to complain when setting options after opening the reader but looks like it does not anymore...
We'll try to fix that.
