### ISSUE TITLE
Add option for autofilter

### ISSUE THREAD

**Issue by aocneanu** [box/spout#477]
Hello,

I know it's something small but I find adding an auto-filter option really useful, maybe other will do to.

Thanks.

**Comment by adrilo** [comment]
Can you please give more details? Is that specific to a filetype? What's the expected behavior of the auto-filter?

**Comment by aocneanu** [comment]
It's specific to xls/xlsx files and it's an default filter for the first column.

In most of the cases it's the first thing that anybody does after they open a xls file without a filters :)

You can check the image below.

![image](https://user-images.githubusercontent.com/16073274/31611370-79918766-b284-11e7-9621-db363ade4162.png)

**Comment by adrilo** [comment]
There could be a bunch of different filters. What we'd need here would be something similar to [this](https://phpspreadsheet.readthedocs.io/en/develop/topics/autofilters/#simple-filters), right? Having a filter on the first row should cover most use cases I guess.

Also, this option is available on ODS documents so it should be added for this filetype too, if possible

**Comment by aocneanu** [comment]
Exactly!

Adrian Ocneanu
0722 44 33 77

**Comment by kstanleygeti** [comment]
Is there an update on this enhancement?  Just curious as I have been using this package for a while but had a request come in just now from a client for this feature.

**Comment by adrilo** [comment]
This is not going to be implemented in the near future, sorry. It adds complexity (making maintenance harder) and the added-value is not enough IMO (ie. too far from what Spout is about).
Closing this issue then.
