### ISSUE TITLE
syntax error T_OBJECT_OPERATOR

### ISSUE THREAD

**Issue by rseptian** [box/spout#478]
`Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /var/www/html/webadmin/simple/test/test/plugins/excel/Writer/XLSX/Writer.php on line 116`

in my localhost works
but in my server not works

```php
require_once '/src/Spout/Autoloader/autoload.php'; // don't forget to change the path!
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Common\Type;

$i=0;
$filePath =__DIR__ . "/" . ($i+1) . ".xlsx";

$writer = WriterFactory::create(Type::XLSX); // for XLSX files
$writer->openToBrowser($filePath);

$writer->addRow(array('a','b'));

for ($j = 0; $j < 1000; $j++) {
     $row = range(($j*10)+1, ($j+1)*10);
     $writer->addRow($row);
   }

$writer->close();
```

**Comment by adrilo** [comment]
Which version of Spout are you using on your server?

**Comment by rseptian** [comment]
version spout-2.7.1

**Comment by adrilo** [comment]
Spout code does not have such errors (otherwise tests would not pass). So if the issue is really in the Writer.php file, I would suggest you to reinstall Spout and see how it goes.
