### ISSUE TITLE
1904-based dates are parsed incorrectly

### ISSUE THREAD

**Issue by k8n** [box/spout#480]
1904-based dates are common on Mac. The offset from the 1900-based dates is 1462 days.

[What they are and why](https://support.microsoft.com/en-us/help/214330/differences-between-the-1900-and-the-1904-date-system-in-excel).

[How to tell which format is used (on PHPExcel's example)](https://github.com/ddeboer/phpexcel/blob/master/Classes/PHPExcel/Reader/Excel2007.php#L716)

**Comment by adrilo** [comment]
Hey @k8n ! Thanks for reporting this issue. I'm looking into it and should be able to push a fix soon

**Comment by adrilo** [comment]
@k8n, the issue has been fixed in the v3.0 branch. This release won't be out very soon, so if you need it now, you can always checkout the v3.0 branch instead of the current stable release.
