### ISSUE TITLE
Reader XLSX - read cell as string

### ISSUE THREAD

**Issue by kravcik** [box/spout#481]
Hello, first thanks for great work!

I have cell like this. Problem is when is type of column is bad set (custom instead of general). Would be nice if user is able "to force" string reading cell.

**Cell (not general column type)**

> 01.X 

**Without formatDates:**

`$reader = ReaderFactory::create(Type::XLSX);`      
`$reader->setShouldFormatDates(TRUE);`
`"1-Oct" //output`

**With formatDates:**

`$reader = ReaderFactory::create(Type::XLSX);`      
`$reader->setShouldFormatDates(FALSE);`
`"date object (2016-10-01)" //output`

**Desired output:**
`$reader = ReaderFactory::create(Type::XLSX);`      
`$reader->forceReadStrings();`
`"01.X" //output`

Thanks

**Comment by adrilo** [comment]
@kravcik do you have a file I could use to reproduce the error?

**Comment by kravcik** [comment]
Ofc, row 1539. [Sešit1.xlsx](https://github.com/box/spout/files/1448968/Sesit1.xlsx)

**Comment by kravcik** [comment]
I guess this will be problem of some version of Excel.
![image](https://user-images.githubusercontent.com/10499130/32579753-93537446-c4e2-11e7-9780-c5f6cfdae127.png)

Yeah file is not really good one. But its from big insurance company and there is no chance to fix it. I just try ask about posibility to "force string reading" regardless date format. I have two solutions:

1. Resave file with right type (annoying for users)
2. Make special table and replace some special cases (ugly spagetti)

Thank you for your time, I guess you can close this one.
