### ISSUE TITLE
Generate new XLSX file

### ISSUE THREAD

**Issue by Karador1995** [box/spout#482]
Hello, it's the first time I'll try to create a new XLSX file. Check the documentation. And try to create a blank file without a good result. What am I doing wrong? I'm calling the function with a button, to open a new tab, but it only shows me errors of undefined variables. Could someone give me an example of how to generate a blank document? or with some written lines of whatever. I would appreciate it.

      require_once APPPATH.'/third_party/Spout/Autoloader/autoload.php';

      use Box\Spout\Common\Type;
      use Box\Spout\Writer\WriterFactory;
     use Box\Spout\Writer\Style\StyleBuilder;
     use Box\Spout\Writer\Style\Color;

     public function excel(){

      $style = (new StyleBuilder())->setFontBold()->setFontSize(15)->setFontColor(Color::BLUE)->setShouldWrapText()->setBackgroundColor(Color::YELLOW)->build();
      $writer = WriterFactory::create(Type::XLSX);
      $writer->openToFile($filePath);

      $writer->addRowWithStyle($singleRow, $style); // style will only be applied to this row
      $writer->addRow($otherSingleRow); // no style will be applied
      $writer->addRowsWithStyle($multipleRows, $style); // style will be applied to all given rows

      $writer->close();
            
	 }
       
       //In  View
       <script>
      $(document).ready(function(){

      $('#btn_search').on('click', function(){
    
         window.open('<?php echo base_url();?>C_Conuslt/excel' );

           });

       });

      </script>

**Comment by adrilo** [comment]
`openToFile()` is used to create a file on disk (and takes a `$filePath`, which indicates where to create the file). In your example `$filePath` is not defined so it can't work. Also, I think that what you need is not `openToFile()` but `openToBrowser($fileName)` which will send the generated XLSX file to the browser (i.e. download the file) once it's done.

Try this, it should work better!
