### ISSUE TITLE
Xls support

### ISSUE THREAD

**Issue by Koc** [box/spout#51]
Does this library supports old 2003 office format? if not - would be nice add it

**Comment by adwww** [comment]
No. See the [reader](https://github.com/box/spout/blob/master/src/Spout/Reader/ReaderFactory.php#L29) or [writer](https://github.com/box/spout/blob/master/src/Spout/Writer/WriterFactory.php#L29) sources to see all the supported formats. (ie. csv and xlsx).

Also, :-1: - this looks like a clean modern library - supporting the ugly old proprietary format might risk that!

**Comment by adrilo** [comment]
Spout is extremely useful if you need to work with large files. XLS has inherent limitations that makes it a non-optimal format, compared to XLSX.

Adding a new format requires a significant investment to make sure reading and writing into this format can scale. @Koc, if you are ready to take on this challenge, I will be happy to help you with your pull request!

**Comment by Koc** [comment]
Oh, no. I haven't enough knowlege for this ;(
