### ISSUE TITLE
Read custom cell format

### ISSUE THREAD

**Issue by Fenweldryn** [box/spout#517]
Any way of getting the custom format the cell has or to read the cell as shown in excel?
Clicking on the cell only shows the number (image 1). Cell properties show a custom format (image 2).
Sorry if this is not the place for it, I needed this 3 years ago and gave up back then. Needing it again!

![spout](https://user-images.githubusercontent.com/8657982/33089059-43ce27d6-cece-11e7-9602-220d2f61d52c.png)

**Comment by adrilo** [comment]
Hi @Fenweldryn !

We are working on adding this kind of info to the Cells the reader returns. The first thing we'll tackle is the style of the cell (#513) but eventually we'll need to add the custom format you mentioned.
So it's coming but I can't tell you when.

**Comment by Fenweldryn** [comment]
Thanks for the info!
