### ISSUE TITLE
Implement Cell Alignment

### ISSUE THREAD

**Issue by adhenrique** [box/spout#519]
Hey @adrilo, have someone thinking about Cell Align?
If not, I wanted to know if I can help with this enhancement.

I made some changes to the Style and StyleHelper classes, and I got the result I wanted.

Can I send a PR?

**Comment by adrilo** [comment]
Hi ! Sure, feel free to submit a PR. Please make sure to make it against the `develop_3.0` branch.
I'll take a look as soon as possible.

**Comment by mbrodala** [comment]
@adhenrique can you post your changes?

**Comment by samalenge74** [comment]
Hi. How do i implement text alignment in cell/column?
Thank you

**Comment by adrilo** [comment]
This is not supported yet.
