### ISSUE TITLE
Cannot open XLSX files on Windows - forward slashes must be used inside of the ZIP file, instead of DIRECTORY_SEPARATOR.

### ISSUE THREAD

**Issue by kewlar** [box/spout#52]
When trying to read an XLSX file, using the provided code example, the following warnings/errors are generated (cleaned up a little):

* *Warning:* XMLReader::open(zip://D:\www\spikes\xlsx-reading/data/smm.xlsx#xl\sharedStrings.xml): failed to open stream: operation failed in (SharedStringsHelper.php:115)
* *Warning:* XMLReader::open(): Unable to open source data in (SharedStringsHelper.php:115
* *Fatal error:* Uncaught exception 'Box\Spout\Common\Exception\IOException' with message 'Could not open D:\www\spikes\xlsx-reading/data/smm.xlsx for reading! (Could not open "xl/sharedStrings.xml".)' in AbstractReader.php:90

A little investigation revealed that when using PHP zip:// stream wrapper to read a ZIP file, a *forward slash* (instead of a backward slash, as elsewhere in Windows) must be used when accessing files in subdirectories of the ZIP file. Particular culprit: SharedStringsHelper::getSharedStringsFilePath(), but there are others that fail, too.

I'm not certain yet, if this is the issue of the particular file, or all ZIP (XLSX) files, or my platform (Win64/8.1, Apache/2.4.12 (Win32), PHP/5.6.10, Zip/1.12.5, Libzip/0.11.2). Will investigate a little more.

**Comment by kewlar** [comment]
I did some digging.

According to PKWARE .ZIP File Format Specification (https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT):

       4.4.17.1 The name of the file, with optional relative path.
       <...> All slashes
       MUST be forward slashes '/' as opposed to
       backwards slashes '\' for compatibility <...>

...which confirms my experience. But it seems the directory separator used inside the ZIP *was* correct before, and it was changed with in fb0175d6338111562938d0ebc15675212664f93a, in response to #35.

I'm confused. It seems that at least on some configurations (#35) it may require that the directory separator inside the ZIP should be the system's DIRECTORY_SEPARATOR, and on others it should conform to the PKWARE specification (#52).

I'm not sure how to proceed here. I was willing to argue that there's surely a bug (and was willing to provide a fix) before I found out about #35.

Thoughts?

**Comment by adrilo** [comment]
Hey @kewlar,
Just to make sure your issue is related to #35, have you tried changing DIRECTORY_SEPARATOR with "/" in the newest version of Spout?

If it now works for you, then I'm confused too! I searched for a setting that could configure this but I did not find anything...

**Comment by kewlar** [comment]
Hey @adrilo,

Yes, I did change DIRECTORY_SEPARATOR with "/" in Spout, where it deals with reading from ZIP archive, and in my case it solved the problem (https://github.com/kewlar/spout/commit/a527f96fb0940bfc8b0a6acba219c5b63ebe3f4b). It may have been a Uniform Server issue, in #35 case.

I'm inclined to think my current solution is correct... but I'm biased :) I could try installing Uniform Server and run some tests, expecting to reproduce the issue. In any case, it will come down to deciding if:

a) the code should be left as-is (honoring #35), or
b) the code should be changed to use "/" inside ZIP archives (I could submit a pull request), or
c) one of the solutions should be selected as a default, and a fallback for "buggy" configurations be provided.

What do you think?

**Comment by adrilo** [comment]
I ran some tests with WAMP and it was working with both `/` and `\`. I talked to the guy that maintains the ZipArchive library and he confirmed that it should not matter. So my preference would be keep `/` everywhere.

I'll run some tests with UniformServer to see if I can reproduce.

Anyway, even if we use `/` by default, we need to provide a way for people encountering the issue to override this. So c) would be the best solution.

**Comment by adrilo** [comment]
Alright, I tested with WAMP (Apache 2.4.2, PHP 5.4.3, libxml 2.7.8) and Uniform server (Apache 2.4.12, PHP 5.4.42, libxml 2.7.8). The fix that was pushed for #35 now breaks Spout for the versions I tested.

**Comment by kewlar** [comment]
Whee, it works like a charm! Thanks!

**Comment by adrilo** [comment]
:laughing:
