### ISSUE TITLE
Not Working Godaddydaddy Server

### ISSUE THREAD

**Issue by joshy0423** [box/spout#520]
Hi,
   I working on PHP. i am using spout to Upload EXCEL sheet Data to Mysqli DB. i have 2 issues.
1. On My localhost date is working.
2. When i deploye into godaddy server spout not working.

i am attaching the sample Ecxel Sheet.
[lizSampleSheet.xlsx](https://github.com/box/spout/files/1544521/lizSampleSheet.xlsx)

**Comment by adrilo** [comment]
I tried reading your file and here is what I get :
```
$ php test.php
1) Cmp Code  | Cmp Id | Cmp Branch Code  | Cmp name | Report Date | Bill amnt | Paid Amnt
2) IDB1 | null | AAAA003772-00 | ydah Collg  | 1/22/2017 | 200 | 200
```
It looks good to me ! If that's not what you expect then please be more specific describing the issue.
The localhost vs server issue is not something I can really help you with. It probably has something to do with your server config, which we don't control.

**Comment by joshy0423** [comment]
when iam trying to check the date[1/22/2017] value using echo it showing empty value.
thank you for your help.

**Comment by joshy0423** [comment]
i am writing the code below like this is any thing wrong my code. please help me

<?php 
 // DB Config
include('../../inc/db.inc.php');
 
echo "DB connection Successfull";
 
// Include Spout library 
require_once '/spout-2.4.3/src/Spout/Autoloader/autoload.php';
 
use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;

// check file name is not empty
if (!empty($_FILES['file']['name'])) {
      
    // Get File extension eg. 'xlsx' to check file is excel sheet
    $pathinfo = pathinfo($_FILES["file"]["name"]);
     
    // check file has extension xlsx, xls and also check 
    // file is not empty
   if (($pathinfo['extension'] == 'xlsx' || $pathinfo['extension'] == 'xls') 
           && $_FILES['file']['size'] > 0 ) {
         
        // Temporary file name
        $inputFileName = $_FILES['file']['tmp_name']; 
    
        // Read excel file by using ReadFactory object.
        $reader = ReaderFactory::create(Type::XLSX);
 
        // Open file
        $reader->open($inputFileName);
        $count = 1;
 
        // Number of sheet in excel file
        foreach ($reader->getSheetIterator() as $sheet) {
             
            // Number of Rows in Excel sheet
            foreach ($sheet->getRowIterator() as $row) {
 
                // It reads data after header. In the my excel sheet, 
                // header is in the first row. 
                if ($count > 1) { 
 
                    // Data of excel sheet
                    $data['ProgramCode'] = $row[0];
                    $data['ClientID'] = $row[1];
                    $data['PolicyNo'] = $row[2];
                    $data['InsuredName'] = $row[3];
                    $data['ReportDate'] = $row[4];// date is coming on UCT Formate 
		   // Date Conversion
                    $d=strtotime($data['ReportDate']);

                    $reportDate= date("Y-m-d", $d);
                    $data['TotalBilled'] = $row[5];
                    $data['TotalCollected'] = $row[6];
                     
                    //Here, You can insert data into database. 
                    print_r($data);
                            
                    $sql = "INSERT INTO `reports`(`ProgramCode`, `ClientID`, `PolicyNo`, `InsuredName`, `ReportDate`, `TotalBilled`, `TotalCollected`)
                    VALUES ('$row[0]','$row[1]','$row[2]','$row[3]','$reportDate','$row[5]','$row[6]')";

                    if ($conn->query($sql) === TRUE) {
                        echo $sql;
                        echo "New record created successfully";
                    } else {
                        echo "Error: " . $sql . "<br>" . $conn->error;
                    }
                     
                }
                $count++;
            }
        }
 
        // Close excel file
        $reader->close();
 
    } else {
 
        echo "Please Select Valid Excel File";
    }
 In localhost its working fine except date. but in server its showing nothing i mean empty page. like below:

![screencapture-projects-techyodha-liz-dashboard-uploadexceldata-uploadexcelsheet-php-1512822583763](https://user-images.githubusercontent.com/20263854/33795617-ddca3a38-dd0a-11e7-96e5-ed6cac2d8c70.png)

} 
?>

**Comment by adrilo** [comment]
If you want to get the dates as strings, you need to configure that before reading your file. Otherwise Spout returns a `DateTime` object (and calling `strtotime()` on such an object won't do anything good).
```
$reader = ReaderFactory::create(Type::XLSX);
$reader->setShouldFormatDates(true);
```

In your code, I see that you also want to support XLS files. Spout does not support XLS files, only XLSX, so you should probably change that.
Now for why it does not work on your server, I would check if it actually goes into the `if` statements that you have. Maybe the path to the file is not correct?
