### ISSUE TITLE
Usage of ressource

### ISSUE THREAD

**Issue by Ngob** [box/spout#527]
Hello,

I am new in the usage of Spout, and I would like to know if writing this is possible:

```
 $fd = fopen("php://temp", "w");
$writer = WriterFactory::create(Type::CSV);
 $writer->openToRessource($fd);
// Playing with writer
$writer->close();
// Doing something with $fd
```
This way I would be able to play with spout using Psr 7, using [zend-diactoros](https://github.com/zendframework/zend-diactoros). In this case, I think the lib should not close the ressource:
```
 $fd = fopen("php://temp", "w");
$writer = WriterFactory::create(Type::CSV);
 $writer->openToRessource($fd);
// Playing with writer
$writer->close();
return new Response(new Stream($fd), 200, [
            "Content-Type" => "application/octet-stream",
            "Content-Transfer-Encoding" => "Binary",
            "Content-disposition" => "attachment"
        ]);
```
Maybe I am missing something?
Thanks for your work!

**Comment by adrilo** [comment]
Hi @Ngob,

The `Writer::openToFile()` function should support PHP streams. So you should be able to do `$writer->openToFile('php://temp');`.
Now this does not return the resource handle so you won't be able to use it the way you described. However, for CSV files, Spout does stream data to the given resource so you may be able to work around your problem.

Another example you can look at: http://opensource.box.com/spout/guides/symfony-stream-content-large-spreadsheet/
This deals with reading instead of writing but that may be helpful.

**Comment by Ngob** [comment]
Hello @adrilo,
Thanks for your fast response.
I probably missunderstand something:
  - I did not find the way to get the content of `php://temp` without using the opened ressource. All usage I found of `php://temp` specify something like this:
```
$fiveMBs = 5 * 1024 * 1024;
$fp = fopen("php://temp/maxmemory:$fiveMBs", 'r+');

fputs($fp, "hello\n");

// Lit ce que nous venons d'écrire.
rewind($fp);
echo stream_get_contents($fp);
```
 - In your example, you specify the way to create a StreamedResponse from a reading, but i cannot control the way the lib write. Maybe i missunderstand how to apply the read's example to a write's case? 

In the wait of a solution I ended by doing something dirty for my taste:
```

        $writer = WriterFactory::create(Type::CSV);
        $h = fopen("php://temp", "w");
        ob_start(function($data) use ($h) {
            fputs($h, $data);
            return "";
        }, 1048576);
        $writer->openToFile("php://output");
       // Play with writer
        ob_flush();
        return new Response(new Stream($h), 200, [
            "Content-Type" => "application/octet-stream",
            "Content-Transfer-Encoding" => "Binary",
            "Content-disposition" => "attachment"
        ]);
```

Thanks for your help.

**Comment by adrilo** [comment]
Actually, can you give more details about what you're trying to accomplish? I'm not sure I really understood... We can start from there and see if we can find a solution

**Comment by Ngob** [comment]
Hello again,
I am generating a XLS/CSV file and I have no need in storing the file. I just need to send the generated file to the browser. I try to achieve this and to stay PSR-7 compilant (so using openToBrowser directly is not possible, because this is not PSR-7 compilant).
Using SPOUT, I can see 3 ways:
- Write and read the file (using the writer then the reader)
- Generate a temporary file and send it to the browser directly (and remove it later)
- Use my previous code

Thanks for your help.

**Comment by adrilo** [comment]
Ok, so you basically want to stream the data to a resource you have access to. More or less what `openToBrowser` does but you don't have access to the resource it uses.
- Write and read seems overcomplicated and very inefficient, as all you really need is writing.
- Generate a temp file and send it to the browser: same inefficiencies as above.

Something you can try is this:
```
$h = fopen('php://output', 'r');
...
$writer->openToBrowser($fileName);
...
echo stream_get_contents($h); // contains what's being outputted by Spout
```

Also note that streaming will only work with CSV files, as XLSX files need to be completely generated before you can send it to the client.

**Comment by Ngob** [comment]
Hello,
Thanks again for your response.

I tryed something like this:

```
$h = fopen("php://output", "r");
$writer->openToBrowser("foobaz.csv");
$writer->addRow(['foo', 'bar']);
$writer->close();
error_log(\stream_get_contents($h));exit;
```
But nothing is displayed in the file of my error's log. Something is displayed by the browser but it is probably the outputting from the lib. Basically I need the lib to let me handle the output. In my case, output should be handled by my framework. I think in Symfony you have something similar. 

Thanks again for your help.

**Comment by adrilo** [comment]
I see. There's nothing built-in to do that. So your best option would be to use the `ob_*` functions, like you did earlier.
Or to be honest, since you won't be able to do the same thing with XLSX file, you can simply use the built-in PHP functions. No need to use Spout in this case.
