### ISSUE TITLE
Excel writing is very slow

### ISSUE THREAD

**Issue by Tonix-Tuft** [box/spout#531]
Hi,

I tried to use Spout in a project, but I do not why it is really slow while writing an Excel file...

So I searched online and I found that someone has created a repo (https://github.com/adrilo/spout-pdo-example) where they benchmark Spout's performances and I do not know why on my computer the Excel writing is so slow.

This is how Spout should perform when writing an Excel of 50.000 rows:
![screen shot 2018-01-26 at 15 16 22](https://user-images.githubusercontent.com/10134421/35443609-06889cfa-02ac-11e8-889d-1524959a387c.png)

On my computer when I run the example, it usually takes at least 90 seconds (below an output of the program):

Fetch mode: batch
Elapsed time: 95.23s
Memory peak: 2MB

I use PHP 7, Spout v2.1.0 . What could be the problem?

Thank you for your attention.

**Comment by adrilo** [comment]
Closing. See referenced issue here: https://github.com/adrilo/spout-pdo-example/issues/2
