### ISSUE TITLE
Exclude 1-2 rows from import

### ISSUE THREAD

**Issue by akuchkovsky** [box/spout#533]
Hi!
Can i exclude 1 first row from .xls import on the settings/ReaderOptions?
Need exclude this document header: 
```NAME LAST_NAME EMAIL....```

Some like this:
```$reader->setExcludeRow(1);```

![2018-02-02_17 55 26](https://user-images.githubusercontent.com/1108013/35729793-69f4f05e-0842-11e8-827a-bba4f47e234a.png)

**Comment by adrilo** [comment]
When you loop through all the rows, you can retrieve the row index. You can then exclude rows this way:
```
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $rowIndex => $row) {
        if ($rowIndex === 1) {
            continue;
        }
        // do something
    }
}
```

**Comment by akuchkovsky** [comment]
This is understandable, but inconvenient, it is convenient to do so set all Import  settings in one style
```
$reader->setFieldDelimiter('|');
$reader->setFieldEnclosure('@');
$reader->setEndOfLineCharacter("\r");
$reader->setEncoding('UTF-16LE');
$reader->setExcludeRows(2);
```
Ok, thank you!
