### ISSUE TITLE
Support objects with __toString() method in ODS and Excel Writers

### ISSUE THREAD

**Issue by delboy1978uk** [box/spout#537]
It works fine with the CSV one, but i think it would be nice if we could check if an object has a `__toString()` method before throwing an exception.

```php
protected function getCellXML($cellValue, $styleIndex, $numTimesValueRepeated)
    {
        $data = '<table:table-cell table:style-name="ce' . $styleIndex . '"';

        if ($numTimesValueRepeated !== 1) {
            $data .= ' table:number-columns-repeated="' . $numTimesValueRepeated . '"';
        }

        if (CellHelper::isNonEmptyString($cellValue)) {
            $data .= ' office:value-type="string" calcext:value-type="string">';

            $cellValueLines = explode("\n", $cellValue);
            foreach ($cellValueLines as $cellValueLine) {
                $data .= '<text:p>' . $this->stringsEscaper->escape($cellValueLine) . '</text:p>';
            }

            $data .= '</table:table-cell>';
        } else if (CellHelper::isBoolean($cellValue)) {
            $data .= ' office:value-type="boolean" calcext:value-type="boolean" office:boolean-value="' . $cellValue . '">';
            $data .= '<text:p>' . $cellValue . '</text:p>';
            $data .= '</table:table-cell>';
        } else if (CellHelper::isNumeric($cellValue)) {
            $data .= ' office:value-type="float" calcext:value-type="float" office:value="' . $cellValue . '">';
            $data .= '<text:p>' . $cellValue . '</text:p>';
            $data .= '</table:table-cell>';
        } else if (empty($cellValue)) {
            $data .= '/>';
        } else {
            throw new InvalidArgumentException('Trying to add a value with an unsupported type: ' . gettype($cellValue));
        }

        return $data;
    }
```

**Comment by adrilo** [comment]
Checking a `__toString()` method is too magic... While it may be what we want in some cases, in others it can lead to unwanted behavior.
Imagine if you have an object, exposing a `__toString` function, used for debugging purpose. You probably don't want Spout to use that. I'd rather have the developer make the transformation herself before giving the data to Spout.

**Comment by delboy1978uk** [comment]
I don't think this will harm anything. The alternative is the current behaviour of throwing an exception. So anyone passing an object in will get failure, meaning currently everyone is already transforming their data. My PR specifically checks for the function, so it's not actually being magic. It just means we can pass objects and still succeed. My last point is that the CSV writer is casting objects using `__toString()` magically as it is.

**Comment by adrilo** [comment]
Having such a behavior for CSV file may make sense, as there's no type involved. However XLSX and ODS files do have types (string, int, etc.). I believe that the choice to convert every object to a string should be left to whoever is calling Spout. Assuming that an object always end up as a string is not a good assumption IMO. Throwing an exception is a way to enforce this implicit contract.

Also, "magic" was not the good term...

**Comment by delboy1978uk** [comment]
Fair point @adrilo. However, if the dev wanted/needed something other than a string, they would have to transform their object anyway, otherwise they'd just get the exception. So I don't think it's such a bad idea. A step beyond could be to check the column type is indeed a string.

**Comment by adrilo** [comment]
> if the dev wanted/needed something other than a string, they would have to transform their object anyway
I think this is idealistic. Some developers may not control their input thoroughly, do a first version that works well because only valid data types are passed but as the app evolves (and because of the lack of type safety in PHP), some objects may be sent as input. In this case, I'd rather have Spout fail explicitly rather than falling back to a behavior that may not be the expected one. In other words, I don't want Spout to be responsible for taking this decision, as it can lead to silent errors (and those are the worse!!).
