### ISSUE TITLE
IOException, failed to open stream: operation failed

### ISSUE THREAD

**Issue by amitgaur208** [box/spout#540]
I keep on getting this error?, why??
I wrote exactly as in the document...

Not working with latest version
Spout: 2.7.3
PHP: 7.1.14

I also tried downgrading Spout to 2.4.4 but still not working. Also i tried  libxml_disable_entity_loader(false);

**Comment by amitgaur208** [comment]
I really need to solve this @adrilo 

Please help me in this .

**Comment by amitgaur208** [comment]
No one is providing support on this plugin. I have to remove this now.

Thanks

**Comment by adrilo** [comment]
Hey @amitgaur208,

There may be many reasons for an IOException to occur. If you could copy/paste the exact error message in here, that'd be helpful. Also, are you trying to read or write a file?

**Comment by amitgaur208** [comment]
@adrilo This is same error as updated earlier

Could not open D:\xampp\tmp\php216F.tmp for reading! (Could not open D:\xampp\tmp\php216F.tmp for reading.) Box\Spout\Common\Exception\IOException

Please help me in this with latest version as mentioned above.
Spout: 2.7.3
PHP: 7.1.14

**Comment by adrilo** [comment]
Well this looks like a permission issue. Spout does not seem to have access to this file: `D:\xampp\tmp\php216F.tmp`.
If you're uploading the file first and try to use the value returned by PHP as the path, it's wrong. You need to use `move_uploaded_file()` to actually copy the uploaded file to a local folder. Only then, you'll be able to give this path to Spout.

**Comment by amitgaur208** [comment]
So this is the limitation with spout, let me try with exact path.

**Comment by amitgaur208** [comment]
So this is the **limitation** with spout, let me try with exact path.
