### ISSUE TITLE
undefined method Box\Spout\Writer\CSV\Writer::setTempFolder()

### ISSUE THREAD

**Issue by sarvap-praharanayuthan** [box/spout#541]
Tested using Composer installation as well as downloaded 2.7.3 from releases.

Code:

```
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Common\Type;
$writer = WriterFactory::create(Type::CSV);
$writer->setTempFolder(FCPATH . "export/garage");
$writer->openToFile(FCPATH . $path);
$writer->addRows($result);
```

Error:

> An uncaught Exception was encountered
> Type: Error
> Message: Call to undefined method Box\Spout\Writer\CSV\Writer::setTempFolder()

When executed without the line, `$writer->setTempFolder(FCPATH . "export/garage");` the CSV file is properly generated as stored. The folder `export\garage` exists with proper writable permissions.

Also the IDE warns about the method does not exists.
![settempfolder-dne](https://user-images.githubusercontent.com/5775590/37552441-63417b82-29db-11e8-87ea-b4cc63d948ea.jpg)

**Comment by madflow** [comment]
The CSV Writer does not need a temp directory. I would argue that it is a good thing that it is missing.

**Comment by camlafit** [comment]
Hello

I found this issue could be interessting to provide a neutral method on CSV Writer. With this could be possible to manage same code without need to know what writer is used.

Thanks
