### ISSUE TITLE
Date/Time formatting

### ISSUE THREAD

**Issue by milan-zelenka** [box/spout#544]
Hi,
I came across this feature and found out that calling the method with the boolean argument gives **opposite result**. Meaning:
$reader->setShouldFormatDates(false); // Formatting is enabled
$reader->setShouldFormatDates(true); // Formatting is disabled

This misinterpretation is also documented [here](http://opensource.box.com/spout/docs/#datetime-formatting).

**Comment by adrilo** [comment]
Hi !

This test seems to indicate that the documented behavior is correct: https://github.com/box/spout/blob/6d44cd26cc49c0fd59ffc01a4c187223c4b183cc/tests/Spout/Reader/XLSX/ReaderTest.php#L300

Can you double check and provide an example if you still find it's incorrect ?

**Comment by rps-repo** [comment]
Looking at the source:

`return ($this->shouldFormatDates) ? $nodeValue : new \DateTime($nodeValue);`

So if it is set to true then formatting should be disabled.  I agree with OP that this method is confusing.  Most people would think that setting false to a method named setShouldFormatDates would disable the formatting.

**Comment by adrilo** [comment]
I think there's a misunderstanding about what "formatting" means. To me, "formatting" transforms an entity into a readable string. So in this case, if formatting is turned on, Spout will returned a readable date (04/04/2018 for instance), as opposed to a raw/non formatted `DateTime` object.

BTW that's exactly what the [DateTime::format](http://php.net/manual/en/datetime.format.php) does :)

**Comment by rps-repo** [comment]
That is not how it works, at least not for me.  If nothing is set a DateTime object is returned by default.  
The default being:
`$reader->setShouldFormatDates(false);`

If I want the cell value left as is (no DateTime object) I would have to do:
`$reader->setShouldFormatDates(true);`

I think most people will be confused by this.

**Comment by madflow** [comment]
@adrilo To be honest - I did not have the use case yet.  I do not have problems with documented breaking changes though.  From my experience in the spreadsheet world I always found  dates to be a "hard" subject. Depending on the users OS and locale they would yield different  WYSIWYG results. So I did a quick test:

With a single Cell I got the same result from ```ODS``` and ```XLSX```:

```BASH
array(1) {
  [0] =>
  class DateTime#38 (3) {
    public $date =>
    string(26) "2020-12-13 00:00:00.000000"
    public $timezone_type =>
    int(3)
    public $timezone =>
    string(13) "Europe/Berlin"
  }
}
```

With ```->setShouldFormatDates(true);``` I get different results:

```BASH
//ODS
array(1) {
  [0] =>
  string(26) "Sonntag, 13. Dezember 2020"
}
//XLSX
array(1) {
  [0] =>
  string(25) "Sunday, 13/ December 2020"
}
```

Maybe this is a LibreOffice artifact...?

I know that this is not really the "problem" described in this issue: But I guess would rather have always the same DateTime object as default then. That said: I do not deal with dates that often with our Spout setup - when the first person tries to import dates I will probably change my mind ;)

**Comment by adrilo** [comment]
The issue you're describing is probably a discrepancy in how Excel and Libre Office handle language/region settings. Is the value returned by Spout what you see when opened in the different software?

**Comment by madflow** [comment]
I do not own an Excel License - So this is not that easy to test for me. I attached the files I used. I created and "ODS" with LibreOffice and saved it as ".xlsx" afterwards.

[date.xlsx](https://github.com/box/spout/files/1914203/date.xlsx)
[date.ods.zip](https://github.com/box/spout/files/1914205/date.ods.zip)

Maybe this should be separate Issue - I did not want to hijack your discussion with my findings.

**Comment by adrilo** [comment]
In your files, the values stored are different.
In ODS:
```
<table:table-cell calcext:value-type="date" office:date-value="2020-12-13" office:value-type="date">
	<text:p>Sonntag, 13. Dezember 2020</text:p>
</table:table-cell>
```

In XLSX:
```
<c r="A1" s="1" t="n">
	<v>44178</v>
</c>
...
<numFmt formatCode="DDDD, D/\ MMMM\ YYYY" numFmtId="165"/>
```

So having different values is the normal behavior :)

Now, the question is: is that better to return the formatted value as is, or should we return the date as a `DateTime` object. I'm now more inclined in the former option, as proposed by @rps-repo.

There are things I have against it:
- it may cause issues during a non thorough migration from v2 to v3
- on a performance level, the non optimal behavior (since you need to read styles XML file) is now the default behavior

I believe these points are ok, and unless someone has other arguments against it, I'll make the change.

**Comment by madflow** [comment]
> So having different values is the normal behavior :)

True - but it is different from what I see in Libreoffice. The display in the speadsheet software is the same - but not in the parsed Spout output. My point here: It is not really WYSIWYG but WYSIWYS(ometimes)G

> I believe these points are ok, and unless someone has other arguments against it, I'll make the change.

I am O.K. with this - since I only have to change on option to change it :D

**Comment by adrilo** [comment]
@cdmathukiya can you please create another issue? Yours seems unrelated to this specific issue's topic. Also, can you please share a file I could reproduce your issue with?

**Comment by adrilo** [comment]
I'll leave the current behavior as is, following the PHP naming (DateTime::format). As long as the behavior is described in the documentation, we should be good. It's also a perf improvement, as having `DateTime` objects by default avoid costly reference checks in other files.

**Comment by abiusx** [comment]
This wasted 30 minutes of my time too :)
