### ISSUE TITLE
CSV Writer add quotes for all values

### ISSUE THREAD

**Issue by rps-repo** [box/spout#545]
I have requirement that all values be double quoted in a csv file that I am generating.  Is there anything I can set to make this happen?  
A line would look something like:
"01","VIS","222","S","","SABRIX - US"

**Comment by adrilo** [comment]
Hi ! Unfortunately, it's not possible to force quotes on values that don't need it. Spout is using the built-in PHP functions and therefore follows its implementation.
If you want to achieve that, you'll have to fork Spout or use another library. Sorry...
