### ISSUE TITLE
v3 - Roadmap

### ISSUE THREAD

**Issue by oytuntez** [box/spout#546]
Hi there,

We needed `Sheet::isVisible()` method in `develop_3.0` branch, so we switched to it and so far it runs fine. Yet this is an exception and we feel insecure using this develop branch.

Do you have a roadmap for v3 release?

Thank you!

**Comment by adrilo** [comment]
Hi !

I'm trying to tag remaining issues with the correct milestone. You can see them here: https://github.com/box/spout/milestone/1

What's not in there is a review of the new APIs, to make sure the interface is still discoverable and easy to use, as well as an internal refactor of the Writers part (the Readers part is done).

If what you need is a release date, I can't unfortunately give you one. It really depends on the availability of the people contributing to this project.
However, the `isVisible` method won't go away :) So if you're scared about upcoming breaking changes (there might be), feel free to use the current commit hash of the `develop_3.0` branch. This way your code won't break if we introduce breaking changes. And once v3 is out, you can finish the transition :)

**Comment by oytuntez** [comment]
Sounds good to me, @adrilo! I just wanted to get a feel of what you had in mind. Thank you <3
