### ISSUE TITLE
why addRows is not faster than addRow

### ISSUE THREAD

**Issue by anylzer** [box/spout#551]
I do some test about spout's addRows with addRow,20w cell for writer,
addRows was not faster than addRow, why?

README is miss some examples ...

otherwise  how about PhpSpreadShee? who is the best choice?

**Comment by adrilo** [comment]
`addRows` is just a wrapper around `addRow`. Calling `addRow` 20 times or `addRows` once with 20 rows data is exactly the same. There are no perf gains calling one VS the other.

The README has a link to the actual documentation. You probably missed it. http://opensource.box.com/spout/

Regarding PhpSpreadSheet, it is a great library, lots of features. But Spout is way better in terms of speed and memory consumption. You can easily get OutOfMemory errors with PhpSpreadSheet (and make your program crash) if your spreadsheet is large. Also, performance decreases with the size of the spreadsheet. These 2 problems don't exist with Spout. You have linear performance and fixed memory consumption: that means that it will always take the same amount of time to read/write data and will not take more than 3MB of memory to perform any operation, even if your spreadsheet has millions of rows.
