### ISSUE TITLE
 htmlspecialchars():charset `AL32UTF8' not supported with Spout 

### ISSUE THREAD

**Issue by Harshanika** [box/spout#552]
I have implemented the Spout library in my project. It has built on the ZF2 framework and PHP version is 
5.6 +. The Spout has used to write on the ".csv" and ".xlsx" files there.  CSV is working successfully and Xlsx gives an error. 

In there the database has implemented on Oracle enviroment . So 'AL32UTF8' has set as the default charset when connecting to the database. After getting the data from the database and then it going to write on the xlsx .It gives below error . I have add code snippet below .

code change -

                $writer = WriterFactory::create(Type::XLSX);
                $writer->setTempFolder(sys_get_temp_dir(),'temp' );

                $writer->openToFile($excelSavePath);

                $writer->addRow($excelHeaderColumn);

                foreach ($fileWriteDataArray AS $reportObj) {
                    $writer->addRow($reportObj);  // add multiple rows at a time
                }
                $writer->close();

db configuration -

'db' => array(
 'driver' => 'Oci8',
        'connection' => '192.168.*.***:1521/1521', // Name of conenction in tnsnames.ora
        'username' => '', // Username to access db
        'password' => '', // Password to access db
        **'character_set' => 'AL32UTF8',**
        'platform_options' => array('quote_identifiers' => false)
)           

error given -
![spoutxlsxerror1](https://user-images.githubusercontent.com/15604113/39829281-97b0b4e4-53db-11e8-9308-a0bc51007aaf.png)

**Comment by adrilo** [comment]
Hi !

Can you try modifying this line: https://github.com/box/spout/blob/master/src/Spout/Common/Escaper/XLSX.php#L47
Replace it with: `$escapedString = htmlspecialchars($escapedString, ENT_NOQUOTES, 'UTF-8');`

Please let me know if that helps. If it does, I'll make the change.

**Comment by Harshanika** [comment]
Hi,

Many thanks for your reply.
Actually, I have done that change in my local library and then it worked successfully. 
I have attached the screenshot below.

Is it legal?
That means we get the library and do changes on that library?
![spoutcharset2](https://user-images.githubusercontent.com/15604113/39832615-4a9ec498-53e5-11e8-9839-fde2a525d476.png)

**Comment by adrilo** [comment]
No that's not how you should do it but that's a working workaround until the fix gets merged in the library and a new version gets released.

I'm gonna make the change in Spout asap

**Comment by Harshanika** [comment]
Hi,
Many thanks for your support and time.
