### ISSUE TITLE
inputEOLDelimiter doesn't work

### ISSUE THREAD

**Issue by eugenio11** [box/spout#560]
Hello,
is there any limitation for a custom inputEOLDelimiter ?

I've tried using a dot:
$delimiter = '.';
$reader->setEndOfLineCharacter($delimiter);

but it doesn't work, it seems it still expects a \n

Thanks.

**Comment by adrilo** [comment]
Hi ! Indeed, looking at the code it seems like this is broken. We changed the way CSV files are read to go back to the built-in `fgetcsv`, which does not support customizing EOL character.
However, we kept the API but the override is ignored...

In the next major release of Spout (3.0), we did remove this API. So unfortunately, no fix will be made for this. You'll have to stick with `\n` for your EOL.

Hopefully you can make it work.

**Comment by eugenio11** [comment]
ok, thanks for the info.
