### ISSUE TITLE
Unknown Character

### ISSUE THREAD

**Issue by anggaand123** [box/spout#562]
i just testing this library and i found output like this
how can i fix it ? any something miss ?

![alt text](https://image.ibb.co/kk7WCo/35114634_2122247167789983_9123568571832598528_n.png)

**Comment by adrilo** [comment]
Hi ! Can you please show us the code you use to read your file?
Also, if you could provide a copy (anonymized if needed) of your file so we can try to reproduce the issue, that'd be very helpful.

**Comment by anggaand123** [comment]
ops, sorry my bad i set the wrong extension .
Thanks !
