### ISSUE TITLE
[develop_3.0] Remove src/Spout/Reader/Common/ReaderOptions.php

### ISSUE THREAD

**Issue by madflow** [box/spout#563]
I am behind all the refactoring changes in 3.0. I was tinkering with "reader options" and I started to implement them in ```src/Spout/Reader/Common/ReaderOptions.php```

This class seems to be unused.

Should  ```src/Spout/Reader/Common/ReaderOptions.php``` be removed or are there any further plans ?

**Comment by adrilo** [comment]
Good catch! It's now using `OptionsManager`s. Feel free to delete the file :)
