### ISSUE TITLE
Set datatype to all cells in specific column and set encoding for xlsx file.

### ISSUE THREAD

**Issue by wooziie** [box/spout#567]
Hello, I have a challenge to set the third column to datatype number instead of the current text. 
But I can´t find any information on how to target columns like you can do with rows and through that possibly set datatypes for specific columns. 

I am also interested in finding out if there is a possibility to change encoding on my xlsx files. Right now I´ve tried $reader->setEncoding('UTF-8'); but the encoding on my xlsx files are still 'charset=binary'.

Is this possible with Spout? 

Best regards
Michael

**Comment by adrilo** [comment]
Hi Michael !

For now, it's impossible to set the cell type to something else than "general". Although, make sure to pass an actual number (123) not a stringified number ("123"), that may help.

Regarding the encoding, XLSX files are always encoded using UTF-8, you can't change that. When you say you see `charset=binary` I'm assuming you're talking about what's being sent by the browser? In this case, it's fine. A file is actually sent to the browser as binary, but the content of the file itself is UTF-8. Hope that makes sense.
