### ISSUE TITLE
Suggestion: Simple global number format :-)

### ISSUE THREAD

**Issue by archfrog** [box/spout#570]
I just begun using your package today but immediately ran into the already known issue that Spout doesn't support controlling the number format of the written cells (the current default is `Standard`, I believe).

It seems you have great ideas for how to add cell-based styling and so on, but I think many of us really only need to be able to change the global, hard-coded default of `Standard` into `Text` so that the various spreadsheets out there don't try to interpret the cell data in unfortunate ways.

Therefore, I was thinking that you could perhaps add a simple `setShouldUseTextFormat(bool $value)` method to the XLSX and ODS writers for now.  That way we could get around the problem that Excel likes to interpret strings as dates and numbers, when they are in fact pure text that shouldn't be interpreted unless somebody actively reformats a given column by specifying a cell format.

Cheers and thanks for your great project - it was just what I needed as I am regularly writing hundreds of thousands of lines to a single spreadsheet.  In fact, I'm only using your package to get around the problem that it takes a while to set up rows manually when importing a CSV file in Excel.

Cheers,
Archfrog

**Comment by adrilo** [comment]
Hi @archfrog,
Thanks for the feedback! It's always good to hear from users :)

I think what you're proposing is only part of the solution. By implementing the code to go from Standard to Text, we're almost done with the work of supporting any type. This means that only supporting `Text` is not ideal, given the amount of work involved. And vice-versa, given the amount of work needed, this is not an easy task and should be prioritized properly.
Unfortunately, for now our bandwidth is pretty low... but hopefully once the v3 is out, we will be able to iterate faster and add this feature.

**Comment by lingtalfi** [comment]
any update on this topic ? I like how spout is faster than PhpSpreadSheet, however I do need those Number formatting for writing...
