### ISSUE TITLE
Incorrect escaping used for Excel and ODS spreadsheet names

### ISSUE THREAD

**Issue by timhunt** [box/spout#576]
In Excel, "test" is a valid spreadsheet name, and this needs to be saved in workbook.xml as

    <sheets><sheet name="&quot;test&quot;" sheetId="1" r:id="rId1"/></sheets>

However, this library gets that wrong. That is, this comment: https://github.com/box/spout/blob/master/src/Spout/Common/Escaper/XLSX.php#L45 and the following code is incorrect.

Ditto for ODS.

I am about to make a pull request for this.

**Comment by timhunt** [comment]
This was found by Joost Elshoff in the context of Moodle (https://moodle.org/), which uses this library. See https://tracker.moodle.org/browse/MDL-62833 for the entry in our issue tracker.

**Comment by timhunt** [comment]
It seems that the ENT_NOQUOTES came from #411. I am not sure if it is safe to change back (I just fixed the unit tests to make them pass).

I hope that whoever reveiws this understands all the implications of the proposed change better than me. Thank you.

**Comment by adrilo** [comment]
Hi @timhunt! Thanks for submitting the issue and the PR.
I took another look at the changes that were made previously (#411) and the original problem (#409). Although I'd believe your changes would cause the original bug to re-appear, I was unable to reproduce the issue in my tests. So that's a go for me :)

**Comment by timhunt** [comment]
I had not found #409 before, but I have read it now. I don't think how values are escaped on output should affect how they are read (which is what 409 is about, if I understand). So, I still think my fix is correct, but you know more about Spout than me.

I have ameded the comments in the commit. I hope that is OK. If not, let me know and I will try agin.

Thanks, Tim.

**Comment by timhunt** [comment]
Any chance this could get reviewed again? Thanks.
