### ISSUE TITLE
XLSX Reader Removes Empty Rows

### ISSUE THREAD

**Issue by rps-repo** [box/spout#579]
When reading an excel spreadsheet the reader removes empty rows.  Is there a way to prevent that?

**Comment by madflow** [comment]
I believe 

https://github.com/box/spout/blob/799ad93d236d90f70d67b85b503a9f488eee15d8/src/Spout/Reader/AbstractReader.php#L91

should cover this.

Please close this issue - if this is what you are looking for. If not - we will go from there ;)

**Comment by rps-repo** [comment]
Thanks!
