### ISSUE TITLE
Add cell data formating as text, number format and date / datetime format insteal of general on xlsx writter

### ISSUE THREAD

**Issue by danielrusu** [box/spout#580]
Cast is not working. Data is still interpreted as general on excel export.

**Comment by adrilo** [comment]
When generating a spreadsheet, cells are always created with "general" type. Spout does not support setting a custom type.
When reading a spreadsheet, you can configure Spout to return a string or a `DateTime` object.

**Comment by suresh34ks** [comment]
Is any development done for generating cells with different type like currency / number?

**Comment by adrilo** [comment]
Unfortunately not.
