### ISSUE TITLE
add a column to an existing sheet

### ISSUE THREAD

**Issue by Romain-Moreaux** [box/spout#586]
Is there a way to add a column to an existing sheet?
If so, what is the name of the method?

Thanks for any help I'll receive.

**Comment by madflow** [comment]
Hello! Take a look here: http://opensource.box.com/spout/guides/edit-existing-spreadsheet/

Please close this issue if this resolves your question.

**Comment by adrilo** [comment]
Indeed, there are no direct way of doing that. You need to read the entire spreadsheet, add the missing column for each row and write back that row. The process is explained in the link provided by @madflow

**Comment by Romain-Moreaux** [comment]
Hello thank for your concern. 
I will detail my need a bit so that you understand better.

1. take an input xlxs file.
2. read the data from a column to make api queries
3. add the api response data to a new column.
4. send this modified file output.

Do you think that possible with spout?

**Comment by adrilo** [comment]
Spout works better with rows, as data is stored row by row and not column by column.
If you need to read an entire column, you basically need to read the entire file and store your column values in memory. Then you can do your API queries. Finally you'll need to go through the file one more time, using the technique described in the doc (link from @madflow's comment).
The process is definitely not optimal but that's the only way to do it.
