### ISSUE TITLE
method setShouldFormatDates do not format properly

### ISSUE THREAD

**Issue by Romain-Moreaux** [box/spout#587]
Hi,

I'm using this `$reader->setShouldFormatDates(true);` but the debugger show me that `[1]=> object(DateTime)#38 (3) { ["date"]=> string(26) "2017-02-04 19:23:00.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(13) "Europe/Berlin" }`

the date object isn't formatted properly and the script output that issue `Fatal error: Uncaught Box\Spout\Common\Exception\InvalidArgumentException: Trying to add a value with an unsupported type: object in /Applications/MAMP/htdocs/idec-api/api/spout/src/Spout/Writer/XLSX/Internal/Worksheet.php:231 Stack trace: #0 /Applications/MAMP/htdocs/idec-api/api/spout/src/Spout/Writer/XLSX/Internal/Worksheet.php(188): Box\Spout\Writer\XLSX\Internal\Worksheet->getCellXML(2, 1, Object(DateTime), 0) #1 /Applications/MAMP/htdocs/idec-api/api/spout/src/Spout/Writer/XLSX/Internal/Worksheet.php(149): Box\Spout\Writer\XLSX\Internal\Worksheet->addNonEmptyRow(Array, Object(Box\Spout\Writer\Style\Style)) #2 /Applications/MAMP/htdocs/idec-api/api/spout/src/Spout/Writer/Common/Internal/AbstractWorkbook.php(170): Box\Spout\Writer\XLSX\Internal\Worksheet->addRow(Array, Object(Box\Spout\Writer\Style\Style)) #3 /Applications/MAMP/htdocs/idec-api/api/spout/src/Spout/Writer/XLSX/Writer.php(105): Box\Spout\Writer\Common\Internal\AbstractWorkbook->addRowToCurrentWorksheet(Array, Object(Box\Spout\Writer\Style\Style)) #4 /App in /Applications/MAMP/htdocs/idec-api/api/spout/src/Spout/Writer/XLSX/Internal/Worksheet.php on line 231`

Any idea ?

**Comment by adrilo** [comment]
Hi @Romain-Moreaux,
Can you please share the code you're using? And if possible a file where I can reproduce the issue.
Thanks!

**Comment by adrilo** [comment]
Hi,
It's not explicit because the check was somehow removed during a previous refactoring but you need to call `setShouldFormatDate(true)` **before** calling the `$reader->open`.
You can get rid of your workaround and just move your `set` one line above :)

**Comment by Romain-Moreaux** [comment]
Ho, i will try it asap.

my bad if it works :)
