### ISSUE TITLE
Design Icon/Logo

### ISSUE THREAD

**Issue by gcarlosr** [box/spout#589]
Hi, my name is Carlos, I'm a graphic designer and I like to make contributions to open source applications without any commitment. I have seen that you have a quite interesting application but it does not have an icon or logo that represents or identifies it, let me know if you would like to receive a contribution from me in this area. Thanks in advance and apologies for opening this issue.

**Comment by adrilo** [comment]
Hi @gcarlosr, we do have a logo already: https://github.com/box/spout/blob/master/logo.png
