### ISSUE TITLE
Feature Request (style cells, default cell style & freeze pane)

### ISSUE THREAD

**Issue by pop-mihai** [box/spout#590]
It would be nice if this library would eventually offer:
- Ability to style individual Cells within a row. 
- Ability to define a default style
- Ability to freeze panes.

**Comment by adrilo** [comment]
Hi @pop-mihai, thanks for the suggestions.

> Ability to style individual Cells within a row

This is already implemented in the v3 (not released yet)

> Ability to define a default style

You can already do this by calling `setDefaultRowStyle` on your writer (before opening it)

> Ability to freeze panes

This is already on our todo list :)

**Comment by pop-mihai** [comment]
Thank you for the feedback @adrilo. Two more questions please: 

1. https://github.com/box/spout/issues/373 < is there anything in the v3 milestone addressing this ?
We did some more investigation and it seams more related to libxml, we are running PHP 7.2.7 with libxml 2.9.1. Growing to over 500MB of RAM for the sample file we have shared is too much.

2. Any future plans to implement a XLS Reader as well ?

**Comment by adrilo** [comment]
1. There's nothing addressing that at the moment. But if you have clues, feel free to get involved :)
2. There will never be a XLS Reader. The format is very old and is a nightmare to support.
