### ISSUE TITLE
External links

### ISSUE THREAD

**Issue by ulasarican** [box/spout#591]
Hi, 
is there a hack for adding external links for cell contents (hyperlinks, hrefs, <a> tags) ?

**For example;**
```
$data[] = array(
			'112',
			'<a href="xxxxxx.xxx">xxx</a>',
			$v['subscription_end_date'],
			$v['days_left'],
			$v['members'],
		);

$writer = WriterFactory::create(Type::XLSX);
$filename = "past_ ".date("d-m-Y_His").".xlsx";
$writer->openToFile($filename);
$writer->addRows($data["past"]);
$writer->close();
```
Thank you..

**Comment by adrilo** [comment]
As far as I know, you can't pass data in such a form so it's understood as an hyperlink. You can take a look at this PR though, it may help: https://github.com/box/spout/pull/352
