### ISSUE TITLE
PHP 5.6.XX 

### ISSUE THREAD

**Issue by muchtarramadhan** [box/spout#596]
When i running Spout in My xampp with php version 5.6.xx i have some error wheren i wanto to write to excelfile 

> This site can’t be reached The webpage at http://localhost/upload_mrs/export might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

and when i run in xampp with PHP 7.xx, the program run well.
this my code. thank u. best regard....

```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');
require_once APPPATH.'libraries/spout-2.7.3/src/Spout/Autoloader/autoload.php';

//definisikan class2 yg akan kamu gunakan dari Spout ini
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Common\Type;

class Export extends CI_Controller{

    function index(){
        $writer = WriterFactory::create(Type::XLSX); // for XLSX files
		//$writer = WriterFactory::create(Type::CSV); // for CSV files
		//$writer = WriterFactory::create(Type::ODS); // for ODS files

		$fileName='text.xlsx';
		//$writer->openToFile($filePath); // write data to a file or to a PHP stream
		$writer->openToBrowser($fileName); // stream data directly to the browser

		$singleRow =['header 1','header 2'];
		$writer->addRow($singleRow); // add a row at a time

		$multipleRows=[
			['data 1','data 2'],
			['data 3','data 4'],
		];
		$writer->addRows($multipleRows); // add multiple rows at a time

		$writer->close();
    }
}
```

**Comment by adrilo** [comment]
Hi @muchtarramadhan,
Unfortunately, this has nothing to do with Spout. The error comes from the setup of your webserver and I can't provide you any help here.

**Comment by muchtarramadhan** [comment]
Hi @adrilo now i can export, i change my xampp to AMPPS thank you sir
