### ISSUE TITLE
Could not open {tmp/file_path} for reading!

### ISSUE THREAD

**Issue by Chintan7027** [box/spout#597]
Hello,
I am getting following error when uploading .csv or xls.
Box \ Spout \ Common \ Exception \ IOException
Could not open /tmp/phpBLER4y for reading! (Could not open /tmp/phpBLER4y for reading.)

Or in windows
Box \ Spout \ Common \ Exception \ IOException
Could not open C:\wamp64\tmp\phpF037.tmp for reading! (Could not open C:\wamp64\tmp\phpF037.tmp for reading.)

However .xlsx file working fine for me.

Here is my code

```
$reader = $excel->load($request->file('students_file'));
            $students = [];
            foreach ($reader->sheets() as $sheet) {
                $header = $sheet->rows()->first();
                foreach ($sheet->rows() as $row) {
                    $temp = ["school_id" => auth()->user()->school_id];
                    foreach ($header as $cols) {

                        if ($cols == 'special_identification_number') {
                            $temp['internal_no'] = $row->$cols;
                        } else {
                            $temp[$cols] = $row->$cols;
                        }
                    }
                    $students[] = $temp;
                }
            }
```

Can you please help me to figure out this?

**Comment by Chintan7027** [comment]
> Hello,
> I am getting following error when uploading .csv or xls.
> Box \ Spout \ Common \ Exception \ IOException
> Could not open /tmp/phpBLER4y for reading! (Could not open /tmp/phpBLER4y for reading.)
> 
> Or in windows
> Box \ Spout \ Common \ Exception \ IOException
> Could not open C:\wamp64\tmp\phpF037.tmp for reading! (Could not open C:\wamp64\tmp\phpF037.tmp for reading.)
> 
> However .xlsx file working fine for me.
> 
> Here is my code
> 
> `$reader = $excel->load($request->file('students_file'));
> $students = [];
> foreach ($reader->sheets() as $sheet) {
> $header = $sheet->rows()->first();
> foreach ($sheet->rows() as $row) {
> $temp = ["school_id" => auth()->user()->school_id];
> foreach ($header as $cols) {
> 
> ```
>                     if ($cols == 'special_identification_number') {
>                         $temp['internal_no'] = $row->$cols;
>                     } else {
>                         $temp[$cols] = $row->$cols;
>                     }
>                 }
>                 $students[] = $temp;
>             }
>         }`
> ```
> Can you please help me to figure out this?

Even in full path specification:
Could not open C:\wamp64\www\exam\storage\StudentSample.xls for reading! 

PHP Version: 7.1.9

**Comment by adrilo** [comment]
Hi @Chintan7027,
If the file you're trying to read was uploaded through a form, you may need to use [move_uploaded_file](http://php.net/manual/en/function.move-uploaded-file.php) first. Regarding your comment on full path, you're trying to read a XLS file, not XLSX! Spout does not support XLS files that's why it complains.
Besides this, there's not much I can do to help. This is really a permission issue rather than a problem with the lib.
