### ISSUE TITLE
Excel Unique Cell Problem

### ISSUE THREAD

**Issue by ismail0234** [box/spout#599]
excel how do I increase the unique cells?
Excel 2003 Limit: 4.000
Excel 2007 Limit: 64000

**Comment by adrilo** [comment]
Can you please clarify your question?

**Comment by ismail0234** [comment]
@adrilo 

Unique cell formats/cell styles =>  64,000

https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3

how do I increase ?

**Comment by markosko** [comment]
You cant increase limit set by microsoft

**Comment by ismail0234** [comment]
@markosko  Is there any way?

**Comment by markosko** [comment]
No you can't exceed that limit thats why its limit
