### ISSUE TITLE
Floats are stored locale-aware

### ISSUE THREAD

**Issue by borys-p** [box/spout#601]
Hi,

I just got bitten by the problem described in #168, but mine is quite different. I was trying to store floats in the generated spreadsheet and kept getting errors. I started digging and discovered that floats in XML are stored in a locale-aware way. They are written as-is, but PHP can sometimes format them with a different decimal separator, other than a dot (eg. in Poland we are using a comma), if you start messing with `setlocale(LC_ALL, 'pl')`.

This results in: `<c r="C7" s="0"><v>3,5</v></c>`

If you manually change it to `<c r="C7" s="0"><v>3.5</v></c>` then Excel is happy and formats the value as a number.

The solution is quite simple, instead of doing:

```
} elseif ($cell->isNumeric()) {
        $cellXML .= '><v>' . $cell->getValue() . '</v></c>';
```

do

```
} elseif ($cell->isNumeric()) {
            $cellXML .= '><v>' . sprintf('%F', $cell->getValue()) . '</v></c>';
```

or even better

```
} elseif ($cell->isNumeric()) {
            $cellXML .= '><v>' . sprintf(\is_float($cell->getValue()) ? '%F' : '%d', $cell->getValue()) . '</v></c>';
```

or temporarily reset LC_ALL / LC_NUMERIC during the export.

I'm changing my code to use LC_TIME, because that's what I actually need right now, but you need to be aware of the unusual side-effects of locale for Spout.

**Comment by adrilo** [comment]
Well, Excel is locale aware as well. So it's hard to just force the locale in Spout. If your PHP locale is set to PL, it's likely that your computer locale is also set to PL and therefore Excel will use these settings to format data.
Do you know what other libs are doing? I'm not sure Spout should be responsible for that type of conversion.

**Comment by borys-p** [comment]
It seems that Excel is using the locale only to format numbers that are displayed. Internally they are stored with a dot (or at least that is being stored in the saved file).

In this case, Spout won't be doing a conversion, rather accessing the true value of a float (which is being converted by PHP on output).

[Other libraries](https://github.com/PHPOffice/PhpSpreadsheet/issues/226) have chosen to mark this issue as `wontfix` or [ignore altogether](https://github.com/PHPOffice/PHPExcel/issues/1107), although it's corrupting their files as well.

**Comment by adrilo** [comment]
Thanks for the additional info. I think there's probably something we can do here. Not sure what the best solution is yet, but I'll think about it.

**Comment by partulaj** [comment]
The issue was fixed in phpspreadsheet [here the fix](https://github.com/PHPOffice/PhpSpreadsheet/pull/1282/commits/d90ba7a615c381ce3f10f80996f3f0d052479d55) maybe it's possible to fix it in a similar way ?

**Comment by vukbgit** [comment]
I have locale set to it_IT (comma as decimal separator instead of dot) and could not find a solution to make numeric values (integer and float, queried from db and casted to integer and double by PHP) be rendered in an xlsx file correctly. I know that Excel displays numeric values according to locale setting but I wasn't aware that "_Internally they are stored with a dot_" as @borys-p writes. So I ended up forcing locale to en_GB before generating the file:

      $languageIETF = 'en_GB';
      putenv(sprintf('LC_ALL=%s', $languageIETF));
      setlocale(LC_ALL, sprintf('%s.utf8', $languageIETF));
      //get records form db
      ....
      //loop records
      array_walk(
        $records,
        function($item) {
          $item->integer_field = (int) $item->integer_field;
          $item->decimal_field = (double) $item->decimal_field;
        }
      );
      //generate xlsx file with the awesome spout writer
      ....

Now cells containing numeric values are formatted (Excel displays comma as decimal separator according to Italian locale) and behave (can be summed) as expected both in LibreOffice and Excel

**Comment by adrilo** [comment]
Thanks for your comment @vukbgit!
Out of curiosity, have you tried modifying Spout to do something like this? [`d90ba7a` (#1282)](https://github.com/PHPOffice/PhpSpreadsheet/pull/1282/commits/d90ba7a615c381ce3f10f80996f3f0d052479d55). You can make a quick fix here: https://github.com/box/spout/blob/91f756be0b0bf78f79f93a36ffdc240a5bf4099d/src/Spout/Writer/XLSX/Manager/WorksheetManager.php#L219

If that fixes the issue, we can make a proper fix.

**Comment by vukbgit** [comment]
I didn't want to mess with a packagist library, I tried now and it works:

in box/spout/src/Spout/Writer/XLSX/Manager/WorksheetManager.php:219

```
} elseif ($cell->isNumeric()) {
          $languageIETF = 'en_GB';
          putenv(sprintf('LC_ALL=%s', $languageIETF));
          setlocale(LC_ALL, sprintf('%s.utf8', $languageIETF));
          $cellXML .= '><v>' . $cell->getValue() . '</v></c>';
}
```
But I do not think it's a proper fix doing this for **every** cell with a numeric value, maybe it should be placed at the beginning of the writing process.
Besides, wouldn't a locale change have also side effects on the output of other kind of data (like dates)? Even if, in the context of a spreadsheet, I deem numbers should be the priority.
And finally, wouldn't it be nice, after file has been outputted, revert to the old locale, wisely stored at the beginning with somethinig like `list($previousLanguageIETF, $localeExtension) = explode('.', setlocale( LC_ALL, 0));` ?

**Comment by adrilo** [comment]
You're right for both the side effects with dates and reverting to the previous locale.
By any chance, have you tried the solution as implemented by PHPSpreadsheet and linked by @partulaj ?

It would be something like this (to be added here: https://github.com/box/spout/blob/91f756be0b0bf78f79f93a36ffdc240a5bf4099d/src/Spout/Writer/XLSX/Manager/WorksheetManager.php#L219):
```
} elseif ($cell->isNumeric()) {
    $cellValue = $cell->getValue();
    if (is_float($cellValue)) {
        $cellValueAsString = (string) $cellValue;
        // force point as decimal separator in case current locale uses comma
        $cellValue = str_replace(',', '.', $cellValueAsString);
        if (strpos($cellValueAsString, '.') === false) {
            $cellValueAsString = $cellValueAsString . '.0';
        }
        $cellValue = (float) $cellValueAsString;
    }

    $cellXML .= '><v>' . $cellValue . '</v></c>';
}
```

**Comment by vukbgit** [comment]
Comma and dot can be used for both decimal and thousand separator, I dug a bit in my old code and I found this gem:
```

str_replace(
  array(
    $locale["mon_decimal_point"],
    $locale["mon_thousands_sep"],
    "xxx",
    "yyy")
  ,array(
    "xxx",
    "yyy",
    ".",
    ""),
  $value);
```
where $locale comes from localeconv(). Not very elegant but it worked as far as I can remember.
To me, it does not seem better than switching locale

**Comment by adrilo** [comment]
Ah using `localeconv()` may be a good idea! Here I'd rather use `$locale['decimal_point']` and `$locale['thousands_sep']` instead of the monetary version.

So what you want to do is remove the thousands separator and force the decimal point to be a `.`.
I'm not sure what "xxx" and "yyy" are in your case, but adjusting what you wrote would give something like this:
```
} elseif ($cell->isNumeric()) {
    $cellValue = $cell->getValue();
    if (is_float($cellValue)) {
	    $cellValue = $str_replace(
	        [$locale['thousands_sep'], $locale['decimal_point']],
	        ['', '.'],
	        (string) $cellValue
	    );
        
        // not sure the if below is useful
        if (strpos($cellValueAsString, '.') === false) {
            $cellValue = $cellValue . '.0';
        }
    }
    $cellXML .= '><v>' . $cellValue . '</v></c>';
}
```

Want to give it a try?

**Comment by adrilo** [comment]
Thanks for trying that out!

Regarding your notes:
1. Yes, you still need to cast the source. When you have "2.34", who knows if you meant it to be a string or a float? Spout does not try to make the decision and therefore relies on the actual type. You're right, this can be added to the docs for better clarity.
2. Indeed, I don't expect the `localeconv()` value to change, so storing the 2 values we're interesting in is a no brainer. I did not mention it so that it would be easier to test.
3. Ok, thanks for the feedback!
