### ISSUE TITLE
Add support for resources or getting the file pointer

### ISSUE THREAD

**Issue by Qrokqt** [box/spout#603]
Ideally I'd like to be able to something like this:
```
$res = fopen('php://memory');
$writer->openResource($res);
```

but even just being able to do something like this:
```
$writer->openToFile('php://memory');
$res = $writer->filePointer;
```

would solve my problems.

**Comment by adrilo** [comment]
You can already do this: `$writer->openToFile('php://memory');`. However you can't pass a pointer nor retrieve the created pointer. We have no plans to add this to Spout, as it is considered internal behavior.

**Comment by Qrokqt** [comment]
The reason I'd like to get the file pointer is so that I could operate in memory and write from memory to an email attachment all without hitting the file system.

**Comment by adrilo** [comment]
Have you tried doing this: `$writer->openToFile('php://memory');` ?

**Comment by Qrokqt** [comment]
Sure, but then how do you get a reference to the stream where it was written?

**Comment by adrilo** [comment]
Ah indeed... then I'm sorry but you will have to use a temp file and write on disk

**Comment by fisharebest** [comment]
FYI, the [documentation](http://opensource.box.com/spout/getting-started/) still says:

```
$writer->openToFile($filePath); // write data to a file or to a PHP stream
```
