### ISSUE TITLE
How do i chunk records?

### ISSUE THREAD

**Issue by kalaiaccendo** [box/spout#609]
Hi,

Currently i have a single excel file which contains 13 sheets.
Each approximately contains 9000 records.
is there any way for me to chunk the records ?
Thanks

**Comment by unurbat** [comment]
i'm writing a excel file with 500k rows and 10 column. But the process exceed 2GB memory limit of PHP. is the chunk possible?

**Comment by adrilo** [comment]
@unurbat You're probably doing something wrong in your code. Spout is capable of writing as many rows as you want without consuming much memory (memory usage should be constant, not linear). Chunking won't help here...
Watch for places where you store the spreadsheet data in an array for instance. This is usually the culprit.
