### ISSUE TITLE
Cannot perform I/O operation outside of the base folder: C:\Windows\Temp  ...IOException(code: 0): Cannot perform I/O operation outside of the base folder: C:\\Windows\\Temp at ....vendor.../FileSystemHelper.php:130)

### ISSUE THREAD

**Issue by dextherry** [box/spout#610]
Hi, I am trying to generate and download an excel, but i got that error, what can I do in this situation?  
I read this [355](https://github.com/box/spout/issues/355), however updating php is not a solution for me, 

what folder is created? maybe I can add rights for write that folder, 

this is my code

`return (new FastExcel($list))->headerStyle($style)->download('file.xlsx');`

help please
Regards

**Comment by adrilo** [comment]
As stated in #355, Spout uses `get_temp_dir()` to get the path of the temp folder. Looks like on your server, it is configured to point at `C:\Windows\Temp`. You can try modifying the permissions of this folder.
Apart from that, there's not much we can do to help. Hopefully that will work for you.

**Comment by NoOorZ24** [comment]
Can't you just add function setTempDir() so I don't need to give permissions to "C:\Windows\Temp"?
Or if something like that exists is it in documentation?

**Comment by adrilo** [comment]
http://opensource.box.com/spout/docs/#using-custom-temporary-folder
