### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by madflow** [box/spout#611]
We are using the develop_3.0 branch for 6 months now in production. I have not seen a regression yet.

So... I would vote for a new release. I would appreciate more people using the new features and hence profit from bug reports, PRs and feature requests.

There is only one issue tagged with the 3.0 milestone https://github.com/box/spout/issues/544

This issue does not seem to be that "hard". So a perfect first PR. I actually do not need any changes regarding the date formatting - but maybe I just do not know it yet.

**Comment by elibyy** [comment]
Hey @madflow,
It's awesome to hear, could you provide with a change list/release notes?

Thanks
Eli

**Comment by madflow** [comment]
The code lives in: https://github.com/box/spout/tree/develop_3.0

The documentation is updated there and there is a "UPGRADE-3.0.md" document.

The release notes should follow - when there is an actual release I guess.

**Comment by adrilo** [comment]
And we're liiiiiive!!

**Comment by madflow** [comment]
@adrilo :1st_place_medal: Thank you! Also: Thank your for continously maintaining this repo, answering issues and patiently doing PR review. :+1:
