### ISSUE TITLE
Complete Ugrading to 3.0 guide

### ISSUE THREAD

**Issue by adrilo** [box/spout#614]
Before being able to release 3.0, we need to document what changed and how to upgrade to the new version.

**Comment by madflow** [comment]
What is missing in the existing upgrade guide? https://github.com/box/spout/blob/develop_3.0/UPGRADE-3.0.md

**Comment by adrilo** [comment]
Just had another look. This is very good stuff :)
It's just missing the part on the namespace move for `Style` (`Border`/`Color`...).

**Comment by rafaelqm** [comment]
There is something that is missing to change the 3.0 from dev to stable?
