### ISSUE TITLE
Update perf tests for v3.0

### ISSUE THREAD

**Issue by adrilo** [box/spout#616]

**Comment by madflow** [comment]
Would it make sense to incorporate these tests into the development branch? An additional branch seems superfluous - but maybe there is a reason I am not aware of to keep then in separate branch.

**Comment by adrilo** [comment]
The reason was to avoid committing the large spreadsheets (few MBs) I use in the tests. Although thinking about it now, this choice was done at the very beginning (and the files contained millions of rows not 300k). In the meantime, I created a `.gitattributes` that discards test resource files when importing Spout. So adding these files would only affect users cloning the project.
Anyway, I think that's a good suggestion and we can merge perf tests into the v3 branch :)
