### ISSUE TITLE
Read Cell As String

### ISSUE THREAD

**Issue by elior99** [box/spout#618]
Hey,
I have cell formatted as date but i'm interesting to read it as simple text, i haven't found a solution for this.
How can i do it?

Thanks

**Comment by adrilo** [comment]
You can use this option:
```
$reader = ReaderFactory::create(Type::XLSX);
$reader->setShouldFormatDates(true);
```

**Comment by elior99** [comment]
Hey,
I'm already using this option but it's convert the numbers to some date, and i want to get the actual numbers..as plain text..

**Comment by adrilo** [comment]
I see. Then I'm sorry this is not supported by Spout and we have no plans to add support for it.
