### ISSUE TITLE
Read Cell As String

### ISSUE THREAD

**Issue by elior99** [box/spout#621]
Hey,
I'm already using this option but it's convert the numbers to some date, and i want to get the actual numbers..as plain text..

_Originally posted by @elior99 in https://github.com/box/spout/issues/618#issuecomment-457938905_

**Comment by JTsToolbox** [comment]
I'm pretty sure it is because it is returning a Datetime Object. At least that's what I encountered. Maybe use var_dump($someresultingdate) to see if you're in the same boat.
