### ISSUE TITLE
[v3] Write performance XLSX

### ISSUE THREAD

**Issue by barryvdh** [box/spout#624]
When I do some quick manual test, the v3 branch seems a lot slower? Or am I missing something obvious? In a quick test (50.000 rows with 20 columns with 20 char strings), v2 is about 20 secs while v3 is 30 seconds. That is a 50% increase..

v2:
```php
$writer = WriterFactory::create(Type::XLSX);
$writer->openToFile('output/spout2.xlsx');
$writer->addRows($data);
$writer->close();
```

v3:
```php
$writer = WriterEntityFactory::createWriter(Type::XLSX);
$writer->openToFile('output/spout3.xlsx');
foreach ($data as $row) {
    $writer->addRow(WriterEntityFactory::createRowFromArray($row));
}
$writer->close();
```

Probably because you have to create `Row` objects for each row (which create `Cell` objects for each key)? So in this testcase 50.000 array_maps creating 1 million objects..

Edit: Full files here: https://gist.github.com/barryvdh/08576d8b8d7a8d171338737851e7ccf4

**Comment by barryvdh** [comment]
On a smaller set (10.000 rows with 20 cols) it takes about twice as long, so a 100% increase.

**Comment by barryvdh** [comment]
So am I testing wrong, or is this something we need to look into?

**Comment by madflow** [comment]
@barryvdh This is how I see it:

I do not think you are testing it wrong. `createRowFromArray` is a utility method to provide a similiar dev experience like in Spout v2 - creating rows from arrays with supported values.

In v2 this was pretty much fed directly to the writer - now in v3 it will create Cell/Row Objects from these values first. So there as many round trips in array_map as there are values in the array.

The preferred way of adding rows is described here: http://opensource.box.com/spout/getting-started/#writer

Basically: 

```PHP
$cells = [
    WriterEntityFactory::createCell('Carl'),
    WriterEntityFactory::createCell('is'),
    WriterEntityFactory::createCell('great!'),
];

/** add a row at a time */
$singleRow = WriterEntityFactory::createRow($cells);
$writer->addRow($singleRow);
```

In the first version of v3 there was not even such a method like `createRowFromArray`.


So I guess your options are:

* Refac your code not to use `createRowFromArray` 
* When you do not need Cell styling and you rely on the "pure" performance of adding rows from PHP arrays - stick with v2 for the moment.
* Work with us on solution for v3. Maybe we need some kind of _raw_ mode for adding PHP arrays like in v2...

**Comment by kierandelaney** [comment]
@madflow naive question - if creating a row from an array encapsulates the new behaviour but doesn’t actually give you much benefit other than allow you to minimise code rewriting, but at the cost of performance...

- could the row function be amended so that it checks what is passed to it driving the following behaviour
    - is array, old style raw writing
    - is row object, new style bells and whistles
- this means existing code ‘just works’ - you used to give it an array, it works like it did. This is desirable _in our use case_ which is dumping sheets quickly
- it means you can make use of the new functionality selectively on an upgrade, and in fact, in the future
- it means no further modes, switching etc are required

**Comment by kierandelaney** [comment]
Just to add, i’d be happy to work on something and submit a PR, the older performance was great and solved 95% of our uses already so, the new stuff is great for the final bit for us.

Happy either way, but I would prefer a steer before starting work on something 😬

**Comment by barryvdh** [comment]
Hmm, took a quick look but not really sure what the best way is. Each Cell is required to have a Style object, and those get merged with the row styling etc. So my feeling would say, that is a big part. But actually just creating the Row object from array is about 10% in my case, without writing them. So perhaps if the Cell styling was optional (eg. 1 style for the entire row, which would make the Style object optional in Cell objects, and doesn't require merging), would be better. But that's not an easy fix.

**Comment by adrilo** [comment]
That's not an easy fix indeed. Everything was re-written with cell styling in mind. I guess we need to do some kind of code profiling to see where the bottleneck is. Of course having encapsulating objects (Row/Cell) adds some complexity and therefore slowness but that might not be the best thing to optimize here. Given the time it would take to refactor what you discussed, I'd rather make sure first it's the correct thing to do. Eventually making some quick changes just to verify your theory would help.

**Comment by jmitchell38488** [comment]
To chime in here - write performance for files with only hundreds of rows, but hundreds of columns is pretty bad. For a file that has 150 rows, it needs to create 150 x 165 cells, approximately 25,000 objects (including the row wrappers). This is significantly worse when I need to produce files that are over 1,000 rows  - upwards of 200k objects, which doesn't provide many performance benefits over other libraries, while fundamentally providing less functionality for formatting and presentation.

Object creation in 7+ is a lot better than it used to be, but this is still a significant overhead.

>That's not an easy fix indeed. Everything was re-written with cell styling in mind. I guess we need to do some kind of code profiling to see where the bottleneck is.

It will be from the massive object tree that's created and the garbage collection, or lack thereof.

>Given the time it would take to refactor what you discussed 

A refactor effort wouldn't be needed, just an implementation of a `Raw` type of writer, which will write the cell values directly from the array without the styling; one could provide a default style option to be used on every cell.

**Comment by barryvdh** [comment]
You would still need to create the Row/Cell Objects, right? And the (current) Row implementation always create Style objects.
I think the CSV Write uses the same objects, so by comparing the v2 vs v3 performance for CSV we should be able to get a good idea about the bottlenecks about the actual objects, versus the bottlenecks in merging the style objects.

To avoid all the Style logic, it would perhaps be easiest to create a 'Raw' Writer / WorksheetManager. To avoid some of the object tree, the Style object could perhaps be made nullable and 1 default object be used, instead of creating the default object for each Cell.

**Comment by jmitchell38488** [comment]
@barryvdh given the code creates an array of objects, which have been decorated, then is sent through a parser than eventually an output writer, the end result is an XML string.

`File: Writer/XLSX/Manager/WorksheetManager.php`
```php
private function getCellXML($rowIndex, $cellNumber, Cell $cell, $styleId) {
    ...
    if ($cell->isString()) {
        $cellXML .= $this->getCellXMLFragmentForNonEmptyString($cell->getValue());
    } elseif ($cell->isBoolean()) {
        $cellXML .= ' t="b"><v>' . (int) ($cell->getValue()) . '</v></c>';
    } elseif ($cell->isNumeric()) {
        $cellXML .= '><v>' . $cell->getValue() . '</v></c>';
    } elseif ($cell->isEmpty()) {
        if ($this->styleManager->shouldApplyStyleOnEmptyCell($styleId)) {
            $cellXML .= '/>';
        } else {
            // don't write empty cells that do no need styling
            // NOTE: not appending to $cellXML is the right behavior!!
            $cellXML = '';
        }
    } else {
        throw new InvalidArgumentException('Trying to add a value with an unsupported type: ' . gettype($cell->getValue()));
    }
}
```

The `WorksheetManager` class builds the XML, the interface contract mandates that on `addRow`, a `Row` object is required.

I'd recommend that:
1. A contract/interface be created for the `Row` class, that's extended for the default Row class
1. A new row type be introduced for the Raw CSV style `Row`
1. A `RawWorksheetManager` class be introduced, that implements the XLSX `WorksheetManager` class, that overrides the writing functions.
1. The visibility for the functions that produce XML be changed to `protected`, or refactored to a specific output class that can be extended

There are fundamental extensibility issues with a class designed for managing the content and structure of a document, with output generation as well.

**Comment by svenpaulsen** [comment]
I also had to move back to the 2.7.3 release. After migrating my code, I noticed a significant increase in memory consumption. While exporting 30000 records with Spout 2.x was dead-simple and very very fast, doing the same with 3.x felt like back in the old days of PHPExcel...

When dealing with a two-dimensional array, it shouldn't be that hard. A new method like `createRowsFromArray` would be much appreciated instead of having to do this on a per-row basis.

**Comment by jmitchell38488** [comment]
@svenpaulsen it's just the side effect issue of PHP being a poorly optimised environment for OOP and object creation. Even with 7.3+, the poor performance exists.

**Comment by yennor** [comment]
I've just used spout the first time. Creating 10 columns with 10 000 row excel file was about 3 minutes with spout 3.1. 
And it was around 30 seconds with spout 2.7.3 (still slow, but magnitudes better).
(using basically the same code as the thread opener)

**Comment by alamirault** [comment]
> Hmm, took a quick look but not really sure what the best way is. Each Cell is required to have a Style object, and those get merged with the row styling etc. So my feeling would say, that is a big part. But actually just creating the Row object from array is about 10% in my case, without writing them. So perhaps if the Cell styling was optional (eg. 1 style for the entire row, which would make the Style object optional in Cell objects, and doesn't require merging), would be better. But that's not an easy fix.

I noticed the same problem on a big file to generate. Blackfire confirmed me that a half of time is used to merge Styles.
![image](https://user-images.githubusercontent.com/9253091/75919082-3016ee00-5e5d-11ea-8a62-b4e72aee1889.png)

I think I can work on this issue. Style is an optional parameter in constructor of `Cell` and `Row` but when `null` is given, an empty Style is instantiate.

 In order avoid BC, I suggest to allow `false` value for style parameter and manage this case in order to avoid merging. WDYT ?

**Comment by madflow** [comment]
@alamirault As far as I can recall: The empty Style is only there to make merging easier. If this yields a performance penalty, then I would applaud work on this :) I personally would not mix boolean/Style/null parameters to make this work - maybe this necessary - this could be discussed in a PR :+1:

**Comment by adrilo** [comment]
I agree with not mixing types. It's better to have two methods than having one accepting params with different types.

**Comment by SamMousa** [comment]
Adding an explicit empty style class `EmptyStyle` would allow for significantly optimizing style merging without introducing type ambiguity.

**Comment by SamMousa** [comment]
The style registry could also do with some serious optimization; it uses `serialize()` to generate unique keys for every style object.
Given that the number of styles is (most likely) a lot smaller than the number of cells it makes sense to store a reference to the default style so that for that case most of these things can be short circuited.

It takes > 50% off for me (35s to 16s).

**Comment by adamwinn** [comment]
So much for "Read and write spreadsheets quickly and at scale" like the Spout homepage says.  I'm just now seeing these v3 changes and have no idea how they were approved.  Reading and writing is tremendously slower now.  I'm also seeing styles are supported, along with pull requests for formulas, merging cells, cell height, etc.  I have no idea how something like `createRowsFromArray` was not implemented.  We had that same functionality with v2.  Spout is now turning into PHPExcel

**Comment by barryvdh** [comment]
@adamwinn It seems a PR is made in https://github.com/box/spout/pull/763 to improve performance. Have not tested this yet.

**Comment by adrilo** [comment]
@adamwinn You're kind of right. The previous version of Spout was really fast. I got so many people asking for more features (just take a look at the current issues) that I decided to take a stab at some of them. Adding an abstraction on top of cells/rows made a lot of sense, as it allowed us to do a lot more things. Unfortunately, this had a bad, unexpected impact on performance...
As @barryvdh mentioned, we're now trying to improve the perf of the current version. I'm refraining on adding new features, and instead prioritize processing speed (other PRs welcome!)

The goal is definitely not to be a PHPExcel clone (it's not possible anyway) but to balance speed and features.

Also note that `WriterEntityFactory::createRowFromArray($values);` does exist but you don't get any perf benefits as it just converts the array to a row/cells.

**Comment by adrilo** [comment]
Some great improvements discussed here were merged as part of https://github.com/box/spout/pull/763.
I'm going to close this related issue.

**Comment by barryvdh** [comment]
Thanks for the improvements!

**Comment by galenchisholm** [comment]
I am using the latest version and experiencing a major difference in performance with it vs v2. 

Do I have to do something for these supposed improvements to take affect?
I am making cells without passing in the style param, 
`$cells[] = WriterEntityFactory::createCell($value);`

and then I do
`$row = WriterEntityFactory::createRow($cells);
$writer->addRow($row);`

I also have this defaultRowStyle, but if I remove it I get the same performance.
`$rowStyle = (new StyleBuilder())
			->setShouldWrapText(FALSE)
			->build();
$writer->setDefaultRowStyle($rowStyle);`

25k rows, 5 columns. Its like 10 seconds on v2 and 20 seconds on the latest code. 

Am I doing something wrong here?

**Comment by adrilo** [comment]
Nothing wrong. V3 is faster than before but still slower than V2 unfortunately.

**Comment by galenchisholm** [comment]
I see, ok thank you. Still it is a useful library and ultimately was able to get the performance we needed out of it.

Thanks!

**Comment by barryvdh** [comment]
For absolute performance but probably less configurable/less styling, you could also try https://github.com/mk-j/PHP_XLSXWriter
