### ISSUE TITLE
Add methods to SheetInterface

### ISSUE THREAD

**Issue by Efiware** [box/spout#626]
Hi

As far I can tell, the only thing the files Sheet.php in XLSX/CVS/ODS have in common is the SheetInterface. I'm building a tool that should take a Sheet as input for further processing, no matter which file it is originating from. I'm defining input as of type SheetInterface. It would help a lot, if the following methods are defined in SheetInterface:

    public function getName()
    public function getIndex()
    public function isActive()

Is this possible?

**Comment by adrilo** [comment]
Indeed, that's a good idea. We can also add `isVisible()`.

**Comment by VincentChalnot** [comment]
:+1:
