### ISSUE TITLE
API Compatibility between CSV and XLSX

### ISSUE THREAD

**Issue by atrauzzi** [box/spout#629]
I'm just noticing now when trying to use an XLSX that while the API signatures are the same thanks to the common interfaces between the implementations, there are differences in behaviour when making calls.

I'm noticing strange errors at a level that I should think spout would abstract away from me:

> XMLReader::read(): Load Data before trying to read

So, while the call signatures are the same, it seems like there are still assumptions baked into the conventions of how the API is consumed.

**Comment by adrilo** [comment]
Hi @atrauzzi, can you be more specific? I'm not sure I get your exact point here.

**Comment by atrauzzi** [comment]
Yeah, so I was using code outside of a `foreach` to get the first row of my CSV via the `SheetIterator` implementation.

When I passed an XLSX to the same code that leverages the same abstraction, I received errors when attempting to use methods like `next` and `current`.

The code for the CSV worked fine, but simply changing the underlying implementation forced me to change my code to *only* use `foreach` and then do row # detections inside the loop construct.

**Comment by adrilo** [comment]
Ah that's indeed possible. Using `next` and `current` is not the recommended way to use Spout and there's no guarantee that it works as expected (and as you noticed, it does not). Eventually, this inconsistency should be fixed, but there's no plan fixing it for now...

**Comment by atrauzzi** [comment]
Doesn't that mean the implementation is broken?

**Comment by adrilo** [comment]
Yes the implementation is incorrect. It works when used with a foreach because `next` and `current` are called consecutively, but when manually calling the methods, the result may not be correct.
