### ISSUE TITLE
How do I keep line breaks

### ISSUE THREAD

**Issue by rondog** [box/spout#631]
I am importing a XLSX file and the import works, but the line breaks are not being preserved. It seems this is possible looking through the issue queue, but its not very clear to me and I couldn't find anything about it in the docs.

**Comment by adrilo** [comment]
You can call `setShouldPreserveEmptyRows()` on your `$reader` object (before calling `open`). Indeed it seems to be missing from the docs.

**Comment by rondog** [comment]
Hi @adrilo thanks for the response. I dont mean empty rows, I mean line breaks in a single cell. I have a description column with paragraphs in a single cell.

I did try the  `setShouldPreserveEmptyRows(true)` and reran the import but it didn't seem to make a difference.

**Comment by rondog** [comment]
I found a solution for now: replace the line breaks in the cell with <br> tags. I should have mentioned this data was getting imported into a database for display in HTML
