### ISSUE TITLE
XLSX reading error with PHP-FastCGI... but not PHP-FPM ! 

### ISSUE THREAD

**Issue by regis92** [box/spout#636]
Hello,

This is a strange issue...

I use Spout 2.7.3 with CodeIgniter 3.1 and PHP 5.6.4. + Apache 2.4 on Linux.

If i set PHP 5.6.4 on FastCGI, i get these errors :

`ERROR - 2019-04-11 15:21:48 --> Severity: Warning --> XMLReader::open(): Unable to open source data /var/www/vhosts/my-domain.com/httpdocs/application/third_party/spout/src/Spout/Reader/Wrapper/XMLReader.php 36

ERROR - 2019-04-11 15:21:48 --> Severity: error --> Exception: Could not open ./uploads/xls/my-xlsx-file.XLSX for reading! (Could not open "xl/sharedStrings.xml".) /var/www/vhosts/my-domain.com/httpdocs/application/third_party/spout/src/Spout/Reader/AbstractReader.php 126`

But if I set PHP 5.6.4 on PHP-FPM, all is fine !!!

Any idea... ?

(the problem is that I would rather use fast-cgi because I also have 500 errors using FPM due to configuration difficulties...).

Thank you very much for any help.

**Comment by adrilo** [comment]
This looks like a server configuration problem to me. Not much we can really help with, as it depends on your specific environment...

**Comment by regis92** [comment]
yes it's certainly a question of server configuration but it's strange ... 
especially since the php.ini is the same in both modes
