### ISSUE TITLE
Option to use SplFixedArray for shared strings, instead of file-based cache.

### ISSUE THREAD

**Issue by kewlar** [box/spout#65]
I have a proposal [to have an option] to make Spout faster by using SplFixedArray instead of files for storing shared strings. At the moment, switching shared-string cache files is one of the biggest performance hogs. On small files, it's not that big a deal. On big files it becomes painful.

I slapped together a quick spike to check how storing shared strings in files vs. array vs. SPL array compare in an XLSX reading test. Here are the benchmarks on my machine:

**Test1.xlsx:** 1.28 MB XLSX file, 9884 rows, 1.04 MB sharedStrings.xml

|           | memory_get_peak_usage(), MB | reader->open() time, s | Total read time, s |
| :-------- | --------------------------: | ---------------------: | -----------------: |
| Files     | 1.43                        | 7.03                   | 288.89             |
| Array     | 4.91                        | 3.54                   | 22.55              |
| SPL array | 2.97                        | 3.51                   | 22.79              |

**Test2.xlsx:** 79 MB XLSX file, 859988 rows, 53.5 MB sharedStrings.xml

|           | memory_get_peak_usage(), MB | reader->open() time, s | Total read time, s |
| :-------- | --------------------------: | ---------------------: | -----------------: |
| Files     | 1.59                        | 290.11                 | 20945.36           |
| Array     | 224.58                      | 162.93                 | 1300.42            |
| SPL array | 137.32                      | 174.85                 | 1262.81            |

I suggest to have an option in Spout to use in-memory SharedStringsHelper, when needed, which would then use SplFixedArray for storing them.

You can see my changes to the code at https://github.com/kewlar/spout/commit/bc72e2c34e9bb18c02a2be169c3d63917694ea1f, if you like. It was meant only for benchmarking the cases, but you can see that the SplFixedArray implementation for shared strings takes little enough code. I didn't figure out how to elegantly tell ReaderFactory (or XLSX) which shared strings helper strategy to use, though.

I understand that one of the goals of Spout was to use as little memory as possible, and I think the way it was accomplished was (and still is) ingenious, and I understand you may want to keep it this way. Still, in some use cases it may be preferable to sacrifice some memory for greater processing speed.

What do you think?

**Comment by adrilo** [comment]
Your idea is similar to what was done here: #49. I'm definitely for such a change but I believe that we can do even better :)

Having an option to store strings in memory is great... as long as there are not too many strings. You can try running the performance tests (there is a perf-test branch) with your changes, I am sure that you will get an out of memory crash. While the file-based caching is slow, it has the advantage of avoiding this kind of crash.

Now here is an idea about how to get the best of both worlds: the sharedStrings.xml file gives you the number of unique strings there are in the file. Based on this number, you could choose which strategy to use. For instance, if this number is greater than 10,000 then use file-based caching; otherwise use in-memory caching - and SplFixedArray is a good candidate, since we know the exact size of the array we want.
This way, Spout won't rely on developers to select the right strategy. Also, since choosing the strategy would be static, if you need to read big files 1% of the time, you'll need to select the file-based strategy, affecting the performance of the 99% other files... I believe that letting Spout choose the best strategy for the given file will be a big gain, both for the perfs and for the API simplicity.

How do you like this idea?

**Comment by kewlar** [comment]
I like the idea that Spout could determine the strategy automatically. It sounds like it would work for 99% of developers, and improve performance in many cases without any negative side effects. I'd still keep the option to specify the strategy for others. In my case, I'm processing of large XLSX files on my development machine, and it's no problem for me to give 3 GB memory to PHP while doing that, because it's preferable to waiting 6 hours for the XLSX to load.

On the subject of implementation, #49 does have a cleaner API; mine is ugly :) I'd only forego plain arrays, because `SplFixedArray` gives a significantly smaller memory consumption while not impacting performance terribly. One only has to be careful about not casting to array accidentally -- for a time I was using `array_has_key()` on it, and was wondering why I'm not getting the advertised memory savings.

Another minor thing to ponder is, what should the magic number be for selecting the strategy? Should it be arbitrary - ex. 10 000 strings, or should it depend on PHP's `memory_limit`? Or be able to be set by the developer, too?

I hope I'm not being a huge pain in the ass :)

**Comment by adrilo** [comment]
If Spout is smart enough to choose the right strategy based on multiples factors, then you remove the need for a specific setter. By doing this, you avoid to be locked into one strategy.
Even with 3GB of memory, you may have to read huge files that will require more than 3GB. If this happens, you'll need to use the file-based strategy, affecting the performance for all smaller files.

I really like your idea about `memory_limit`. Combining this info with the number of unique shared strings should be enough to optimize the memory consumption. We'll need to empirically determine the formula but that looks promising.
I'm still not sure if there is a benefit to keep a "low memory" option. I guess it's good for publicity :)

**Comment by kewlar** [comment]
I'd still vote to have the option to set the wanted strategy, to allow the developers to control how they want/need Spout to work. If it's a multi-user corporate site accepting XLSX uploads, low-memory option may be the best way to go. If it's a local dev machine for one-off processing, using faster but memory-hungry method and tweaking PHP settings may be more acceptable. Auto-strategy, while sounding awesome in theory, may have a downside of making a script not respond for a very long time without warning, when a file a bit too large is fetched. In my opinion, [out-of-memory] crashes are preferable to hours-long running time by being easier to spot, debug, and work around. And it gives more control to the developer.

Still, it's only my opinion, but it's your software, and it's very likely that you know best how Spout should evolve :) I won't be able to contribute in this discussion in the next few weeks (AFK), so if you decide to go ahead, do as you see fit. I'm glad to have successfully made use of it as it was.

**Comment by adrilo** [comment]
Hey @kewlar! I'm working on implementing the different strategies first.
I want to give the "smart" selection a try. I'll gather feedback and if needed, it will be straightforward to implement the setter to force a strategy.

> In my opinion, [out-of-memory] crashes are preferable to hours-long running time by being easier to spot, debug, and work around
I disagree. The library should not crash! If you need to process very large files, it's normal that it takes hours and your program should take this into account.
