### ISSUE TITLE
Upgrade to V3. Unsported Type Null?

### ISSUE THREAD

**Issue by AskanSimon** [box/spout#654]
Hello,

I have an old application with V2.7, everything runs fine. But with V3 adding rows to the Writer
results in an "Trying to add a value with an unsupported type: NULL" error. I think this is bug.
`
array(31) { ["A"]=> NULL ["B"]=> NULL ["C"]=> NULL ["D"]=> string(0) "" ["E"]=> NULL ["F"]=> string(0) "" ["G"]=> NULL ["H"]=> NULL ["I"]=> NULL ["J"]=> NULL ["K"]=> NULL ["L"]=> NULL ["M"]=> float(0) ["N"]=> float(0) ["O"]=> NULL ["P"]=> NULL ["Q"]=> float(0) ["R"]=> float(0) ["S"]=> float(0) ["T"]=> NULL ["U"]=> NULL ["V"]=> NULL ["W"]=> NULL ["X"]=> NULL ["Y"]=> NULL ["Z"]=> int(0) ["AA"]=> int(0) ["AB"]=> int(0) ["AC"]=> float(0) ["AD"]=> float(0) ["AE"]=> string(0) "" } `

PHP7.218

Best Regards
Simon

**Comment by madflow** [comment]
Please post your complete code. This works for me:

```PHP
use Box\Spout\Writer\Common\Creator\WriterEntityFactory;

$writer = WriterEntityFactory::createCSVWriter();
$writer->openToFile('aa.csv');
$writer->addRow(WriterEntityFactory::createRowFromArray([null]));
$writer->close();   
```

**Comment by BitWarriorsTechnology** [comment]
I am experiencing this issue when the reader comes across different formulas that I assume parse out as NULL.  They aren't normal functions, it's usually some strange combination of characters in front of an equals sign.  When I analyze each cell using var_dump they show up as "" empty strings...  Having a hard time with this issue and it's creating a hefty obstacle.

**Comment by madflow** [comment]
The above post deals with the `Writer` part of this library. You are mentioning having trouble with the `Reader` part. 

Formulas are not supported by the `Reader`. This is tracked for instance here: https://github.com/box/spout/issues/204

Returning `null` for unsupported content seems pretty reasonably at the moment to me. If you still think you found a bug or you want to work on reading formulas - it would be great to open a new issue or comment on the existing ones.

**Comment by BitWarriorsTechnology** [comment]
> The above post deals with the `Writer` part of this library. You are mentioning having trouble with the `Reader` part.
> 
> Formulas are not supported by the `Reader`. This is tracked for instance here: #204
> 
> Returning `null` for unsupported content seems pretty reasonably at the moment to me. If you still think you found a bug or you want to work on reading formulas - it would be great to open a new issue or comment on the existing ones.

I understand, just trying to find out how to handle the returned `null` value because right now I get a fatal error and everything quits.  As far as my knowledge goes, fatal errors are not stoppable, but I could very well be wrong.  It is reasonable to use null of course.  Do you know of any tickets that have been made for checking for formulas beforehand?  Or anything similar to handling them without getting a fatal error?  Possible with box/spout?

**Comment by faiyazalam** [comment]
> Please post your complete code. This works for me:
I am trying to write data like ['key'=>NULL] in XLSX and it is giving error "Trying to add a value with an unsupported type: NULL". It works with CSV writer.
