### ISSUE TITLE
PHP 7.4: disable the fgetcsv() escape character

### ISSUE THREAD

**Issue by Llbe** [box/spout#658]
The `GlobalFunctionsHelper::fgetcsv()` wrap sets the escape char to `\0` in order to disable it. With PHP 7.4, it's possible to set it to an empty string in order to disable it.

See https://github.com/box/spout/issues/473

See https://github.com/php/php-src/pull/3515

**Comment by adrilo** [comment]
Thanks for sharing this info @Llbe ! Since we still support PHP 7.1, we can't switch to the empty string yet. A `TODO` can be added in the code though to take that into account once we are > 7.4.

**Comment by markosko** [comment]
@adrilo Why not use  php constant `PHP_VERSION_ID` ? Introduced in PHP 5.2.7

**Comment by adrilo** [comment]
do you mean:
```
if (PHP_VERSION < 70400) {
 ...
} else {
 ...
}
```

**Comment by markosko** [comment]
Yes something like, only that PHP_VERSION is string format, PHP_VERSION_ID is in numeric but it wont be that much break change because of that escape character

**Comment by adrilo** [comment]
Sure we can do that :)
