### ISSUE TITLE
[Writer] Auto-width style for columns

### ISSUE THREAD

**Issue by dkarlovi** [box/spout#660]
Excel supports to specify auto-width for cells, it adapts to the widest content in the column.

Having this supported would allow for some fancier writer styling. :)

**Comment by adrilo** [comment]
Unfortunately, this is not magic. Excel does calculate the longest cell width and sets this size in the spreadsheet metadata. It's not just a "auto-width=1" option...
So to replicate the same behavior, we would need to do that, which is far from being trivial. This is tracked in #129
