### ISSUE TITLE
Upgrade v2.7.1 to v3.0.1 : Notice: Undefined index: http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles

### ISSUE THREAD

**Issue by alain-flaus** [box/spout#663]
Hello,
I have an application with box/spout v2.7.1.
I use it to read an "invalid" xlsx file. Content is valid but there is no "style" sheet.
In this previous version, the xlsx reader was triggering a warning but still read the file. 
Note that I have a warning when I try to read this file with excel too but it works.

After upgrading to v3.0.1 the same process throw an exception:

```
#message: "Notice: Undefined index: http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
#code: 0
#file: "./vendor/box/spout/src/Spout/Reader/XLSX/Manager/WorkbookRelationshipsManager.php"
#line: 83
```

Unfortunately the file is provided by a third-party application and it will not be fix.
I'm not able to give you that file because it contains sensitive data, and if I edit it, Excel will fix that "style" issue.

I can help with a pull request if you guide me to the solution you want for this : maybe ignoring the style in that case is enough ?

**Comment by delboy1978uk** [comment]
This ticket will probably be closed. It sounds like you are asking for a hack to be put in place so it can handle invalid input?

**Comment by alain-flaus** [comment]
Not really, the file is valid, excel can read it but it throw warnings (problem with the style sheet).
In the previous spout/box version, it also throw warning but the behavior has changed and now it throw an exception that block the reading of the file.
It does not seems to be a hack to me, because it was working well in the previous version.

**Comment by kierandelaney** [comment]
I appreciate it is nice when libraries are a bit more tolerant about files, but technically the file is not _valid_ as Excel itself warns you.

It's extremely difficult to replicate without the file - are the third party able to provide you a sanitised or test version of the file with dummy data?

I guess the best you could hope for is a switch or option for suppressing some non-catastrophic warnings, which in the lower levels of the library prevented an exception being thrown and emitted a softer level of warning or error.

**Comment by adrilo** [comment]
I believe this is ok to have Spout handle some of these invalid states. I just merged a PR to fix your issue @alain-flaus.

**Comment by egeis** [comment]
I was also having this issue in addition i am receiving a Fatal Error with the message Call to a member function getStringAtIndex() on null in /Spout/Reader/XLSX/Manager/SharedStringsManager.php on line 237. 

The XLSX file was created via Microsoft Excel (Mac) by loading a CSV file and then saving it as an XLSX file. The file appears to not have any styles attached and produced the error for which the merge fixed.  Updating Spout to use the merged fix cleared the undefined index but did not fix this issue.

If i take the contents of the cells out of the converted file and duplicate / clear the contents of one of the tests/resources/xlsx files or create a new blank workbook then paste the contents back in / save and load that file, then file loads successfully with no errors.
