### ISSUE TITLE
Get style properties unexcepted from xlsx?

### ISSUE THREAD

**Issue by zhuyingda** [box/spout#672]
Hi, I am new to this library and I follow the [documentation](http://opensource.box.com/spout/docs/) to write a simple `xlsx` parsing program.
It seems `getFontColor` method always returns `000000` no matter what color the cell has in xlsx file.
There are also some other methods have the problem, such as `getFontSize` always returns `11` and `getBackgroundColor` always returns NULL.

Here is my code and method usage:
```
use Box\Spout\Reader\Common\Creator\ReaderEntityFactory;

$filePath = '/**/test-demo.xlsx';

$reader = ReaderEntityFactory::createReaderFromFile($filePath);

$reader->open($filePath);

foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        $cells = $row->getCells();
        foreach ($cells as $cell) {
            var_dump('_____');
            var_dump('value: ' . $cell->getValue());
            $style = $cell->getStyle();
            var_dump($style->getFontColor());
            var_dump($style->getFontSize());
            var_dump($style->getBackgroundColor());
        }
    }
}

$reader->close();
```

And here is my Excel file:
![image](https://user-images.githubusercontent.com/9526467/61869100-72fb0580-af0d-11e9-8f50-9472e1f5eedf.png)

The php output is:

```
string(5) "_____"
string(10) "value: aaa"
string(6) "000000"
int(11)
NULL
string(5) "_____"
string(9) "value: dd"
string(6) "000000"
int(11)
NULL
string(5) "_____"
string(10) "value: bbb"
string(6) "000000"
int(11)
NULL
string(5) "_____"
string(9) "value: ee"
string(6) "000000"
int(11)
NULL
string(5) "_____"
string(10) "value: ccc"
string(6) "000000"
int(11)
NULL
string(5) "_____"
string(9) "value: ff"
string(6) "000000"
int(11)
NULL
```

**Comment by madflow** [comment]
Hello @zhuyingda.

Reading styles is not supported yet. This is tracked here: https://github.com/box/spout/issues/513

What you are seeing are the default values.

**Comment by landall** [comment]
I find you can track style->getId(), if it is null, it is the default value.
