### ISSUE TITLE
Cannot read from streamed CSV

### ISSUE THREAD

**Issue by pyr0hu** [box/spout#673]
Hello!

I was trying to read and process a CSV file from S3 using streams, but after opening the file and starting iterating on the rows, no row is loaded as `feof` returns true before even loading one row.

I attached the CSV file I was trying: [test.csv.zip](https://github.com/box/spout/files/3440623/test.csv.zip)

The code I was using:

```php
// Register AWS PHP's stream wrapper so we can support s3:// uris.
$adapter = Storage::getAdapter();
$client = $adapter->getClient();
$client->registerStreamWrapper();

$reader = ReaderEntityFactory::createCSVReader();
$reader->open('s3://test.csv');

foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        dump($row->getCells());
    }
}
```

My code does not reach the `dump()` call. If I use the native php file methods (fopen, fgetcsv) with the same `s3://` uri, I can load and process the lines properly.

I was putting breakpoints in the code and stepping through XDebug to find the bug and could locate the following situation:

when `rewind()` is called in `src/Spout/Reader/CSV/RowIterator.php`, the `feof()` returns false, so the file is open and not at the end of the file (in this case, stream). If we step inside `rewindAndSkipBom`, `feof()` still returns false, looking good at the moment. After `$this->globalFunctionsHelper->fseek()` is called, `feof()` now returns true, without even reading anything from the file so `RowIterator`'s `next()` won't return anything.

This only happens if I am reading a CSV from S3. (I don' think this issue is in aws-sdk-php because manually calling `fopen` and `fgetcsv` works so the `StreamWrapper` can read the CSV properly)

**Comment by adrilo** [comment]
According to https://aws.amazon.com/blogs/developer/amazon-s3-php-stream-wrapper/:
> the Amazon S3 stream wrapper are by default not seekable

To make it seekable, you need to specify it:
```
// Create a stream context to allow seeking
$context = stream_context_create(array(
    's3' => array(
        'seekable' => true
    )
));

if ($stream = fopen('s3://bucket/key', 'r', false, $context)) {
    // Read bytes from the stream
    fread($stream, 1024);
    // Seek back to the beginning of the stream
    fseek($stream, 0);
    // Read the same bytes that were previously read
    fread($stream, 1024);
    fclose($stream);
}
```

Can you please let me know if that fixes your problem?

**Comment by n4huel** [comment]
Hi @adrilo, your answer is correct. In order to read seekable streams from Amazon S3, you must create a stream context with `['s3' => ['seekable' => true]]` options and pass it to `\fopen()`. I had to rewrite `GlobalFunctionsHelper` class to create the required context and pass it to `\fopen()`.

Thanks you for your answer.
