### ISSUE TITLE
How to upgrade Spout 3.0

### ISSUE THREAD

**Issue by nazrullah07** [box/spout#675]
Hi, Currently am using PHPSpout 2.7 in Ubuntu. How can I upgrade to 3.0
//Ubuntu section
ubuntu@ubuntu:/var/www/html$ cd /var/www/html/phpspout
ubuntu@ubuntu:/var/www/html/phpspout$ composer require box/spout
Using version ^2.7 for box/spout
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

**Comment by adrilo** [comment]
`composer update box/spout` ?

**Comment by nazrullah07** [comment]
Hi..  I had tried the below command to update Ubuntu..  But it seems to be
doesn't work.

*composer update box/spout*

As well as how can I check the version of current PHP spout version.
Please help me to sort out the issue.

**Comment by adrilo** [comment]
To check the current version:
- inside `composer.lock`, you'll get the exact version installed (in case you're not using a fixed version in `composer.json`)
- or `composer info box/spout | grep versions`

**Comment by nazrullah07** [comment]
Thanks..

**Comment by nazrullah07** [comment]
While writing .xlsx is opening in Excel. But it is producing the error message while writing the file

**Comment by adrilo** [comment]
You can try removing the package and reinstalling it.
Please file another issue if you have a problem writing a file.

**Comment by nazrullah07** [comment]
<?php

# Include Spout library
require_once ('/var/www/html/phpspout/vendor/box/spout/src/Spout/Autoloader/autoload.php');

use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;




try {

    //Lokasi file excel
    $file_path = "/var/www/html/phpspout/SampleConatct.xlsx";
    $reader = ReaderFactory::create(Type::XLSX); //set Type file xlsx
    $reader->open($file_path); //open the file

    $i = 0;

    /**
     * Sheets Iterator. Kali aja multiple sheets
     **/
    foreach ($reader->getSheetIterator() as $sheet) {

        //Rows iterator
        foreach ($sheet->getRowIterator() as $row) {

            print_r($row);

            ++$i;
        }
    }

    echo "Total Rows : " . $i;
    $reader->close();




} catch (Exception $e) {

    echo $e->getMessage();
    exit;
}






?>

This is my entire code

**Comment by nazrullah07** [comment]
![image](https://user-images.githubusercontent.com/36001505/62459009-f8977480-b79b-11e9-973a-aab986938181.png)

**Comment by nazrullah07** [comment]
The above error pop ups while file is opening

**Comment by nazrullah07** [comment]
> You can try removing the package and reinstalling it.
> Please file another issue if you have a problem writing a file.

Is there any command to remove the package

**Comment by adrilo** [comment]
https://getcomposer.org/doc/03-cli.md#remove (please search on Google before asking questions not related to Spout).
