### ISSUE TITLE
How to read the entire rows from Excel file?

### ISSUE THREAD

**Issue by nazrullah07** [box/spout#676]
In my files there are total 1048576 rows, But I can read only 184066 rows. How can I sort of it.?
abc.xlsx

**Comment by nazrullah07** [comment]
[abc.xlsx](https://github.com/box/spout/files/3470493/abc.xlsx)

**Comment by nazrullah07** [comment]
Each time I refresh, The number of reading row gets varies. What is the solution for this.?

**Comment by adrilo** [comment]
Can you please share some code? Spout is very predictable so there should not be any variation in the number of rows read. There's something wrong with your code.
