### ISSUE TITLE
Error when adding new sheet

### ISSUE THREAD

**Issue by aduhaime-arm** [box/spout#677]
Hi, while trying to create a new sheet, I get the following error:

> exception: "ErrorException"

> file: "/app/vendor/box/spout/src/Spout/Writer/XLSX/Internal/Worksheet.php"

> line: 91

> fopen(/tmp/xlsx5d6531ca659056.27788695/xl/worksheets/sheet2.xml): failed to open stream: No such file or directory"

Here is the code I use:

```
public function createNewSheet($sheetName = null)
{
        if ($this instanceof AbstractMultiSheetsWriter) {
            $sheet = $this->writer->addNewSheetAndMakeItCurrent();
            $sheet->setName($sheetName ?? $sheet->getName());
            return $sheet;
        }
        throw new Exception('Failed to create new sheet');
}

public function appendRowsToCurrentSheet(array $rows)
{
        $this->writer->openToFile($this->filePath);
        $this->writer->addRows($rows);

        $this->writer->close();
}
```

```
$summaryRows = (new HandoverSummarySheetRows($this->parameters))->getRows();
        $detailRows = (new HandoverDetailSheetRows($this->parameters))->getRows();

        $this->appendRowsToCurrentSheet($summaryRows);
        $this->createNewSheet(); //This is where the error occurs
       $this->appendRowsToCurrentSheet($detailRows);
```
I have also tried to set a sheetname and the temporary folder path using `setTempFolder`, without success.

I am using version 2.7 of Spout.

Any idea what is causing this?

**Comment by adrilo** [comment]
Not sure why it does not work. Maybe try with another version of Spout? If you use `setTempFolder`, do you have the same error?

Something I noticed though is that you're going to call `openToFile` multiple times (as `appendRowsToCurrentSheet` is called multiple times). This is not gonna work.

**Comment by aduhaime-arm** [comment]
Updating to version 3.0.1 solved the error.  I also changed my code for the following:
```
    public function appendRowsToCurrentSheet($rows)
    {
        if (!$this->fileIsOpened) {
            $this->writer->openToFile($this->filePath);
            $this->fileIsOpened = true;
        }
        $arrayOfRows = collect($rows)->map(function($row) {
            return WriterEntityFactory::createRowFromArray($row);
        })->toArray();
        $this->writer->addRows($arrayOfRows);
    }

    protected function free()
    {
        if ($this->fileIsOpened) {
            $this->writer->close();
        }
    }
```
I think a `isFileOpen` method would be useful to add in WriterAbstract.

Thank's for the help
