### ISSUE TITLE
Where can I find 2.0 documentation?

### ISSUE THREAD

**Issue by rondog** [box/spout#679]
I tried searching for it, but cannot locate documentation for ^2.0. Going into an older project and not looking to upgrade to 3.0 at this time.

**Comment by adrilo** [comment]
It's no longer visible online. However, you can checkout the `2.x-branch` and follow the procedure defined in the README here: https://github.com/box/spout/tree/master/docs/README.md to have it run locally (you'll just need docker)

**Comment by rondog** [comment]
Thank you!
