### ISSUE TITLE
Commas in strings in csv writer

### ISSUE THREAD

**Issue by shansalam** [box/spout#685]
When trying to write a string that contains commas into a csv file, the string gets truncated and all the corresponding columns go empty. The csv file is ";" delimited.

**Comment by adrilo** [comment]
Can you please share some code that reproduces the issue?

**Comment by adrilo** [comment]
I just tried with this CSV:
```
foo;comma,delimited;bar
```

And this code:
```
$reader = ReaderEntityFactory::createCSVReader($filePath);
$reader->setFieldDelimiter(';');
$reader->open($filePath);

foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        echo implode(' | ', $row->getCells()) . "\n";
    }
}

$reader->close();
```

It is working as expected:
```
foo | comma,delimited | bar
```
