### ISSUE TITLE
The official website cannot be accessed

### ISSUE THREAD

**Issue by chuxiangqaz** [box/spout#689]
When I want to view the document, but not access!
`http://opensource.box.com/spout/`

**Comment by ijiaxin** [comment]
HTTPS can be used to open, but the resource file is HTTP, causing page style confusion

**Comment by ijiaxin** [comment]
> If you're accessing this site from China, the domain `box.com` is probably blocked there...

HTTPS can be used to open, but the resource file is HTTP, causing page style confusion

**Comment by ijiaxin** [comment]
The page style is messy, because the CSS file is loaded with HTTP, not HTTPS, loading failed

**Comment by ijiaxin** [comment]
You need to modify the website code to load the CSS file HTTPS as well.

**Comment by ijiaxin** [comment]
`<link rel="stylesheet" href="http://opensource.box.com/spout/css/main.css">`

**Comment by adrilo** [comment]
Yes, I realized that. I'm trying to find a way to fix that.

**Comment by ijiaxin** [comment]
Many links in your website are not HTTPS. You need to use HTTPS throughout the site.

**Comment by maijs** [comment]
For some reason somebody decided that the best way to force users to use HTTPS is to put `<!-- This is a hack to force using HTTPS... -->` in `href` attribute of every link.

Chrome reacts with the following console message:
```
[Deprecation] Resource requests whose URLs contained both removed whitespace (`\n`, `\r`, `\t`) characters and less-than characters (`<`) are blocked. Please remove newlines and encode less-than characters from places like element attribute values in order to load these resources. See https://www.chromestatus.com/feature/5735596811091968 for more details.
```

All the links on the page look like this:
```
<a class="page-link" href="<!-- This is a hack to force using HTTPS... -->
<!-- The URL of the docs should be changed in the repo settings instead -->
https://opensource.box.com/spout/getting-started/">Getting Started</a>
  <a class="page-link" href="<!-- This is a hack to force using HTTPS... -->
<!-- The URL of the docs should be changed in the repo settings instead -->
https://opensource.box.com/spout/docs/">Documentation</a>
  <a class="page-link" href="<!-- This is a hack to force using HTTPS... -->
<!-- The URL of the docs should be changed in the repo settings instead -->
https://opensource.box.com/spout/guides/">Guides</a>
  <a class="page-link" href="<!-- This is a hack to force using HTTPS... -->
<!-- The URL of the docs should be changed in the repo settings instead -->
https://opensource.box.com/spout/faq/">FAQ</a>
```

**Comment by ijiaxin** [comment]
nice

**Comment by adrilo** [comment]
Alright, it's finally fixed :)
