### ISSUE TITLE
Add access/documentation to Get and Set cell protected value

### ISSUE THREAD

**Issue by BitWarriorsTechnology** [box/spout#701]
I was trying to figure out the issue I am having from issue #204 and #654...  After not finding a solution from either I dug a bit, which wasn't far, it just felt like it because of my lack of knowledge.  And I discovered that my excel sheets occasionally do something dumb and I want to be able to prevent this from creating a fatal error...  My code is as such:
```
foreach($sheet->getRowIterator() as $rowObject){
          $row = $rowObject->getCells();
          for($v = 0; $v < count($row); $v++){
              var_dump($row[$v]);
          }
}
```

Fairly simple.  For the sake of not posting a bunch of useless info I won't show the full object dump.  The important part is here...
`object(Box\Spout\Common\Entity\Cell)#227 (3) { ["value":protected]=> string(7) "#DIV/0!" `

So this wouldn't normally be weird...  In fact why don't I just check the cell value like normal?  So I swapped `var_dump($row[$v]);` with `echo "Value: " . $row[$v];` and this is the result:

`Value: `

So that's inconvenient...

I opened the xlsx sheet in google sheets and did [ctrl + f] for '#DIV' and it found nothing.  Maybe my issue is Google sheets, but previous to this problem I found several formulas which equated to what I would assume to be NULL values, and removing those seemed to solve it.  There is nothing obvious in the data about this particular piece of text...  So Box/Spout is picking up something I can't see or change.  My next solution would be to delete what I assume to be the problem row and try again, which is a bad idea because it is sensitive information, but what else can I do?

Any thoughts, comments, questions, suggestions, would be greatly appreciated...

I was going to try to write a class to extend the Cell class so that I could add Get and Set functions for the protected value but I have no idea how to do that.  Is this even a good idea?...  Thanks for the help.

**Comment by madflow** [comment]
Firstly, an example  (minimal, anonymized) file would be great to grasp what you are trying to do ;)

**Comment by BitWarriorsTechnology** [comment]
Ohhh I am so sorry I forgot to add what I was working towards xD... Silly me, I was very tired.  I will work on getting a simplified code file, and also a simplified .xlsx (if I can).  I am worried about making an .xlsx because not only do I need worry about the integrity of the data but also the integrity of the issue and in changing data to make it anonymized I risk changing the issue unintentionally.  However, I am not sure which you are looking for... xlsx file, php, or both?  If PHP, while I am working on that, I am hoping that this clarification can help...

So a few hundred lines of code down from the block I posted above, I am attempting to write the same row to a file, after making certain appendages... (similar to this [Guide](https://opensource.box.com/spout/guides/edit-existing-spreadsheet/))

A lot of `$row[] = WriterEntityFactory::createCell("Append", $style);`
and of course `$writer->addRow(WriterEntityFactory::createRow($row));`

It USUALLY works perfectly.  Row by row, and often times I finish an entire file perfectly... :) So thank you for that...

AND BANG!

`Fatal error: Uncaught Box\Spout\Common\Exception\InvalidArgumentException: Trying to add a value with an unsupported type: NULL in myfilepath/vendor/box/spout/src/Spout/Writer/XLSX/Manager/WorksheetManager.php:230 Stack trace: #611  
myfilepath/vendor/box/spout/src/Spout/Writer/XLSX/Manager/WorksheetManager.php(196): Box\Spout\Writer\XLSX\Manager\WorksheetManager->getCellXML(125, 16, Object(Box\Spout\Common\Entity\Cell), 0) #1 
myfilepath/vendor/box/spout/src/Spout/Writer/XLSX/Manager/WorksheetManager.php(164): Box\Spout\Writer\XLSX\Manager\WorksheetManager->applyStyleAndGetCellXML(Object(Box\Spout\Common\Entity\Cell), Object(Box\Spout\Common\Entity\Style\Style), 125, 16) #2 
myfilepath/vendor/box/spout/src/Spout/Writer/XLSX/Manager/ in myfilepath/vendor/box/spout/src/Spout/Writer/XLSX/Manager/WorksheetManager.php on line 230`

So THIS error, is what led me to start `var_dump`ing things and figuring out why this was happening.  That little `#DIV/0!` thing occurs on exactly the row that this error occurs... I just can't see it in the xlsx file, nor can I see it in php besides your protected value...  

My hopeless (and unsustainable) solution prior to my petty outrage, was downloading the xlsx file off my server, directly changing the content, and reuploading it.  Well I process too many xlsx files to count automatically, and to do this often is torture...

I hope this clarifies things a bit :)  Can you tell me if you want php, xlsx, or both, if I haven't fixed the curiosity? :D  Thanks :D

**Comment by madflow** [comment]
I have opened the test file in Libreoffice. In the first row/cell there is a value `=#DIV/0!`.

When reading the with Spout and trying to write it back to an new file I get two different results. When just try to write the read `Row` - there is an error `unsupported type: NULL`. When I use the `createRowFromArray` helper with the cell values, there is no error.

This is the working version:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Box\Spout\Writer\Common\Creator\WriterEntityFactory;
use Box\Spout\Reader\Common\Creator\ReaderEntityFactory;

$fileName = __DIR__ . '/testFile.xlsx';

$writer = WriterEntityFactory::createXLSXWriter();
$writer->openToFile(__DIR__ . '/testFileNew.xlsx');

$reader = ReaderEntityFactory::createReaderFromFile($fileName);
$reader->open($fileName);

foreach($reader->getSheetIterator() as $sheet) {
    foreach($sheet->getRowIterator() as $row) {
        // $writer->addRow($row); // This throws an error, unsupported type: NULL
        $cellValues = array_map(function($cell) {
            return $cell->getValue();
        }, $row->getCells());
        $newRow = WriterEntityFactory::createRowFromArray($cellValues);
        $writer->addRow($newRow);
    }
}
$reader->close();
$writer->close();
```

I would argue, that a valid read `Row` should be able to be written by Spout without any amendments. 
@adrilo

**Comment by BitWarriorsTechnology** [comment]
Ahh THANK YOU.

I am very glad for a conclusion, and also that I am not 100% crazy.  It's always nice to not be fully embarassed about an issue I'm having.  I didn't consider changing the method I used.  The solution you provided will result in A LOT of code changes considering I built the everything around the one method, but it should be fine and at this point in time I don't see much option...  Thanks for the help, and I hope this helps but I'm not sure as it's a very specific case and I know how that goes!

**Comment by adrilo** [comment]
Hey guys, I created a PR to add support for cells with errors. Let me know what you think.

**Comment by madflow** [comment]
I did a retest with the setup above - and the `=#DIV/0!` cell was correctly written to the new Spreadsheet. Although this makes it work - I wonder if we need a bigger picture how to handle errored cell content. For the moment this patch should work just fine though.
