### ISSUE TITLE
how to use openToFile to store the CSV i have generated to Amazon S3? is it possible?

### ISSUE THREAD

**Issue by drevendy** [box/spout#711]

**Comment by drevendy** [comment]
i don't know how to store the csv i have created to amazon s3. is is possible to use openToFIle to store to amazon s3? 

i tried using openToBrowser and everything works fine.

**Comment by adrilo** [comment]
You can generate you CSV on disk temporarily and once created, upload it via S3 using their SDK.
You can try using `s3://...` as the file path but I can't guarantee this works.
