### ISSUE TITLE
writer time format

### ISSUE THREAD

**Issue by vadbard** [box/spout#719]
Hi.
I have 'time' column in my data to write to excel file. It is a simple string like '10:49:05'. 
This is how I write data to my excel file
```php
        foreach ($obReportData as $obRow) {
            $arRow = (array) $obRow;
            $excelRow = WriterEntityFactory::createRowFromArray($arRow);
            $writer->addRow($excelRow);
        }
```

When I open my ready-made file my time column looks like this:
10:49:05.000000

My question is if there any way to leave my time as it was '10:49:05'?

version of Spout is v3.1.0

**Comment by adrilo** [comment]
Unfortunately, you can't specify a cell type (TIME for instance) at the moment. So all cells are using the default GENERAL cell type, unless Excel guesses otherwise (which it does apparently).
One way to force the value as a string may be to use `'=10:49:05'`. You can give it a try
