### ISSUE TITLE
How to set input encoding for Reader?

### ISSUE THREAD

**Issue by DenisAlliswell** [box/spout#72]
Hi @adrilo!

How I can set input encoding 'CP1251' for reading file?

For instance, in PHPExcel that can be achieved with the following:
```php
$objReader = new PHPExcel_Reader_CSV();
$objReader->setInputEncoding('CP1251');
```

**Comment by adrilo** [comment]
Hi @DenisAlliswell,

Unfortunately, this is not possible yet. I have a TODO in the code to allow this: https://github.com/box/spout/blob/d4cf85327026d62d5975dff086e19518722b598b/src/Spout/Reader/CSV.php#L53

If you feel like it, feel free to submit a pull request. I'll be happy to help you add support for multiple encodings :)

**Comment by DenisAlliswell** [comment]
Ok, thank you for what you're doing! :+1: That's great!

**Comment by adrilo** [comment]
Hi @DenisAlliswell, you should now be able to specify the encoding of your CSV file :)

**Comment by DenisAlliswell** [comment]
Hi @adrilo! Thanks, cool!
