### ISSUE TITLE
undefined offset, but the offset exist in my xlsx

### ISSUE THREAD

**Issue by itajackass** [box/spout#720]
I've a strange problem.
I get error

      Notice: Undefined offset: 19

In my test.xlsx at row 17. I don't know why. If I insert some text it is ok...but if it is empty I get error.....the strange thing is that all columns at index 19 before 17 are empty but they doesn't get any error.

My code test: and in attachment the file
[test.zip](https://github.com/box/spout/files/4134401/test.zip)

    include_once(dirname(dirname(__FILE__)) . "/vendors/spout/src/Spout/Autoloader/autoload.php");

    use Box\Spout\Reader\Common\Creator\ReaderEntityFactory

    $xlsx = ReaderEntityFactory::createReaderFromFile(dirname(__FILE__) . '/test.xlsx');

    $xlsx->open(dirname(__FILE__) . '/test.xlsx');
	
	
	foreach ($xlsx->getSheetIterator() as $sheet) {
		
		foreach ($sheet->getRowIterator() as $row) {

			$cells = $row->getCells();
				
		    var_dump( $cells[18]->getValue() );
                    var_dump( $cells[19]->getValue() ); //<---error offset 19 at row 17!!!!!!
			
		}
			
	}

**Comment by adrilo** [comment]
Old issue, closing it.
