### ISSUE TITLE
StyleBuilder() using hex color value wastes memory

### ISSUE THREAD

**Issue by hoggj** [box/spout#721]
It seems that using StyleBuilder with a custom hex color (e.g 0000FF for blue) uses a ton of memory compared to the pre-defined colors such as Color::BLUE.

**Relevant snippet:**
```
//LOW MEMORY
$row[] = WriterEntityFactory::createCell('test', (new StyleBuilder())->setFontColor(Color::BLUE)->build());

//HIGH MEMORY
$row[] = WriterEntityFactory::createCell('test', (new StyleBuilder())->setFontColor($colorHex)->build());
```
**Output:**
setFontColor($colorHex): `Peak memory usage: 189436 KB`
setFontColor(Color::BLUE): `Peak memory usage: 1666 KB`

**Full code:**

(For demo purposes I'm loading a small 250x150 image to provide multiple color values)

```
<?php

	require_once 'Spout/Autoloader/autoload.php';
	use Box\Spout\Writer\Common\Creator\WriterEntityFactory;
	use Box\Spout\Common\Entity\Style\Color;
	use Box\Spout\Writer\Common\Creator\Style\StyleBuilder;
	
	//load an image
	$img = imagecreatefrompng('input/test250x150.png');

	$writer = WriterEntityFactory::createXLSXWriter();
	$writer->openToFile('output/MyExcel.xlsx');

	//height of the image
	for($y=0; $y<150; $y++) {
		
		//create or reset array to hold this row's cells
		$row = [];

		//width of the image
		for($x=0; $x<250; $x++) {

			//gets the pixel color
			$index = imagecolorat($img, $x, $y);
			$colorRGBArr = imagecolorsforindex($img, $index);
			$colorHex = sprintf("%02x%02x%02x", $colorRGBArr['red'], $colorRGBArr['green'], $colorRGBArr['blue']);

			//LOW MEMORY
			//$row[] = WriterEntityFactory::createCell('test', (new StyleBuilder())->setFontColor(Color::BLUE)->build());
			//HIGH MEMORY
			$row[] = WriterEntityFactory::createCell('test', (new StyleBuilder())->setFontColor($colorHex)->build());

		}
		$writer->addRow(WriterEntityFactory::createRow($row));
	}

	$writer->close();

	echo 'Peak memory usage: '.round(memory_get_peak_usage() / 1024).' KB';
?>
```

**Comment by hoggj** [comment]
Also posted the problem here and received a really good answer. The tl;dr is that it's not using a hex color that is a problem per se, it's the fact that each new style creates a unique style index in Spout, while duplicate styles (e.g. setFontColor(Color::BLUE)) re-uses the existing style. Spout could probably do something here to optimise this, but there is very little practical application.  Closing issue.

https://stackoverflow.com/questions/60078787/box-spout-massive-memory-usage-when-using-hex-color-vs-pre-defined-colors

**Comment by adrilo** [comment]
Excellent answer indeed! Something else that could help is to set a custom default style for the style that's used the most.
