### ISSUE TITLE
Can I set the author of the xlsx in the metadata?

### ISSUE THREAD

**Issue by jonjibbed** [box/spout#723]
I don't see this in the docs, but I do in the code: createCoreXmlFile()

What is the correct way to interface with it?

**Comment by adrilo** [comment]
Unfortunately, there's no way to set the author at the moment.

**Comment by jonjibbed** [comment]
No problem, thanks. Just wondering why the code seems to exist to do it, is it a planned feature one day?

**Comment by adrilo** [comment]
Not really. Creating the core xml file is a requirement to generate a valid file hence the presence of this function. But as you saw, it's all hardcoded and not available through the API.
