### ISSUE TITLE
Bug: Value of XLSX cell being incorrectly changed by the format of the cell in certain cases

### ISSUE THREAD

**Issue by ryanrapini** [box/spout#725]
Hey all,

Sorry if this is already documented or I'm missing something.

Steps to reproduce:

[Book1.xlsx](https://github.com/box/spout/files/4227377/Book1.xlsx)

1. Create a new xlsx file (I have attached an example file for your convenience)
2. In this file, add a new cell and type a number (999)
3. Right click the cell and click Format Cells... on the Number Tab, select Custom format and enter in `# "AS"`
4. Save the sheet, then read with Spout Reader

Code Snippet:
```
$reader->open($filePath);

        foreach ($reader->getSheetIterator() as $sheet) {
            $is_header_loaded = false;
            foreach ($sheet->getRowIterator() as $row_number => $row) {
                dd($row->getCells());
```

Output:
```
  1 => Box\Spout\Common\Entity\Cell^ {#394
    #value: "# AS"
    #type: 1
    #style: Box\Spout\Common\Entity\Style\Style^ {#393
      -id: null
      -fontBold: false
      -hasSetFontBold: false
      -fontItalic: false
      -hasSetFontItalic: false
      -fontUnderline: false
      -hasSetFontUnderline: false
      -fontStrikethrough: false
      -hasSetFontStrikethrough: false
      -fontSize: 11
      -hasSetFontSize: false
      -fontColor: "000000"
      -hasSetFontColor: false
      -fontName: "Arial"
      -hasSetFontName: false
      -shouldApplyFont: false
      -shouldApplyCellAlignment: false
      -cellAlignment: null
      -hasSetCellAlignment: false
      -shouldWrapText: false
      -hasSetWrapText: false
      -border: null
      -shouldApplyBorder: false
      -backgroundColor: null
      -hasSetBackgroundColor: false
      -format: null
      -hasSetFormat: false
    }
```

This bug appears to occur with only certain letter combinations, and I wasn't able to determine a consistent rule for what causes it.

Some that cause the bug:
```
# "CAD"
# "AS"
# "UYY"
```
Some that dont cause the bug:
```
# "AA"
# "ABC"
# "AAA"
# "AAB"
```

This is weird...

**Comment by adrilo** [comment]
Unfortunately, Spout does not support custom number format well.
As there's no plan to improve this part yet, I'm going to close this issue.
