### ISSUE TITLE
XLSX reading error "Could not open ....xlsx for reading!" 

### ISSUE THREAD

**Issue by yujin1st** [box/spout#727]
Hello, I'm getting this error while trying to open a xlsx ReaderFactory
"Could not open /www/....filename.xlsx for reading! (Could not open "xl/sharedStrings.xml".

Issue is the same as https://github.com/box/spout/issues/379 
but using libxml_disable_entity_loader doesn't solve issue.

previously i had this issue on 2.7 version #441 and after updating to v3.1.0 i got this error.

php v7.3.11. File attached. Google can't properly open file, but office 365 does fine.
It's automatically created price list of one our supplier, so we can't do nothing with it.

[eh02CQJ89ALtOrEfGjvD3PBHp (2).xlsx](https://github.com/box/spout/files/4273718/eh02CQJ89ALtOrEfGjvD3PBHp.2.xlsx)
![75333612-c8dfc380-58c9-11ea-9650-2e5f94d5ba0f](https://user-images.githubusercontent.com/2317913/75650670-f6e25080-5c99-11ea-92d7-8541bec0c952.png)
![75333745-07757e00-58ca-11ea-883d-7e5e53048a32](https://user-images.githubusercontent.com/2317913/75650673-f944aa80-5c99-11ea-9bfe-0b640c853442.png)

**Comment by madflow** [comment]
Some observations: The file you posted does not contain a `xl/sharedStrings.xml` - but a `xl/SharedStrings.xml` (note the different case) file. This is the reason the reader cannot find it (on Linux with ext4 fs at least).

When I hack the `WorkbookRelationshipsManager::RELATIONSHIP_TYPE_SHARED_STRINGS` to `xl/SharedStrings.xml`  - the file can be read but yields another error:

> PHP Fatal error:  Uncaught Error: Call to a member function getStringAtIndex() on null in /spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php:237

A quick fix just to get it working is to open it on "LibreOffice" and save it again. 

A test with another library (openpyxl, Python) yields the same result - but with a better error message:

> Traceback (most recent call last):
  File "a.py", line 2, in <module>
    wb2 = load_workbook('tests.xlsx')
  File "/home/flo/.virtualenvs/pyxl/lib/python3.8/site-packages/openpyxl/reader/excel.py", line 314, in load_workbook
    reader.read()
  File "/home/flo/.virtualenvs/pyxl/lib/python3.8/site-packages/openpyxl/reader/excel.py", line 274, in read
    self.read_strings()
  File "/home/flo/.virtualenvs/pyxl/lib/python3.8/site-packages/openpyxl/reader/excel.py", line 143, in read_strings
    with self.archive.open(strings_path,) as src:
  File "/usr/lib64/python3.8/zipfile.py", line 1512, in open
    zinfo = self.getinfo(name)
  File "/usr/lib64/python3.8/zipfile.py", line 1439, in getinfo
    raise KeyError(
KeyError: "There is no item named 'xl/sharedStrings.xml' in the archive"

**Comment by yujin1st** [comment]
Thank you for detailed answer. 
Such file is automatically generated once in day by external system  – I'm writing auto-import of price-lists – so i can't do anything manually with them (open in editor, or something else).
Is any other options that i can possibly do?

**Comment by madflow** [comment]
You could

* convert it with Libreoffice in Headless mode.
> soffice --convert-to ods myfile.xlsx  --headless  
* talk to the people who program the external system

**Comment by yujin1st** [comment]
Thank you for help.
i think issue could be closed
