### ISSUE TITLE
$writer->openToBrowser being inconsistent on Content-Type header

### ISSUE THREAD

**Issue by Gavrisimo** [box/spout#730]
PHP: 7.4.3
spout: 3.1.0

I'm doing something like this:

```
        $writer = WriterEntityFactory::createCSVWriter();
        $writer->openToBrowser($file_name);

        foreach ($data as $row_data) {
            $writer->addRow(WriterEntityFactory::createRowFromArray($row_data));
        }

        $writer->close();
```

If file has 36 or less rows the `Content-Type` header is set to: `text/html; charset=UTF-8`

If file has 37 or more rows the `Content-Type` header is set to: `text/csv; charset=UTF-8`

I have no idea what's happening... :) Any tips on where to look?

**Comment by adrilo** [comment]
Spout uses `text/csv; charset=UTF-8` for the Content-Type. The other header probably comes from your code. I can't help.
