### ISSUE TITLE
Spout fails to read XLSX file with large sharedString.xml

### ISSUE THREAD

**Issue by sancozta** [box/spout#731]
Hello, we are trying to read a file ([1584648766_ORIGINAL.xlsx](https://github.com/box/spout/files/4357064/1584648766_ORIGINAL.xlsx)) aprox. 9MB and about 20k rows divided in to worksheets. But the file fail to open, in smaller files the reader works without a problem.

The problem seams to be related to the function call $this->sharedStringsManager->extractSharedStrings() in line 92 of Reader.php.

I'm guessing there is a problem in our file that resulted on a very large sharedStrings.xml file (29MB) and therefore the reader get stuck on it. Is there a way to config spout to not read that file? Is there a known performance problem in the sharedStrings reader?

We tried to bypass the sharedStrings reader by commenting lines 90 to 93 of Reader.php file, but it resulted in the following error:

> Call to a member function getStringAtIndex() on null`
> vendor\box\spout\src\Spout\Reader\XLSX\Manager\SharedStringsManager.php:237
> vendor\box\spout\src\Spout\Reader\XLSX\Helper\CellValueFormatter.php(152): Box\Spout\Reader\XLSX\Manager\SharedStringsManager->getStringAtIndex(0)

**Comment by madflow** [comment]
Shared strings is a `xlsx` feature that results in smaller file sizes. It is basically a map of all unique strings in the complete workbook.

This why you cannot disable the shared strings reader - the result will be empty/incomplete.

Spout will try to determine the best strategy for reading the shared strings. They can either fit safely into ram or a file base strategy will be used. The in-memory strategy is usually faster.

Your options include:

* Raise the PHP memory limit `ini_set('memory_limit', ...);` before reading the file
* Preprocess the file and save it **without** shared strings
* Convert it to `ods` and try if this gives better results
* Help us to work on https://github.com/box/spout/issues/550
