### ISSUE TITLE
duplicate file with extension .csv and .CSV

### ISSUE THREAD

**Issue by dagatogamez** [box/spout#734]
Hi, I'm sorry to bother you but I just updated the library by composing and it gives me an error when displaying the files on the server. You cannot save the "vendor\box\spout\tests\resources\csv_test_create_from_file.CSV" file because the "vendor\box\spout\tests\resources\csv_test_create_from_file.csv" file already exists. I have this deployment in a pipeline of devops that deployed an artifact in azure. And have this error.

Translated with www.DeepL.com/Translator (free version)

**Comment by adrilo** [comment]
Hi! Why do you need to run Spout's tests in your pipeline?
