### ISSUE TITLE
Shared strings are written multiple times (XLSX)

### ISSUE THREAD

**Issue by sclause2412** [box/spout#736]
According to documentation the default setting is inline texts which is faster but creates bigger files. Another disadvantage is that the file is not correctly shown on Mac.
Therefore shared strings can be activated with this setting:
`$writer->setShouldUseInlineStrings(false);`
The result should be this:
**sheet1.xml**
```xml
<sheetData>
  <row r="1" spans="1:1">
    <c r="A1" s="0" t="s">
      <v>0</v>
    </c>
  </row>
  <row r="1" spans="1:1">
    <c r="A2" s="0" t="s">
      <v>0</v>
    </c>
  </row>
</sheetData>
```
**sharedStrings.xml**
```xml
<sst xmlns="..." count="2" uniqueCount="1">
  <si>
    <t xml:space="preserve">Test</t>
  </si>
</sst>
```
But the `writeString` function in SharedStringManager class does not check for duplicates - even if documentation says so. The result is:
**sheet1.xml**
```xml
<sheetData>
  <row r="1" spans="1:1">
    <c r="A1" s="0" t="s">
      <v>0</v>
    </c>
  </row>
  <row r="1" spans="1:1">
    <c r="A2" s="0" t="s">
      <v>1</v>
    </c>
  </row>
</sheetData>
```
**sharedStrings.xml**
```xml
<sst xmlns="..." count="2" uniqueCount="2">
  <si>
    <t xml:space="preserve">Test</t>
  </si>
  <si>
    <t xml:space="preserve">Test</t>
  </si>
</sst>
```
The final Excel file uses shared strings which makes it work on Mac. However, the file size is bigger as the strings are not "compressed".

For me this seems to be a bug.

**Comment by adrilo** [comment]
Hi,

Strictly speaking, this indeed goes against the concept of shared strings. While this can be seen as a bug, I rather considered this approach as a shortcut. It works *almost* as expected for the end user (module the final size of the spreadsheet) so IMO it was an acceptable tradeoff to avoid maintaining the full list of strings in memory to check for duplicates.

Implementing a proper solution is costly. I'm not sure how Excel does it, but I'd probably go with a Bloom filter approach to limit the amount of memory needed. No plans to work on it at the moment though.
