### ISSUE TITLE
FastExcel读取上传的excel文件报错

### ISSUE THREAD

**Issue by wqj0304** [box/spout#739]
Box\Spout\Common\Exception\IOException: Could not open /private/var/tmp/php3hgkgs for reading! (Could not open /private/var/tmp/php3hgkgs for reading.) in file /Applications/MxSrvs/www/expert/vendor/box/spout/src/Spout/Reader/AbstractReader.php on line 126
Stack trace:
  1. Box\Spout\Common\Exception\IOException-&gt;() /Applications/MxSrvs/www/expert/vendor/box/spout/src/Spout/Reader/AbstractReader.php:126
  2. Box\Spout\Reader\AbstractReader-&gt;open() /Applications/MxSrvs/www/expert/vendor/rap2hpoutre/fast-excel/src/Importable.php:96
  3. Rap2hpoutre\FastExcel\FastExcel-&gt;reader() /Applications/MxSrvs/www/expert/vendor/rap2hpoutre/fast-excel/src/Importable.php:47
  4. Rap2hpoutre\FastExcel\FastExcel-&gt;import() /Applications/MxSrvs/www/expert/app/Http/Controllers/Expert/ExpertController.php:80
  5. App\Http\Controllers\Expert\ExpertController-&gt;importExpert() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  6. call_user_func_array() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  7. Illuminate\Routing\Controller-&gt;callAction() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
  8. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
  9. Illuminate\Routing\Route-&gt;runController() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176
 10. Illuminate\Routing\Route-&gt;run() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Router.php:680
 11. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 12. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
 13. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 14. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 15. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
 16. Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 17. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 18. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56
 19. Illuminate\Session\Middleware\StartSession-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 20. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 21. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
 22. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 23. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 24. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
 25. Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 26. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 27. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
 28. Illuminate\Pipeline\Pipeline-&gt;then() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682
 29. Illuminate\Routing\Router-&gt;runRouteWithinStack() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Router.php:657
 30. Illuminate\Routing\Router-&gt;runRoute() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Router.php:623
 31. Illuminate\Routing\Router-&gt;dispatchToRoute() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Router.php:612
 32. Illuminate\Routing\Router-&gt;dispatch() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
 33. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 34. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
 35. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 36. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 37. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
 38. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 39. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 40. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
 41. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 42. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 43. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
 44. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 45. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 46. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/fideloper/proxy/src/TrustProxies.php:57
 47. Fideloper\Proxy\TrustProxies-&gt;handle() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 48. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 49. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
 50. Illuminate\Pipeline\Pipeline-&gt;then() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
 51. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() /Applications/MxSrvs/www/expert/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
 52. Illuminate\Foundation\Http\Kernel-&gt;handle() /Applications/MxSrvs/www/expert/public/index.php:55

**Comment by wqj0304** [comment]
@rap2hpoutre

**Comment by adrilo** [comment]
With absolutely no context, we won't be able to help...

**Comment by SamMousa** [comment]
This is a file permission issue, totally unrelated to this library.
