### ISSUE TITLE
Wrong order of empty columns (Google Spreadsheets generated XLSX)

### ISSUE THREAD

**Issue by alexroosenstein** [box/spout#740]
Hi,

I'm using Spout 3.1.0 and I'm running into the issue where the reader adds empty columns to the back of the row if the XLSX file was generated by Google Spreadsheets.
[demo_spreadsheet.xlsx](https://github.com/box/spout/files/4592322/demo_spreadsheet.xlsx)

If I open the file in Microsoft Excel 2019 and (re)save it, it's fixed.

I tried enabling setShouldPreserveEmptyRows to see if it would make any difference, but it didn't.
Some test code:
```
        $reader = ReaderEntityFactory::createReaderFromFile(__DIR__.'/demo_spreadsheet.xlsx');
        //$reader->setShouldPreserveEmptyRows(true);
        $reader->open(__DIR__.'/demo_spreadsheet.xlsx');

        foreach($reader->getSheetIterator() as $sheet)
        {
            foreach($sheet->getRowIterator() as $row)
            {
                echo 'Row iterator'.PHP_EOL;
                $cells = $row->getCells();
                $data = array();
                foreach($cells as $id=> $cell)
                    $data[] = $cell->getValue();

                var_dump($data);
                var_dump($row->toArray());
                echo PHP_EOL;
            }
        }
```
The output:
[demo_spreadsheet_output.txt](https://github.com/box/spout/files/4592330/demo_spreadsheet_output.txt)

The toArray() function clearly shows the order is wrong, as the empty column with ID 1 is at the end of the array (but with the correct key).

EDIT: Just checked if this also occured with Spout 2.X, it does not. This is apparently a new bug introduced in Spout 3.(1?)

**Comment by celloman** [comment]
Hi, we are experiencing the same issue with a google spreadsheets generated xlsx file and Spout 3.1.0. Is there any hope of a quick resolution to this?

**Comment by celloman** [comment]
For now, it seems that it will work to just do a ksort() on the resulting array since the keys are still correct. However, a true fix for the library would be cool

**Comment by IvanChernikov** [comment]
Had the same issue, used `ksort()` to fix it. can recommend `Box\Spout\Common\Entity\Row` implement `IteratorAggregate` with:
```
function getIterator(): Traversable
{
    $iterator = new ArrayIterator($this->cells);
    $iterator->ksort();
    return $iterator;
}
```

**Comment by adrilo** [comment]
The issue only happens if sheet dimensions are not specified (`<dimension ref='A1:M13'/>`).
I'm gonna push a fix for this case.
