### ISSUE TITLE
Maximum execution time of 120 seconds exceeded 

### ISSUE THREAD

**Issue by sdsz65** [box/spout#741]
Hi, I have this error when read xlsx file. There is no problem when read csv file with this code:

```
$upload_name = 'assets\tmp\\' . (self::uploadFile($value, 'assets/tmp/'));
$reader = '';
if ($value["type"] == 'application/vnd.ms-excel') $reader = ReaderEntityFactory::createCSVReader();
else $reader = ReaderEntityFactory::createXLSXReader();;
$reader->open('c:\file_excel1.xlsx'); //open the file
foreach ($reader->getSheetIterator() as $key => $sheet) {
if ($key > 1) break;
foreach ($sheet->getRowIterator() as $row_key => $Row) {
$cells = $Row->getCells();
echo $row_key.'--'.trim($cells[3]).'<br>';
}
}
```

My file:
[file_excel.xlsx](https://github.com/box/spout/files/4615850/file_excel.xlsx)

**Comment by adrilo** [comment]
Reading an Excel file takes much longer than reading a CSV, as the format is more complex and requires more processing.

In your case, your server only allows scripts to be executed for 120s. They are terminated after that. So while it may work with a CSV file, processing the Excel file takes more than 120s and triggers this error.

You can try increasing this period using `set_time_limit` (https://www.php.net/manual/en/function.set-time-limit.php). There's not much more you can do...

**Comment by sdsz65** [comment]
For 5000 row how long long does it take?

**Comment by sdsz65** [comment]
Now, i have another issue. when i echo cell value print the value correctly but when i assign that value to an array cell that's not work.

`foreach ($sheet->getRowIterator() as $row_key => $Row) {
              if ($row_key == 1) continue;
              if ($row_key == 10) break;
              $cells = $Row->getCells();
              if (trim($cells[1]) == '' && !is_numeric(trim($cells[1]))) continue;
              if (trim($cells[2]) == '' && !is_numeric(trim($cells[2])) && strlen($cells[2]) != 6) continue;
              $data_row = array();

              $data_row['RegisterDate'] = $today;
              $data_row['LoadDate'] = utf8_encode(modify_date(trim($cells[1])));
              $data_row['EntryDate'] = utf8_encode(modify_date(trim($cells[2])));
              $var = $cells[3];
              echo $var.'<br>'; // Print correct value
              $data_row['DriverName'] = $var; // assign Box\Spout\Common\Entity\Cell Object
}`
