### ISSUE TITLE
Bump minimum PHP version

### ISSUE THREAD

**Issue by SamMousa** [box/spout#743]
Since PHP 7.1 has been EOL I propose bumping the minimum required version to 7.4 and releasing a new major version.

Sticking with modern PHP versions makes it easier for contributors to contribute code. Also seeing as the v3 code base has a very clean OOP design it could benefit from the new strong typing features in 7.4.

(I'm selfishly asking this because I'd love to make a PR for some parts of the code but don't want to spend time on different syntax versions)

**Comment by adrilo** [comment]
Done
