### ISSUE TITLE
When cell contain a zero value, stop reading row

### ISSUE THREAD

**Issue by antoiba86** [box/spout#759]
I had a very weird issue while using box/spout.

I had different excel files, some files have empty cells in the middle of the row, those worked fine.
Another files had a 0 inside the cell instead of an empty cell. In these cases, the reader didn't get all the row, only until the 0.

I was using the method 

```
$cells = $row->getCells();
$customer_code = $cells[0]->getValue();
```

My solution was to replace all cells containing 0 for an empty string. Then, the problem "magically" was solved.
I don't know if this is a problem with box/spout or with Excel.

**Comment by madflow** [comment]
@antoiba86 I cannot replicate this using a simple `xlsx` file created in LibreOffice.


A | B | C
-- | -- | --
1 | 0 | 1
0 | 1 | 0

```PHP
<?php

require __DIR__ . '/vendor/autoload.php';

use Box\Spout\Reader\Common\Creator\ReaderFactory;

$reader = ReaderFactory::createFromFile('test.xlsx');

$reader->open('test.xlsx');
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        var_dump('ROW');
        $cells = $row->getCells();
        foreach ($cells as $cell) {
            var_dump($cell->getValue());
        }
    }
}

$reader->close();
```

```
string(3) "ROW"
string(1) "A"
string(1) "B"
string(1) "C"
string(3) "ROW"
int(1)
int(0)
int(1)
string(3) "ROW"
int(0)
int(1)
int(0)
```

Please share the (anonymized) file you are seeing this in.

**Comment by antoiba86** [comment]
Sorry for the delay. Too much work and I found a workaround, format the cells with zero to empty string and now it takes everything on the row.

I attach the file I am using and I will write down the code.

This is my environment.
"php": "^7.1.3",
box/spout": "^3.0
"laravel/framework": "5.8.*"

I am using Docker with the environment of php:7.2-fpm-stretch

`$reader = ReaderEntityFactory::createXLSXReader();
        $reader->open($filePath);

        foreach ($reader->getSheetIterator() as $sheet) {
            foreach ($sheet->getRowIterator() as $row) {
                // do stuff with the row
                $cells = $row->getCells();
                $customer_code = $cells[0]->getValue();
                $cellData = [];
                foreach ($cells as $keyCell => $cell) {
                    $value = $cell->getValue();
                    if ($value == "COD_CLID") {
                        break;
                    }
                    if (!empty($value)) {
                        $keyForValue = GetKey::getKey($keyCell, $customer_code);
                        if (!empty($keyForValue)) {
                            $cellData[$keyForValue] = $value;
                        }
                    }
                }
                if (!empty($cellData)) {
                    $cellData['created_by_user_id'] = Auth::user()->id;
                    $cellData['last_updated_by_user_id'] = Auth::user()->id;
                    SarebDataService::saveDataByCustomerAndServiceLocation($cellData);
                }

            }
        }

        $reader->close();`

[archivo_prueba.xlsx](https://github.com/box/spout/files/5451531/archivo_prueba.xlsx)

**Comment by adrilo** [comment]
Here is what the reader reads:

| COD_CLI | COD_CLI2 | COD_CLI3 | COD_CLI4 | COD_CLI5 | COD_CLI6 |
|---------|----------|----------|----------|----------|----------|
| 126 | 126 | 6063996 | 126 | 126 | 126 |
| 127 | 127 | 0 | 127 | 127 | 127 |
| 128 | 128 | 6029435 | 128 | 128 | 128 |
| 129 | 129 | 6014464 | 129 | 129 | 129 |
| 130 | 130 | 6011271 | 130 | 130 | 130 |
| 131 | 131 | 0 | 131 | 131 | 131 |
| 132 | 132 | 6021466 | 132 | 132 | 132 |
| 133 | 133 | 6087509 | 133 | 133 | 133 |
| 134 | 134 | 6087509 | 134 | 134 | 134 |
| 135 | 135 | 6087509 | 135 | 135 | 135 |
| 136 | 136 | 6087509 | 136 | 136 | 136 |
| 137 | 137 | 6087509 | 137 | 137 | 137 |
| 138 | 138 | 6087509 | 138 | 138 | 138 |
| 139 | 139 | 6087509 | 139 | 139 | 139 |
| 140 | 140 | 6087509 | 140 | 140 | 140 |
| 141 | 141 | 6087509 | 141 | 141 | 141 |
| 142 | 142 | 6087509 | 142 | 142 | 142 |
| 143 | 143 | 6087509 | 143 | 143 | 143 |
| 144 | 144 | 6087509 | 144 | 144 | 144 |
| 145 | 145 | 6087509 | 145 | 145 | 145 |
| 146 | 146 | 6087509 | 146 | 146 | 146 |
| 147 | 147 | 6011230 | 147 | 147 | 147 |
| 148 | 148 | 6016472 | 148 | 148 | 148 |
| 149 | 149 | 6016472 | 149 | 149 | 149 |
| 150 | 150 | 6016472 | 150 | 150 | 150 |
| 151 | 151 | 6016472 | 151 | 151 | 151 |
| 152 | 152 | 0 | 152 | 152 | 152 |
| 153 | 153 | 0 | 153 | 153 | 153 |

The output looks correct to me and matches what's in the file.
