### ISSUE TITLE
How to prevent modyfing header for PHPUnit tests only

### ISSUE THREAD

**Issue by LocalHeroPro** [box/spout#774]
Did we have ability to don't modify headers when we use:
```php
$writer->openToBrowser($fileName);
```
because right now I got exception:
```
message = Cannot modify header information - headers already sent by (output started at /var/www/html/vendor/phpunit/phpunit/src/Util/Printer.php:104)
file = /var/www/html/vendor/box/spout/src/Spout/Common/Helper/GlobalFunctionsHelper.php
line = 252
```

**Comment by adrilo** [comment]
Hello! 
Well, you can mock the call? If you're writing a functional test, then you do want to send these headers. And if so, I'd recommend you to change your code so that it does not send headers too early.

**Comment by LocalHeroPro** [comment]
Yes I can, and then don't use that library.
So basically I'm thinking you are joking with your answer, yes?

**Comment by adrilo** [comment]
I'm not sure to understand what your expectation is. If you want to test/trigger the behavior of the `openToBrowser` then you do want the headers to be set. If you don't want this, then you can mock the method call.
What's wrong with that?
