### ISSUE TITLE
2.7.x compatibility with PHP 8.0

### ISSUE THREAD

**Issue by YetiCGN** [box/spout#775]
With PHP 8.0.0 around the corner, I thought I'd run a quick syntax check in my project which uses box/spout 2.7.3. The result:

```
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in vendor/box/spout/src/Spout/Common/Singleton.php on line 39
PHP Warning:  The magic method Box\Spout\Common\Singleton::__wakeup() must have public visibility in vendor/box/spout/src/Spout/Common/Singleton.php on line 39
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in vendor/box/spout/src/Spout/Common/Singleton.php on line 40
```

Will try running some of the code after fixing this. Are you still maintaining that branch or should we switch to 3.x for PHP 8?

**Comment by adrilo** [comment]
The 2.x branch is no longer maintained. But feel free to add support for PHP 8 in the 3.x branch
