### ISSUE TITLE
Feature request: add ability to add additional heder when using $writer->openToBrowser

### ISSUE THREAD

**Issue by LocalHeroPro** [box/spout#776]
When using
```php
$writer->openToBrowser($fileName);
```
add additional header, like:
```php
$writer->openToBrowser($fileName)->headers(['foo' => 'bar']);
````
I want to use this because I have to apply manually:
```php
header('Access-Control-Expose-Headers: Content-Disposition');
```

**Comment by adrilo** [comment]
Hello @LocalHeroPro! Do you think this header should be set all the time?

**Comment by LocalHeroPro** [comment]
Yes, I think so.
But will be nice to have that as a feature.

**Comment by adrilo** [comment]
@LocalHeroPro Actually, now that I come back to this: there's nothing preventing you from calling `header('Access-Control-Expose-Headers: Content-Disposition');` before/after calling `$writer->openToBrowser($fileName);`? I don't think you need Spout to handle that right?

**Comment by adrilo** [comment]
Actually, I'm going to close this issue. Feel free to re-open if you think it's still relevant.
