### ISSUE TITLE
XLSX writer performance issues

### ISSUE THREAD

**Issue by errXprintln** [box/spout#777]
Hi,
we use spout3.1.0 in one of our projects.
Using the XLSX writer we have about 29.000 rows with 300 columns each. So there are about 87.000.00 cells to be written.
Unfortunately it takes more than five minutes. The webserver returns error code 503, not even timeout errors.
This is a set of mixed data types containing datetimes, strings, integers.

Our writer is set up as follows:
```
        use Box\Spout\Writer\Common\Creator\WriterEntityFactory;
        $writer = WriterEntityFactory::createXLSXWriter();
        $fullPath = Utility::getFullTempPath() . DIRECTORY_SEPARATOR . uniqid() . '.xlsx';
        $writer->openToFile($fullPath);
        $headerCells = array();
        $firstRow = array_key_first($this->data);
        foreach ($this->data as $row => $rowData) {
            $cells = array();
            foreach ($rowData as $columnHeader => $columnValue) {
                if ($row === $firstRow) {
                    array_push($headerCells, WriterEntityFactory::createCell($columnHeader));
                }
                array_push($cells, WriterEntityFactory::createCell($columnValue));
            }

            if ($row === $firstRow) {
                $headerRow = WriterEntityFactory::createRow($headerCells);
                $writer->addRow($headerRow);
            }
            $row = WriterEntityFactory::createRow($cells);
            $writer->addRow($row);
        }

        $writer->close();
        return $fullPath;
```

I don't know if that is the best approach considering performance but with a smaller amount of data no 503 errors are returned - so I guess it's related. Any thoughts on how to speed it up if possible?

Thanks in advance!

**Comment by adrilo** [comment]
Hello!

I believe what you're doing is what I'd recommend you to do... Reading/writing 87M cells is a long process, so I'm not surprised it takes more than 5min!
I don't think there's much more you can do here!
