### ISSUE TITLE
 can this export function generate data while outputting to the browser?

### ISSUE THREAD

**Issue by aikunzhe** [box/spout#783]
Hello, can this export function generate data while outputting to the browser?
I used ob_flush(); flush(); but it does not work.

**Comment by aikunzhe** [comment]
你好， 这个导出功能，是否可以边输出到浏览器，边生成数据？
我使用了 ob_flush();  flush(); 但是不生效

**Comment by adrilo** [comment]
If you mean streaming, here is an example of how you can do it: https://opensource.box.com/spout/guides/symfony-stream-content-large-spreadsheet/

This only works with CSV though... XLSX and ODS are not compatible with streaming
