### ISSUE TITLE
Writer: empty cells are changed to 0

### ISSUE THREAD

**Issue by fasttrackhost** [box/spout#785]
Hi. Regarding Writer. 
Is there a way to change behavior of empty cells being changed to 0 int value ?
Cant find anything about in the docs.

Is a product table and depending of cell, the value 0 (zero) actually has a meaning different than empty string.

I could only find this:

$reader->setShouldPreserveEmptyRows(true);

But nothing about empty cells.

I must take a moment and say Good Job. The script is very very good. It writes xls files no matter how much data without consuming several GBs of RAM. And its a lot faster than others.

**Comment by adrilo** [comment]
Thanks for the kind words! Really appreciate :)
Empty cells should remain empty. We have a bunch of tests covering this use case. So there must be an issue with your code. Without more context, I won't be able to help.

**Comment by adrilo** [comment]
Stale. Closing issue.
