### ISSUE TITLE
speed issue migrating to spout 3.x

### ISSUE THREAD

**Issue by olaulau** [box/spout#786]
Hi ;
I had a small piece of code, outputing about 3000 rows with a few columns.
simple text, no formating : a basic table.
with spout 2.7, it took about 500ms (which is already quite huge, but the fastest I found in PHP libs).
I just migrated the code following your guidelines. now the execution  takes about 2000ms (on the same conditions of course).
this is a huge performance drop, and not acceptable for a small file like this.

piece of code involved :
```
		$entreprises = $db->exec($sql);
		$headers = array_keys($entreprises[0]);
		
		$writer = WriterEntityFactory::createXLSXWriter();
		$writer->openToBrowser("export.xlsx"); // stream data directly to the browser
		$headersRow = WriterEntityFactory::createRowFromArray($headers);
		$writer->addRow($headersRow);
		$rows = [];
		foreach ($entreprises as $entreprise) {
			$row = WriterEntityFactory::createRowFromArray($entreprise);
// 			$writer->addRow($row);
			$rows[] = $row;
		}
		$writer->addRows($rows);
		$writer->close();
		die;
```

**Comment by adrilo** [comment]
Hello !

This is indeed a known issue. We lost of speed but gained on other features. It was a tradeoff. Some users are interested in pure performance. Others are interested in additional features such as cell styling, ...
Feel free to submit PRs if you have ideas on how to improve the performance.
