### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by plyaskin** [box/spout#787]
Hi all! 
I trying to run the samples for reading and writing to xlsx but always have the same error (HTTP ERROR 500). 
Could you help me?

My index.php is
```
<?php

require_once 'vendor/spout/src/Spout/Autoloader/autoload.php';

use Box\Spout\Reader\Common\Creator\ReaderEntityFactory;

$reader = ReaderFactory::create(Type::XLSX); 

$filePath ='1.xlsx';

$reader->open($filePath);

foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        print_r($row);
    }
}

$reader->close();
echo "OK";
```
![image](https://user-images.githubusercontent.com/9464550/104555349-4b9f7780-5670-11eb-8564-838640a99741.png)

My php is

```
PHP 7.4.12 (cli) (built: Oct 31 2020 17:03:53) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
enchant
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
PDO_Firebird
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by hugotkk** [comment]
Can you add these lines at the beginning to get the error message.
``` php
error_reporting(E_ALL);
ini_set('display_errors' 1);
```

**Comment by plyaskin** [comment]
I don't have any messages, just HTTP ERROR 500 :(
I use this code (example from documentation):
`<?php

error_reporting(E_ALL);
ini_set('display_errors' 1);

require_once __DIR__.'/vendor/box/spout/src/Spout/Autoloader/autoload.php';

use Box\Spout\Writer\Common\Creator\WriterEntityFactory;
use Box\Spout\Common\Entity\Row;

$writer = WriterEntityFactory::createXLSXWriter();

$filePath = '1.xlsx';

$writer->openToFile($filePath); // write data to a file or to a PHP stream
//$writer->openToBrowser($fileName); // stream data directly to the browser

$cells = [
    WriterEntityFactory::createCell('Carl'),
    WriterEntityFactory::createCell('is'),
    WriterEntityFactory::createCell('great!'),
];

/** add a row at a time */
$singleRow = WriterEntityFactory::createRow($cells);
$writer->addRow($singleRow);

/** add multiple rows at a time */
$multipleRows = [
    WriterEntityFactory::createRow($cells),
    WriterEntityFactory::createRow($cells),
];
$writer->addRows($multipleRows); 

/** Shortcut: add a row from an array of values */
$values = ['Carl', 'is', 'great!'];
$rowFromValues = WriterEntityFactory::createRowFromArray($values);
$writer->addRow($rowFromValues);

$writer->close();

echo "OK";
`
After using this line, the " OK " disappeared."
`$writer = WriterEntityFactory::createXLSXWriter();`

**Comment by plyaskin** [comment]
> I don't have any messages, just HTTP ERROR 500 :(
> I use this code (example from documentation):
> 
> `<?php
> 
> error_reporting(E_ALL);
> ini_set('display_errors' 1);
> 
> require_once **DIR**.'/vendor/box/spout/src/Spout/Autoloader/autoload.php';
> 
> use Box\Spout\Writer\Common\Creator\WriterEntityFactory;
> use Box\Spout\Common\Entity\Row;
> 
> $writer = WriterEntityFactory::createXLSXWriter();
> 
> $filePath = '1.xlsx';
> 
> $writer->openToFile($filePath); // write data to a file or to a PHP stream
> //$writer->openToBrowser($fileName); // stream data directly to the browser
> 
> $cells = [
> WriterEntityFactory::createCell('Carl'),
> WriterEntityFactory::createCell('is'),
> WriterEntityFactory::createCell('great!'),
> ];
> 
> /** add a row at a time */
> $singleRow = WriterEntityFactory::createRow($cells);
> $writer->addRow($singleRow);
> 
> /** add multiple rows at a time */
> $multipleRows = [
> WriterEntityFactory::createRow($cells),
> WriterEntityFactory::createRow($cells),
> ];
> $writer->addRows($multipleRows);
> 
> /** Shortcut: add a row from an array of values */
> $values = ['Carl', 'is', 'great!'];
> $rowFromValues = WriterEntityFactory::createRowFromArray($values);
> $writer->addRow($rowFromValues);
> 
> $writer->close();
> 
> echo "OK";
> `
> 
> After using this line, the " OK " disappeared."
> 
> `$writer = WriterEntityFactory::createXLSXWriter();`

**Comment by plyaskin** [comment]
I have found the log messages
`php
PHP Fatal error:  Uncaught Box\\Spout\\Common\\Exception\\IOException: Cannot perform I/O operation outside of the base folder:  in /home/admin/web/dev.wedtp.com/public_html/vendor/box/spout/src/Spout/Common/Helper/FileSystemHelper.php:128\nStack trace:\n#0 /home/admin/web/dev.wedtp.com/public_html/vendor/box/spout/src/Spout/Common/Helper/FileSystemHelper.php(35): Box\\Spout\\Common\\Helper\\FileSystemHelper->throwIfOperationNotInBaseFolder()\n#1 /home/admin/web/dev.wedtp.com/public_html/vendor/box/spout/src/Spout/Writer/XLSX/Helper/FileSystemHelper.php(115): Box\\Spout\\Common\\Helper\\FileSystemHelper->createFolder()\n#2 /home/admin/web/dev.wedtp.com/public_html/vendor/box/spout/src/Spout/Writer/XLSX/Helper/FileSystemHelper.php(101): Box\\Spout\\Writer\\XLSX\\Helper\\FileSystemHelper->createRootFolder()\n#3 /home/admin/web/dev.wedtp.com/public_html/vendor/box/spout/src/Spout/Writer/XLSX/Creator/ManagerFactory.php(49): Box\\Spout\\Writer\\XLSX\\Helper\\FileSystemHelper->createBaseFilesAndFolders()\n#4 /home/admin/web/dev.wedtp.com/public_html/vendor/box in /home/admin/web/dev.wedtp.com/public_html/vendor/box/spout/src/Spout/Common/Helper/FileSystemHelper.php on line 128`

**Comment by plyaskin** [comment]
It works!

Solution: 
\home\admin\conf\web\site..com.apache2.conf
or
\Timeweb\home\admin\conf\web\site.com.apache2.ssl.conf
insert `:/tmp` to the end of string `php_admin_value open_basedir /home/admin/web/dev.wedtp.com/public_html:/home/admin/tmp`
it should be `php_admin_value open_basedir /home/admin/web/dev.wedtp.com/public_html:/home/admin/tmp**:/tmp**`
