### ISSUE TITLE
Spout date time conversion create undesire outcome

### ISSUE THREAD

**Issue by michaelsiu** [box/spout#788]
New to spout. 

I am just wondering if my cell is '2020-10-06', after i set $reader->setShouldFormatDates(true); it will convert to '10/6/2020' which is not what i want. 

I just want the original value back. '2020-10-06' 
I read from another post that you can use
$reader->disableDateAutoConversion();
OR
$reader->returnDatesAsStrings();

but that didn't work with $reader = ReaderEntityFactory::createReaderFromFile($filePath);

help please

**Comment by adrilo** [comment]
Hello! Using `$reader->setShouldFormatDates(true);` is the right thing to do. However there may be some locale issue causing your date to be formatted differently.
The date value is stored as a timestamp so Spout has to re-format the value. Depending on your software and locale, this may or may not work as expected...
