### ISSUE TITLE
XLSX Reader error when run

### ISSUE THREAD

**Issue by smoln** [box/spout#790]
Hello,
Sometimes I'm getting this error while trying to open a xlsx ReaderFactory

Fatal error: Uncaught Box\Spout\Common\Exception\IOException: Could not open .../pricepmco.xlsx for reading! (Could not open "xl/sharedStrings.xml".) in .../vendor/box/spout/src/Spout/Reader/ReaderAbstract.php:130
Stack trace:
#0 .../import.php(112): Box\Spout\Reader\ReaderAbstract->open('$file')
#1 {main}
  thrown in .../vendor/box/spout/src/Spout/Reader/ReaderAbstract.php on line 130

[pricepmco.xlsx](https://github.com/box/spout/files/5872287/pricepmco.xlsx)
spout version 3.1.0
php  7.2
libxml Version 2.9.4

`$reader = ReaderEntityFactory::createReaderFromFile("$file");
            
$reader->open($file);
foreach ($reader->getSheetIterator() as $sheet) {

foreach ($sheet->getRowIterator() as $result) {
  
print_r($result);

}

}`

**Comment by ionstudio** [comment]
The same problem.

File generated Go Excelize

**Comment by SpaceInvader2020** [comment]
Same problem here, file was created using office 365, anyone managed to resolve this yet ?

**Comment by adrilo** [comment]
This seems to be caused by incorrect spreadsheet metadata (at least for the file given by @smoln).

The file containing shared strings is defined this way:
```
<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>
```

However, the actual file name is `SharedStrings.xml` (note the capital S). Because filesystems are usually case sensitive, the file `sharedStrings.xml` can't be found. Hence the error!

Unfortunately, there's not much we can do here. It's not Spout's responsibility to fix this kind of errors I believe.

**Comment by SpaceInvader2020** [comment]
It looks like this excel reader doesn't support purl.oclc.org (strict ooxml namespace). 
It is unable to read xlsx files when file is created with MS Excel using Mac. 
If you upload the xlsx file to office 365 cloud, save in the cloud and download - it starts working for me. 
Sadly you will need to do that until library will have support for purl.oclc.org namespace. 
I have found the same issue with other similar bundles and packages

**Comment by adrilo** [comment]
@SpaceInvader2020 The issue you're describing (strict ooxml support) is different from what I described above (case sensitivity issue).
But I'm glad to say that I added support for strict OOXML namespace yesterday :) I haven't released a new version yet but will soon! Hopefully, it will help.

**Comment by SpaceInvader2020** [comment]
Excellent news! :)
