### ISSUE TITLE
createReaderFromFile produces an error

### ISSUE THREAD

**Issue by eugenio11** [box/spout#791]
Hello,
if I follow the instructions here:
https://opensource.box.com/spout/getting-started/

using:
$reader = ReaderEntityFactory::createReaderFromFile('/path/to/file.ext');

I get:
Fatal error: Uncaught Box\Spout\Reader\Exception\ReaderNotOpenedException: Reader should be opened first

I need to do:
$reader = ReaderEntityFactory::createXLSXReader();
$reader->open('/path/to/file.ext');

am I doing something wrong?  I am using Spout 3.1.0 with PHP 7.1.1

Thanks

**Comment by adrilo** [comment]
You probably forgot to add this line `$reader->open($filePath);`

**Comment by eugenio11** [comment]
You are right, when I tried I probably thought the open line was a typo because (for consistency) I expected:

$reader = ReaderEntityFactory::createReaderFromFile('/path/to/file.ext');
$reader->open('/path/to/file.ext');

and not 

$reader = ReaderEntityFactory::createReaderFromFile('/path/to/file.ext');
$reader->open($filePath);
