### ISSUE TITLE
When save file to CSV new line works as new row iterator

### ISSUE THREAD

**Issue by LocalHeroPro** [box/spout#795]
When save data to CSV file and on one cell have <new line> inside cell, that line works as go to new row and new cells.
When open in Excel it's broke, in LibreOffice works as expected.
Cell setFieldDelimiter: ,
Cell setFieldEnclosure: "

Original cell:
```
Metalowy cyrkiel z regulacją kąta nachylenia grafitu. Solidny mechanizm regulacji promienia
 rysowanych okręgów, zapobiega efektowi „elipsy” przy mocniejszym przyciśnięciu cyrkla do papieru. Łatwy w obsłudze system wymiany
grafitów. Maksymalna średnica rysowanych okręgów to 32cm. Idealny do zastosowań szkolnych na lekcjach matematyki, techniki i plastyki. Pakowany w plastikową kasetę z linijką 
pełniącą funkcję wieczka kasety.
```
CSV view:
![image](https://user-images.githubusercontent.com/42643563/108264022-48b00f00-7167-11eb-8627-064859ddf230.png)

**Comment by adrilo** [comment]
What do you mean by "one cell have inside cell"?
Can you provide a test file where the issue can be reproduced, along with explanations on what the expected behavior should be?

**Comment by adrilo** [comment]
Stale. Closing issue.
