### ISSUE TITLE
Date/datetime cell type not implemented for insert?

### ISSUE THREAD

**Issue by devnix** [box/spout#797]
I'm trying to insert a DateTime into a XLSX with no luck, this exception gets thrown: `Trying to add a value with an unsupported type: object`

```php
    private function getCellXML($rowIndexOneBased, $columnIndexZeroBased, Cell $cell, $styleId)
    {
        $columnLetters = CellHelper::getColumnLettersFromColumnIndex($columnIndexZeroBased);
        $cellXML = '<c r="' . $columnLetters . $rowIndexOneBased . '"';
        $cellXML .= ' s="' . $styleId . '"';

        if ($cell->isString()) {
            $cellXML .= $this->getCellXMLFragmentForNonEmptyString($cell->getValue());
        } elseif ($cell->isBoolean()) {
            $cellXML .= ' t="b"><v>' . (int) ($cell->getValue()) . '</v></c>';
        } elseif ($cell->isNumeric()) {
            $cellXML .= '><v>' . $cell->getValue() . '</v></c>';
        } elseif ($cell->isError() && is_string($cell->getValueEvenIfError())) {
            // only writes the error value if it's a string
            $cellXML .= ' t="e"><v>' . $cell->getValueEvenIfError() . '</v></c>';
        } elseif ($cell->isEmpty()) {
            if ($this->styleManager->shouldApplyStyleOnEmptyCell($styleId)) {
                $cellXML .= '/>';
            } else {
                // don't write empty cells that do no need styling
                // NOTE: not appending to $cellXML is the right behavior!!
                $cellXML = '';
            }
        } else {
            throw new InvalidArgumentException('Trying to add a value with an unsupported type: ' . \gettype($cell->getValue()));
        }

        return $cellXML;
    }
```

It's me, or the DateTime cell is not implemented in `Box\Spout\Writer\XLSX\Manager\WorksheetManager::getCellXML()`?

**Comment by adrilo** [comment]
Hello !
It's not implemented indeed. It's actually tricky to implement correctly. In XLSX, a date is composed of a timestamp + a custom style representing how it's formatted. There's no plan to add this feature in the short term unfortunately.

**Comment by devnix** [comment]
@adrilo Borrowing the implementation from PhpSpreadsheet would slow down Spout? I know there is a list of edge cases, like replicating bugs for some leap years that really aren't and things like that. Would you accept that kind of contribution?

**Comment by adrilo** [comment]
PhpSpreadsheet does things very differently than Spout. It holds the entire spreadsheet in memory: this makes it easy to implement new features (such as this one), but prevents it from working well with larger files (because memory is limited).
Spout processes spreadsheet using streaming techniques, which has the opposite benefits: it can work with large files but implementing new, seemingly simple, features is not straightforward.

Datetime support is one of these features.

If you want to give it a try, absolutely please do it! But I must warn you that it's not an easy task :)
