### ISSUE TITLE
$reader->setShouldFormatDates(true) returns a string in ODS, but also a DateTime in XLSX

### ISSUE THREAD

**Issue by devnix** [box/spout#798]
This would be part of the stacktrace:
```
Error:
Object of class DateTime could not be converted to string

  at vendor/box/spout/src/Spout/Common/Entity/Cell.php:214
  at Box\Spout\Common\Entity\Cell->__toString()
  at trim(object(Cell))
```

As the title says, `setShouldFormatDates` works fine for ODS, but the XLSX reader seems to ignore this setting.

**Comment by devnix** [comment]
I think it's working after switching this two lines:
```php
$reader->open($this->file->getPathname());
$reader->setShouldFormatDates(true);
```

```php
$reader->setShouldFormatDates(true);
$reader->open($this->file->getPathname());
```

But I don't get why this affects in a different way two readers.

**Comment by adrilo** [comment]
`$reader->setShouldFormatDates(true);` must be called before calling `open()`. By doing so, both readers should behave the same: return a string and not a DateTime.
There are tests covering this behavior so I'd double check your code first, making sure that you call things in the right order.
