### ISSUE TITLE
Feature request: support for cell comments (XLSX)

### ISSUE THREAD

**Issue by jverelst** [box/spout#799]
Hi,

I am currently rewriting my application from phpspreadsheet to box/spout, because of the speed and memory usage. So far, excellent results! There is one incompatibility however: the support for cell comments.

Is this something that could be implemented in the XLSX writer and reader? The writer has my main priority, because I want to generate XLSX files with annotations on the cells.

**Comment by adrilo** [comment]
Hi !

Unfortunately, there's no plan to implement cell comments at the moment. Sorry @jverelst
