### ISSUE TITLE
Cast float encapsulate in string to float ?

### ISSUE THREAD

**Issue by partulaj** [box/spout#802]
Hello,

I'm trying to replace phpspreadsheet by spout because we have performance issue but I'm noticing a difference in the way you handle data type. When passing a string that contain a float in phpspreadsheet it's converted to float but in spout it stay a string.

For example with phpspreadsheet with the code bellow I get [phpspreadsheet-example.xlsx](https://github.com/box/spout/files/6197709/phpspreadsheet-example.xlsx)
```php
$data = array(array('test', '2.361', 2.361));

$spreadsheet = new Spreadsheet();
$spreadsheet
    ->getActiveSheet()
    ->fromArray($data)
;
$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
header(sprintf("Content-Disposition:attachement;filename=\"phpspreadsheet-example.xlsx\""));
$writer->save('php://output');
```

And with spout I get [spout-example.xlsx](https://github.com/box/spout/files/6197710/spout-example.xlsx)
```php
$data = array(array('test', '2.361', 2.361));

$writer = WriterFactory::create(Type::XLSX);
$writer->openToBrowser('spout-example.xlsx');
$writer->addRows($data);
$writer->close();
```

I think it's possible to do the conversion like phpspreadsheet but I was wondering if you would be okay to implement this in spout ?

If you're okay with this I can make a PR

**Comment by adrilo** [comment]
Hi @partulaj!
If you pass a string, I believe the right thing to do is to keep it as a string. That's what the intent is and Spout should not make any assumption on what was the actual attempt. It's up to the developer to clarify the intent.

So I won't proceed with your suggestion.
