### ISSUE TITLE
How to get a really row number when setShouldPreserveEmptyRows is set to FALSE?

### ISSUE THREAD

**Issue by baltun** [box/spout#803]

**Comment by adrilo** [comment]
What do you mean "really row number"?

**Comment by baltun** [comment]
When setShouldPreserveEmptyRows is set to FALSE then spout misses empty rows and when you try to get row number from iterator (foreach ($reader-getRowIterator() as $key => $row), a $key will contain not a really number of row from .xlsx file but count of not empty rows from beginning of file to this cycle stage

**Comment by adrilo** [comment]
I see. Your use case is not supported. You'll need to `setShouldPreserveEmptyRows(true)` and skip them in your code if you want to have the real row number.
