### ISSUE TITLE
Requirements and MS Excel Formulas

### ISSUE THREAD

**Issue by eugenio11** [box/spout#805]
Hello,
I have a question about the requirements:

PHP extension ext-zip enabled
PHP extension ext-xmlreader enabled

it seems to me that ext-zip is not required if you just need to READ xls/ods/csv files, while ext-xmlreader is required even if you just need to red. 
Could you please confirm? 

About formulas: in the FAQs you say you don't support formulas, this means you can't edit an existing formula or create a new formula but you can correctly read Excel cells whose values are generated by a formula, correct?

Thanks!

**Comment by adrilo** [comment]
Hi!

Both extensions are required if you need to read and/or write XLSX and ODS files. They are not if you're dealing with CSV files. XLSX and ODS files are basically a bunch of XML files, zipped together. So the zip extension is required to unzip them, and the XML extension is required to read each file.

Regarding formulas, you are correct.

**Comment by eugenio11** [comment]
Hello and thanks for your reply.
What I've noticed, however, is that in a system without ext-zip I can ready xlsx files without any problem but, instead, I get a
Class 'ZipArchive' not found
error if I try to write an xlsx file.  So, for some reason, it seems that reading works even without ext-zip, is this expected? I guess it's not according to your reply.

**Comment by adrilo** [comment]
For reading, we don't use a zip class directly (contrary to writing where we indeed use `ZipArchive`). Instead we can look at the XML files directly into the "zip" (ie XLSX/ODS file), as written here: https://github.com/box/spout/blob/91f756be0b0bf78f79f93a36ffdc240a5bf4099d/src/Spout/Reader/Wrapper/XMLReader.php. I assumed that this behavior required ext-zip extension (and I believe it did few years ago) but maybe in newer PHP versions, it's no longer the case.

**Comment by eugenio11** [comment]
Ok, got it, that's probably the reason then. At least with PHP 7.3, reading seems to work without zip ext.

Thanks.
