### ISSUE TITLE
Adding sheets to existing excel file that uses advanced features

### ISSUE THREAD

**Issue by eugenio11** [box/spout#806]
Hello,
I need to add some sheets to an existing xlsx file. 
The original file has only one sheet and uses some "advanced" features such as:
- Data validation lists with values loaded from another sheet 
- Notes
- background colors 

Can you confirm that is not possible to edit this file using spout? What I understood is that there isn't an actual edit feature, I have to read and copy the data to another file, but I don't think I can read & copy data validation lists or notes for example therefore I can't edit the file.

Thanks.

**Comment by adrilo** [comment]
Unfortunately, none of these use cases are supported by Spout at the moment.
