### ISSUE TITLE
No "date" type when reading XSLX 

### ISSUE THREAD

**Issue by squio** [box/spout#81]
When reading a XSLX file the output types are not always what I would expect.

Observations From limited testing with some xslx files from Excel and exported document from Google Sheets give met the same result:

A cell with a Date or DateTime value appears to be converted to a FLOAT (number of days since 1899-12-30 as per Lotus 123 tradition) rather than a PHP `DateTime` value.

This is unexpected as `Spout/Reader/XLSX/RowIterator.php` explicitly defines cell type `CELL_TYPE_DATE` to convert Date values.

Similarly, a numeric value resulting from an evaluated expression like `=12+13` is converted to a string value `"25"` rather than an `Int` or `Float` value of `25`

Not sure if this is a bug or a limitation related to XSLX variants?

**Comment by adrilo** [comment]
Hi @squio,

Regarding date values, it works as expected with the test files I have: https://github.com/box/spout/blob/03d1917080c7bbc2d109477ff9b793c23a0046ef/tests/Spout/Reader/XLSX/ReaderTest.php#L93
The formatting of the date happens here: https://github.com/box/spout/blob/2a1925bc51155c57d4d0fbb34fa0a23c135878ef/src/Spout/Reader/XLSX/RowIterator.php#L287. It should either return a DateTime object or null if it can't convert the timestamp to a date. I'm surprised a float is also returned.
If you are able to reproduce the issue with a XLSX file, can you please send it to me (adrien_at_box.com)? It will really help me debug!

For the `=12+13` issue, I tried to reproduce it but could not... I got a `int` back.

How did you generate these files? Did you use Excel? Which version?

**Comment by squio** [comment]
Hi @adrilo, 

First: testing with your test sheet `sheet_with_all_cell_types.xlsx` works as expected and indeed gives me correct DateTime values back.

I used two test spreadsheets of myself: one internal company spreadsheet of which I don't know the exact history (I assumed some Excel for Windows version but it might be generated in some way, I'm trying to fin d out).
Also I used an exported sheet from Google Sheets with some formatted and default/auto cell values, downloaded using "File -> download file -> Microsoft Excel".

The strange thing is that when I import your test sheet in Google Sheets both DateTime cells are wrong (E1 empty, E2 a number which looks like the days since epoch value).

Here is my test sheet:
https://docs.google.com/spreadsheets/d/1C1ZnaimFQ6eSmqmYlbFY2CbeFAPbEYHl7-lN5bH9-wg/edit?usp=sharing

Tab 1: 
- test values, dates are in cells B2, B3
- the int-as-a-sum cell is in D4

Tab 2: 
- imported version of `sheet_with_all_cell_types.xlsx`


Opening `sheet_with_all_cell_types.xlsx` in Numbers for Mac OSX (latest version) also shows unexpected values for a lot of cells, including both date cells, see screenshot.


<img width="726" alt="screen shot 2015-08-11 at 09 29 02" src="https://cloud.githubusercontent.com/assets/169410/9193625/2006c140-4015-11e5-9e25-c79d6bc8fb89.png">

**Comment by adrilo** [comment]
I found where the issue comes from. The "date" cell type is not supported by all Excel versions. It seems like Excel 2010 on Mac and the Office Online is two of these.
So instead, Excel uses float values and styles to determine the cell format. From styles.xml:

```
<cellXfs count="5">
	<xf borderId="0" fillId="0" fontId="0" numFmtId="0" xfId="0"/>
	<xf applyNumberFormat="1" borderId="0" fillId="0" fontId="0" numFmtId="14" xfId="0"/>
	<xf applyNumberFormat="1" borderId="0" fillId="0" fontId="0" numFmtId="165" xfId="0"/>
	<xf applyNumberFormat="1" borderId="0" fillId="0" fontId="0" numFmtId="17" xfId="0"/>
	<xf applyNumberFormat="1" borderId="0" fillId="0" fontId="0" numFmtId="166" xfId="0"/>
</cellXfs>
```

This results in:
```
8/11/15	11-Aug-2015	Aug-15	08/11/15
```

So, the solution would be to read the styles whenever a numeric value with a style is encountered:
```
<c r="A1" s="1">
	<v>42227</v>
</c>
```

The style ID needs to be greater than 0 (as 0 is the default style, and does not have any formatting).

Now, regarding formatting, Excel has a number of pre-defined formats. That's what the numFmtId attribute refers to. So we'll need to get the list somewhere to check which ones are date formats in order to convert them to an actual DateTime object.
Finally, the value itself is not an ISO date but a OLE Automation date... From the Microsoft website:

> An OLE Automation date is implemented as a floating-point number whose integral component is the number of days before or after midnight, 30 December 1899, and whose fractional component represents the time on that day divided by 24. For example, midnight, 31 December 1899 is represented by 1.0; 6 A.M., 1 January 1900 is represented by 2.25; midnight, 29 December 1899 is represented by -1.0; and 6 A.M., 29 December 1899 is represented by -1.25.

**Comment by rbro** [comment]
I am seeing a similar issue.  If I create a new spreadsheet in Excel 2010 on Windows with 1/2/2003 in cell A1, when I read it through spout, it's coming through as 37623.  I can convert it back to 2003-01-02 using the formulas listed in http://stackoverflow.com/questions/1703505/excel-date-to-unix-timestamp, but is there a way that spout can export it directly as 2003-01-02.  Please let me know if posting an sample xlsx file will help.  Thanks.

**Comment by adrilo** [comment]
@rbro, thanks for your help. I am able to reproduce the issue so no need for a sample xlsx.
The way dates are parsed is currently incorrect as it assumes dates are ISO dates and not OLE Automation Date. I'll work on this when I have some time.
