### ISSUE TITLE
How to have more than one iterator.

### ISSUE THREAD

**Issue by lestcape** [box/spout#817]
As i can see `getSheetIterator `or `getRowIterator` return always the same iterator instance and I think that this is a problem. Considered the following situation where we have our own wrapper for spout:

```php
class WrapperSpoutReader {
    public function __construct($filePath) {
        $this->reader = ReaderEntityFactory::createXLSXReader();
        $this->reader->open($filePath); 
    }

    public function getFirstRowWithData() {
        foreach ($this->reader->getSheetIterator() as $sheet) {
            foreach ($this->sheet->getRowIterator() as $row) {
                if (!$row->isEmpty()) {
                    return $row;
                }
            }
        }
        return null;
    }

    public function getSheet($index) {
        foreach ($this->reader->getSheetIterator() as $sheet) {
            if ($sheet->getIndex() === $index) {
                return $this->sheet;
            }
        }
    }
}
```

This is a code of a user of our wrapper who don' t know anything about the internal class implementation. Then he/she wrote this code:

```php
....
$reader = new WrapperSpoutReader($filePath);
$sheet = $reader->getSheet(0);

foreach ($this->sheet->getRowIterator() as $row) {
    if (!$row->isEmpty()) {
        $rowFirst =  $reader->getFirstRowWithData();
        if ($rowFirst == $row) {
           ....
        }
    }
}
```

Please note that call a function that use the iterator inside a procedure that is using the same iterator is what cause the issue. I think that to solve that type of issues, the iterator that is returned need to be a new instance always and not the same instance.

**Comment by adrilo** [comment]
Indeed, you can't have multiple iterators operation at the same time. Having multiple iterators is not needed the vast majority of the time and increases the possibility of errors (each iterator stores data in memory for instance). So I won't support this use case directly in Spout.

Also here the logic being used is off IMO. A row belongs to a sheet. What your user is trying to do is get the first row of the sheet 0. Your `getFirstRowWithData` should have a reference to the sheet; something like this:

```
public function getFirstRowWithData($sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        if (!$row->isEmpty()) {
           return $row;
        }
    }
    return null;
}
```

In which case, the usage of your wrapper now looks like this:
```
....
$reader = new WrapperSpoutReader($filePath);
$sheet = $reader->getSheet(0);
$rowFirst =  $reader->getFirstRowWithData($sheet);
if ($rowFirst == $row) {
  ....
}
```

And you no longer have a problem with multiple iterators :)

**Comment by lestcape** [comment]
When you design a library, one important point is isolate the client of your library about the internal implementation. Something impossible in the case of spout, because the already exposed situation.

For a point of view of a user of the library, have multiple iterator reduce the possibility of errors, because reduced the possibility of conflicts when you reused the same iterator. For the point of view of the creator of the library, yes, is more easy handled just one instance, but a library is designed to be used by users, not by the creator, so...

I only shared an example with a different implementation to be easy understand the problematic, but the problematic is already present in spout, you don't need to create a wrapper to have the possibility of be in conflict with the iterators.

Also the solution you proposed don't resolve the exposed problematic. Please, see that the same code of the user adapted to your changes in `getFirstRowWithData` will have again he same problem:

```php
$reader = new WrapperSpoutReader($filePath);
$sheet = $reader->getSheet(0);

foreach ($sheet->getRowIterator() as $row) {
    if (!$row->isEmpty()) {
        $rowFirst =  $reader->getFirstRowWithData($sheet);
        if ($rowFirst == $row) {
           ....
        }
    }
}
```

Please note that the row iterator is restarted internally in `getFirstRowWithData`, so that is why the execution will fail.

Additional to that information, please note that we don' t create wrappers for fun, we create it when we need to satisfy an interface of a functionality. For example, when we are creating a commons file generator (spss, stata, dbf. xlsx, csv....) and in that case the interface is unique, so is not negotiable and you can not change it. So, we can not use spout as a back-end of our interface, as a cause of the already exposed problematic.

In fact this is not an hypothetical case, I'm port the stata implementation of python pandas to php, i already created a dbf writer implementation in php and i'm working to improved  an spss implementation in php that is here in github. My objective was to use spout as a backbend to xslx, but i can not, because a to the problem that creates the conflict between the iterators.
