### ISSUE TITLE
"This action won't work on multiple selections" error in Excel

### ISSUE THREAD

**Issue by gellerta** [box/spout#818]
Hi,

I'm experiencing the following weird issue:
1. Export xlsx file from php
2. Open the file in Excel 2019
3. Click the "New sheet" (+) icon
4. I'm getting the "_This action won't work on multiple selections_" error.
In case I save the file (without any modification) close Excel and reopen the file the error is not present anymore.

I even exported a completely empty xlsx file ([Sample empty export file.xlsx](https://github.com/box/spout/files/6555403/Sample.empty.export.file.xlsx)) and tried with that but it was the same with that.

If I open the file in Excel 2003 or in LibreOffice it the issue is not present.
It seems that Excel 2019 treats the exported file as somehow corrupted / or misses some essential macro info (which is added after saving the file).

Do you have any idea/suggestion what should I do differently during the export process to resolve this issue?

Thank you,
Andrew

**Comment by adrilo** [comment]
Hi,
It seems like the file you sent is not what's coming from Spout directly. You probably opened it in Excel and saved it (so Excel added a bunch of things). Anyway, can you download this file and tell me if you can reproduce the bug with it? If not, it will really help me narrow down what the issue can be.

**Comment by gellerta** [comment]
Hi adrilo,

The file which I attached is the one wich came directly from the export (with using Spout). It has not been saved in Excel.

I do the export using the following method:
```
$writer = LKWriterEntityFactory::createXLSXWriter();
$writer->openToFile($file);
$writer->addRow(WriterEntityFactory::createRowFromArray(['column1']));
$writer->close();
```

Here is another exported file which has the same deficiency as all others :(
[sample_export_file_with_Spout.xlsx](https://github.com/box/spout/files/6562758/sample_export_file_with_Spout.xlsx)

**Comment by adrilo** [comment]
You're not using Spout directly, but instead a wrapper. This wrapper adds stuff to the created files, which causes the issue.

For example, this is what the sheet data for your last sent file looks like:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
	<sheetViews>
		<sheetView showGridLines="true" showRowColHeaders="1" tabSelected="1" workbookViewId="0">
			<pane activePane="bottomLeft" state="frozen" topLeftCell="A2" ySplit="1"/>
			<selection activeCell="A1" pane="bottomLeft" sqref="A1"/>
		</sheetView>
	</sheetViews>
	<sheetFormatPr defaultColWidth="30" defaultRowHeight="14.4" outlineLevelCol="0" outlineLevelRow="0"/>
	<sheetData>
		<row r="1" spans="1:1">
			<c r="A1" s="0" t="inlineStr">
				<is>
					<t>column1</t>
				</is>
			</c>
		</row>
	</sheetData>
</worksheet>
```

And this is what a file created by Spout would look like:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
	<sheetData>
		<row r="1">
			<c r="A1" s="0" t="inlineStr">
				<is>
					<t>column1</t>
				</is>
			</c>
		</row>
	</sheetData>
</worksheet>
```

So you can try modifying the wrapper lib you're using (remove `sheetViews` or `sheetFormatPr`) or switch to Spout directly. Good luck!
