### ISSUE TITLE
Specifix XLSX file not opening

### ISSUE THREAD

**Issue by madhurbhaiya** [box/spout#823]
Firstly, thanks a lot for this amazing Library. It has helped me upload 100 k records in very less time and little memory usage.

This issue is about a very specific xlsx file, which I received from client. That xlsx files opens perfectly fine in MS Office, Libreoffice etc. But on trying to read the same using Spout, I am getting following exception message

```
Could not open <filename> for reading
```

Am attaching the excel file here. The code used for reading is pretty standard and shared below:

```
$reader = ReaderFactory::create(Type::XLSX);
// Skip Empty Rows. Ref: http://opensource.box.com/spout/docs/#empty-rows
$reader->setShouldPreserveEmptyRows(false);
$reader->open($file_path);  // $file_path is the path to the file being read
```

File is attached [test.xlsx](https://github.com/box/spout/files/6829494/test.xlsx)

Thanks.

**Comment by adrilo** [comment]
Hi,

Indeed the way the file was created differs from what I usually see.
```
 unzip test.xlsx
Archive:  test.xlsx
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of test.xlsx or
        test.xlsx.zip, and cannot find test.xlsx.ZIP, period.
```

Unzipping the XLSX file usually works as expected. Not sure what's wrong here...

**Comment by madhurbhaiya** [comment]
@adrilo Yeah it is definitely generated a bit weirdly.

Interesting thing is that once I open this file and Save again (without chaning anything) using Excel 2010+, LibreOffice; then the file becomes "correct" and Spout is able to read the same.

If it helps, I believe that the original "error" file is generated using MS Excel 2007

**Comment by adrilo** [comment]
Maybe there's a compatibility mode or something like this. Anyway, this is the first time in many years that I hear about this issue. So I won't investigate more on my side...
