### ISSUE TITLE
XLSX Reader error

### ISSUE THREAD

**Issue by 957945355** [box/spout#824]
My error info:
Could not open D:\www\public/import\custom_yinqing/OS202107271615345123_origin.xlsx for reading! (XMLReader::open(): Unable to open source data)

I tracking code, error is sent here（vendor\box\spout\src\Spout\Reader\Wrapper\XMLReader.php）：
![image](https://user-images.githubusercontent.com/8485502/127120121-a3524639-84dc-4cb5-8d24-6927f9db1f85.png)

I found a solution by looking for other issues. After using libxml_disable_entity_loader(false) function, the loading of xlsx is very slow. Is there any other better solution?

My application environment:
windows 10
php v7.3.4
libxml v2.9.9
box/spout v3.3.0

**Comment by adrilo** [comment]
I don't know any other solution. But unless your XLSX file is "malformed", using `libxml_disable_entity_loader` should not affect performance. So the slowness here may be normal if it's a large spreadsheet.

**Comment by 957945355** [comment]
> I don't know any other solution. But unless your XLSX file is "malformed", using `libxml_disable_entity_loader` should not affect performance. So the slowness here may be normal if it's a large spreadsheet.

Thank you for your reply!
I compared it with `phpoffice`  and got the result of slow running.
If `libxml_disable_entity_loader`does not affect the performance, it should be the problem of the `box/spuut` itself, or the problem occurs in the secondary package `rap2hpoutre/fast-excel`. I need more tests.
