### ISSUE TITLE
Could not open file name for reading! Stream wrapper used is not supported for this type of file

### ISSUE THREAD

**Issue by azizimo** [box/spout#826]
Hello Everyone i hope someone will get back to me, I'm trying to read  from google cloud. i get this

$reader->open(getenv('GOOGLE_CLOUD_STORAGE_BUCKET') . "://" . $path );

`^ Box\Spout\Common\Exception\IOException {#1661 ▼
  #message: "Could not open ramsstatic://imports/import.csv for reading! Stream wrapper used is not supported for this type of file."
  #code: 0
  #file: "/home/vagrant/code/rams/vendor/box/spout/src/Spout/Reader/ReaderAbstract.php"
  #line: 112
  trace: {▼
    /home/vagrant/code/rams/vendor/box/spout/src/Spout/Reader/ReaderAbstract.php:112 {▶}
    /home/vagrant/code/rams/app/Http/Controllers/AssetController.php:2393 {▼
      App\Http\Controllers\AssetController->import($fieldName, $tab = null) …
      › $reader = ReaderEntityFactory::createReaderFromFile(getenv('GOOGLE_CLOUD_STORAGE_BUCKET') . "://" . $path);
      › $reader->open(getenv('GOOGLE_CLOUD_STORAGE_BUCKET') . "://" . $path );
      › 
      arguments: {▶}
    }
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130 {▶}
    /home/vagrant/code/rams/app/Http/Middleware/PermissionsActions.php:45 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/app/Http/Middleware/CheckToken.php:48 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/app/Http/Middleware/LogRoute.php:19 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php:39 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/Router.php:683 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/Router.php:624 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Routing/Router.php:613 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:170 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130 {▶}
    /home/vagrant/code/rams/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:67 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:63 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/fideloper/proxy/src/TrustProxies.php:57 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:145 {▶}
    /home/vagrant/code/rams/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110 {▶}
    /home/vagrant/code/rams/public/index.php:55 {▶}
  }
}`

**Comment by adrilo** [comment]
Hi @azizimo,

As indicated by the error message "Could not open ramsstatic://imports/import.csv for reading! Stream wrapper used is not supported for this type of file", reading a file directly from GCS is not supported.
What you can do instead (less efficient but working) is to first download the file locally and then read from the local file.

Hope this helps!
