### ISSUE TITLE
Override StyleManager::shouldFormatNumericValueAsDate()

### ISSUE THREAD

**Issue by Horzta** [box/spout#828]
Hi I just started implementing this project too one of our scripts because we moved away from PHPExcel due to memory concerns.

I was just wondering if we could have an override option to 
` $shouldFormatAsDate = $this->styleManager->shouldFormatNumericValueAsDate($cellStyleId);` 
on [CellValueFormatter](https://github.com/box/spout/blob/master/src/Spout/Reader/XLSX/Helper/CellValueFormatter.php#L181)?

We want to use our own way in formatting the date, so meaning we actually want the original int value.

**Comment by adrilo** [comment]
Hi!
Sorry this is not possible. However, you could reverse the logic when Spout returns a DateTime to get the int value back. Not as convenient but it should work.
