### ISSUE TITLE
addRows Array

### ISSUE THREAD

**Issue by drmax24** [box/spout#845]
Well we used BoxSpout 2 for some years and considered it to be the best xlsx library ie good perfomance/features. Now in a box spout 3 i see a problem.

In box spout 2 i could have a code:
```
    public function make()
    {
        $headerRow = isset($this->output[0]) ? array_keys($this->output[0]) : [];
        $writer = \Box\Spout\Writer\WriterFactory::create(\Box\Spout\Common\Type::XLSX);

        header('Access-Control-Allow-Origin: *');
        $writer->openToBrowser('organizations' . '.' . 'xlsx');
        $writer->addRow($headerRow);
        $writer->addRows($this->output);
        $writer->close();
    }
```

Above function can output any array as xlsx file. Now i'd have to loop $this->output and make rows out of it first.

In a box spout 3 we can't work with array of strings anymore. Box spout 3 is very much focused on styling but it lacks robust array to xlsx conversion (reason why we used box spout in the first place). Box spout 3 forces us to write extra code making each row an object and making each row inconvenient in the same time. I liked an idea of converting array into xlsx. Plz let us simply convert array to xlsx again!

**Comment by adrilo** [comment]
Hi!

You can have another look at the documentation, it was updated: https://opensource.box.com/spout/getting-started/
You'll find that you can now do that:
```
$values = ['Carl', 'is', 'great!'];
$rowFromValues = WriterEntityFactory::createRowFromArray($values);
$writer->addRow($rowFromValues);
```

**Comment by drmax24** [comment]
This is array to xlsx converter via boxSpout 3
```
    private function generateViaSpout()
    {
        $writer = WriterFactory::createFromType(Type::XLSX);
        $headerRow = $this->getHeader();
        header('Access-Control-Allow-Origin: *');
        $writer->openToBrowser($this->fileName);
        $writer->addRow(WriterEntityFactory::createRowFromArray($headerRow));
        foreach ($this->output as $output) {
            $writer->addRow(WriterEntityFactory::createRowFromArray($output));
        }
        $writer->close();
    }

```

**Comment by drmax24** [comment]
This is similar array to xlsx conversion code via XlsWriter 
https://github.com/mk-j/PHP_XLSXWriter
```php
    private function generateViaXlsxWriter()
    {
        $writer = new \XLSXWriter();
        $writer->writeSheetHeader('list1', $this->getHeader());
        $writer->writeSheet($this->output);
        $writer->writeToFile($this->fileName);
    }
```

If robust array to xls conversion (similar to spout 2) is not added we would have to ditch Spout 3
