### ISSUE TITLE
Deprecated warnings for incompatible return types in PHP 8.1

### ISSUE THREAD

**Issue by fabacino** [box/spout#846]
Since PHP 8.1 most methods of internal classes require a compatible return type when overriding them (see [Return Type Compatibility with Internal Classes](https://www.php.net/manual/en/migration81.incompatible.php)).

This results in deprecated warnings for the following classes:

* `Box\Spout\Reader\CSV\RowIterator`
* `Box\Spout\Reader\CSV\SheetIterator`
* `Box\Spout\Reader\ODS\RowIterator`
* `Box\Spout\Reader\ODS\SheetIterator`
* `Box\Spout\Reader\Wrapper\XMLReader`
* `Box\Spout\Reader\XLSX\RowIterator`
* `Box\Spout\Reader\XLSX\SheetIterator`

Sample output for `Box\Spout\Reader\CSV\RowIterator`:

```sh
❯ vendor/bin/phpunit | grep -i "deprecated: return type" | grep -i 'csv\\rowiterator'

Deprecated: Return type of Box\Spout\Reader\CSV\RowIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in src/Spout/Reader/CSV/RowIterator.php on line 227
Deprecated: Return type of Box\Spout\Reader\CSV\RowIterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in src/Spout/Reader/CSV/RowIterator.php on line 129
Deprecated: Return type of Box\Spout\Reader\CSV\RowIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in src/Spout/Reader/CSV/RowIterator.php on line 238
Deprecated: Return type of Box\Spout\Reader\CSV\RowIterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in src/Spout/Reader/CSV/RowIterator.php on line 117
Deprecated: Return type of Box\Spout\Reader\CSV\RowIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in src/Spout/Reader/CSV/RowIterator.php on line 87
```

Adding the `#[\ReturnTypeWillChange]` attribute to these methods fixes the issue. I can PR if appreciated.

**Comment by ankurk91** [comment]
Please send a PR, this is the only way to fix the issue

**Comment by adrilo** [comment]
Hi! Feel free to send a PR :)

Just one thing: if you take a look at the `CSVIterator::rewind` method for instance:
```
    /**
     * Rewind the Iterator to the first element
     * @see http://php.net/manual/en/iterator.rewind.php
     *
     * @return void
     */
    public function rewind()
    {
        ...
    }
```

As you can see, the PHPDoc is correct. To solve the issue you mentioned, the correct fix would be to add a proper return type (instead of adding the `#[\ReturnTypeWillChange]` attribute).

**Comment by fabacino** [comment]
> As you can see, the PHPDoc is correct. To solve the issue you mentioned, the correct fix would be to add a proper return type (instead of adding the #[\ReturnTypeWillChange] attribute).

Adding the return type breaks backward compatibility and assuming that this fix would get released as a patch version, I would be reluctant to do that. But if you like it to be fixed this way, I can certainly do that.

**Comment by adrilo** [comment]
Well most of the methods are (or should be considered) internal only. So adding a return type should not break anybody.
Also, the `@return` in the PHPDocs should be correct. So the only case where it's going to break something is if someone used an internal method that did not have the correct type.
Is that correct?

**Comment by fabacino** [comment]
> Well most of the methods are (or should be considered) internal only. So adding a return type should not break anybody.
Also, the @return in the PHPDocs should be correct. So the only case where it's going to break something is if someone used an internal method that did not have the correct type.
Is that correct?

Well, you could get a break even with a correct return type because adding explicit return types forces all extending classes to have explicit return types as well, otherwise PHP will raise a fatal error (function interface mismatch).
So if the `RowIterator::rewind()` function interface were changed to
```php
class RowIterator implements IteratorInterface
{
    /**
     * Rewind the Iterator to the first element
     * @see http://php.net/manual/en/iterator.rewind.php
     */
    public function rewind(): void
    {
        ...
    }
}
```
then an overridden function with the current interface in an extending class
```php
class MyIterator extends RowIterator
{
    /**
     * Rewind the Iterator to the first element
     * @see http://php.net/manual/en/iterator.rewind.php
     *
     * @return void
     */
    public function rewind()
    {
        ...
    }
}
```
would cause a break.

**Comment by fabacino** [comment]
Please let me know whether you prefer the addition of explicit return types (despite possible breaks) or want it to be solved with attributes.

**Comment by adrilo** [comment]
@fabacino As part of another PR, I fixed these issues (using explicit types)
