### ISSUE TITLE
Unable to open xlsx in browser under iOS

### ISSUE THREAD

**Issue by sixtyseven-multimedia** [box/spout#85]
First  of all: I love the simplicity of your class, it works like a charm on my windows system. Unfortunately I get an error when I open the page that generates the file under iOS, I get the following error message:

OfficeImportErrorDomain-Fehler 912

**Comment by adrilo** [comment]
Hi @sixtyseven-multimedia,

Thanks for filing this issue!
It looks like there is something wrong with the `openToBrowser()` function. It is not restricted to iOS (although the error message IS specific to iOS).
After using the `openToBrowser()` function, opening the created file in Excel Mac or Windows result in a "File corrupted" error message... What's strange is that if I unzip the XLSX file and re-zip it, it now works.

This needs deeper investigation.

**Comment by sixtyseven-multimedia** [comment]
Unfortunately the fix does not completely solve the problem. Although I am able to open the file under iOS now, most of the cells are empty. As far as I can see, only the numbers are displayed properly.

**Comment by adrilo** [comment]
The empty cells are a iOS bug (it's also present with Numbers). The iOS
previewer does not support inline strings, which is Spout's default way of
storing string. So in order to have your strings displayed you need to tell
Spout to use shared strings instead.
This can be done by calling setShouldUseInlineStrings(false) on the writer
object.

There is a small performance tradeoff when using shared strings but unless
your sheet contains millions of rows, you should not notice :)

Let me know if this fixes your issue

**Comment by sixtyseven-multimedia** [comment]
Tried to add your suggestion, but no luck :-(

Could you take a look at the following code and tell me if I am doing it wrung? I skipped the data building part. Since the sheets are ok on my dektop, I assume that the arrays are ok.

'use Box\Spout\Common\Type;
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Writer\Style\StyleBuilder;

$header_style = (new StyleBuilder())
           ->setFontBold()
           ->build();

$writer = WriterFactory::create(Type::XLSX);

$writer->openToBrowser($filename); // stream data directly to the browser
$writer->setShouldUseInlineStrings(false); // iOS fix

$mitglieder_sheet = $writer->getCurrentSheet();
$mitglieder_sheetName = $mitglieder_sheet->setName('Mitglieder');

$writer->addRowWithStyle($header, $header_style); // style will only be applied to this row
$writer->addRows($mitglieder); // add multiple rows at a time

if(count($verstorbene) > 0) {
	// New sheet
	$verstorbene_sheet = $writer->addNewSheetAndMakeItCurrent();
	$verstorbene_sheetName = $verstorbene_sheet->setName('Verstorbene');
	
	$writer->addRowWithStyle($header2, $header_style); // style will only be applied to this row
	$writer->addRows($verstorbene); // add multiple rows at a time
}

$writer->close();'

Thank you for your patience with my problem.

**Comment by sixtyseven-multimedia** [comment]
Please ignore the above, I obviously have to call the string settings BEFORE open to browswer.

Works like a charm, I will try it on a mac as well tomorrow, problem solved!

**Comment by adrilo** [comment]
I'm glad it works now :) I filed #95 to avoid your last mistake happens again.
