### ISSUE TITLE
It takes around 5 secs to read 1000 rows (25 cols)

### ISSUE THREAD

**Issue by acirulis** [box/spout#858]
I have a large Excel file (>100k rows) and basic reader example without any processing takes around 5 secs for 1000 rows with 25 columns. (env: php 8.1, Symfony 6, Win11 with WSL2+docker and Ryzen 4700U CPU). 
I thought it was a bit much and come across abandoned package https://github.com/akeneo-labs/spreadsheet-parser which after testing can read same 1000 rows in about 200ms (.2 secs) without any other changes to code or environment.

Is there anything I can try with box/spout to improve performance? I am reluctant to use that abandoned package.
Thank you!

**Comment by adrilo** [comment]
Hi!
I'm not sure what's different but performance may vary from file to file. For instance, if the file uses inline strings or shared strings has a huge impact. The number of cell styles (which may be ignored by the said lib, but processed by Spout) may also have an impact.
So I don't have anything specific in mind, except removing existing features. While this can work for your use case, some people rely on these features...
