### ISSUE TITLE
How to set  cell background and font color

### ISSUE THREAD

**Issue by renciebautista** [box/spout#86]
How to set  cell background and font color

**Comment by adrilo** [comment]
Hi @renciebautista,

Unfortunately, for now Spout does not support these style properties. You can find the list of supported styles here: https://github.com/box/spout#row-styling

I'll keep this issue open as adding font color and cell background is something I can add to the roadmap.

**Comment by adrilo** [comment]
Font color support: #93

**Comment by adrilo** [comment]
Adding background color is way more complex than font color. Therefore it won't be supported for now.

**Comment by denaje** [comment]
+1 for background color support.

**Comment by zendre4** [comment]
+1 for background color support.

**Comment by adrilo** [comment]
@denaje @zendre4, it's actually supported now!
```
$style->setBackgroundColor(Color::YELLOW);
```

**Comment by insane404** [comment]
@adrilo is **cell** formatting like background color, font color & font style for an individual cell, added into this library yet ?

**Comment by adrilo** [comment]
@insane404 It's not yet. All the styling is done at the row level for now

**Comment by slyher** [comment]
@adrilo  any update on cell formating? 3.x?

**Comment by adrilo** [comment]
This is ready now: https://opensource.box.com/spout/docs/#styling-cells
