### ISSUE TITLE
This page isn’t working when calling $reader = ReaderEntityFactory::

### ISSUE THREAD

**Issue by KK4HFJ** [box/spout#861]
I don't use composer. my code is as follows:

$filePath = 'csv/20220127160717 prop.xlsx';

include 'Reader\Common\Creator\ReaderEntityFactory.php';

$reader = ReaderEntityFactory::createReaderFromFile($filePath);  // this is the line that breaks my browser

$reader->open($filePath);

I get a broken page message from chrome. Autoloader, Common, Reader and Writer are in same directory as my php file.

**Comment by adrilo** [comment]
You should take a look at this: https://opensource.box.com/spout/getting-started/#manual-installation
You need to include the autoload file.
