### ISSUE TITLE
Content-Disposition header for file download is not properly encoded

### ISSUE THREAD

**Issue by larsbonczek** [box/spout#878]
In [src/Spout/Writer/WriterAbstract.php:141](https://github.com/box/spout/blob/cc42c1d29fc5d29f07caeace99bd29dbb6d7c2f8/src/Spout/Writer/WriterAbstract.php#L141) the value for `filename` and `filename*` is not properly encoded. `rawurlencode` should probably be used instead of `rawurldecode`.

This leads to an error in the Moodle Learning Platform when a file name contains special characters like a comma: [MDL-73624](https://tracker.moodle.org/browse/MDL-73624).

If I'm reading [RFC5987](https://datatracker.ietf.org/doc/html/rfc5987#section-3.2.1) correctly, only the extended syntax for `filename*` may use URL-encoding. The regular syntax for `filename` (defined as `quoted-string` in [RFC2616](https://datatracker.ietf.org/doc/html/rfc2616#section-2.2) seems to describe backslash-encoding. But reality doesn't seem to agree.

According to [this comment](https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http/6745788#comment65669446_6745788) on StackOverflow, URL-encoding both values should work with most browsers.

**Comment by Slamdunk** [comment]
Fix merged in https://github.com/openspout/openspout/pull/46 and released in [`openspout:v3.7.2`](https://github.com/openspout/openspout/releases/tag/v3.7.2)
