### ISSUE TITLE
PHP 8.1 Warnings

### ISSUE THREAD

**Issue by masroore** [box/spout#882]
The following warnings appear on `PHP >= 8.1`:

Return type of Box\Spout\Reader\CSV\RowIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in \vendor\box\spout\src\Spout\Reader\CSV\RowIterator.php on line 227

Return type of Box\Spout\Reader\CSV\RowIterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in \vendor\box\spout\src\Spout\Reader\CSV\RowIterator.php on line 129

Return type of Box\Spout\Reader\CSV\RowIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in \vendor\box\spout\src\Spout\Reader\CSV\RowIterator.php on line 238

Return type of Box\Spout\Reader\CSV\RowIterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in \vendor\box\spout\src\Spout\Reader\CSV\RowIterator.php on line 117

Return type of Box\Spout\Reader\CSV\RowIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in \vendor\box\spout\src\Spout\Reader\CSV\RowIterator.php on line 87

Other document types (XLS, ODT) also have similar warnings

**Comment by Slamdunk** [comment]
Fixed and released in [`openspout/openspout:v3.7.1`](https://github.com/openspout/openspout/releases/tag/v3.7.1)

**Comment by masroore** [comment]
> Fixed and released in [`openspout/openspout:v3.7.1`](https://github.com/openspout/openspout/releases/tag/v3.7.1)

Thanks. I'd switched to openspout after filing the issue.
