### ISSUE TITLE
rowIterator->next() crash

### ISSUE THREAD

**Issue by Sukushi** [box/spout#884]
Hi. I encounter a problem when I use the next() function my php crash.
The foreach loop work but not the $rows->next().

```
require_once("spout-3.3.0/src/Spout/Autoloader/autoload.php");
use Box\Spout\Reader\Common\Creator\ReaderEntityFactory;

$reader = ReaderEntityFactory::createXLSXReader();
$reader->open($target_file);

foreach ($reader->getSheetIterator() as $sheet) {
	$rows = $sheet->getRowIterator();
	$rows->next();
        ...
        foreach ($rows as $row) {
            $cells = $row->getCells();
            ...
        }
}

$reader->close();
```

**Comment by adrilo** [comment]
Hi,
As described [in the doc](https://opensource.box.com/spout/getting-started/#reader), you should not need to call `next()`:
```
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        // do stuff with the row
        $cells = $row->getCells();
        ...
    }
}
```

**Comment by Sukushi** [comment]
the fact is that I want to do a different thing only for the first line (get the index name and position of the column) and then treat the row with the foreach.
there is no way to use next() directly ? 

I bypass the problem like this but this isn't a satisfying solution.
```
$boolIndex = true;

foreach ($rows as $row) {
    if ($boolIndex) {
        // do thing for the first line
        $boolIndex = false;
    } 
    else {
        // do thing for the row
    }
}
```

**Comment by adrilo** [comment]
(we can continue the discussion here)

```
foreach ($sheet->getRowIterator() as $rowIndex => $row) {
    if ($rowIndex === 0) {
      // do something with the first row
    } else {
    }
}
```
This is how it should be done

**Comment by Sukushi** [comment]
(I was not sure if you will see it)
Yes thanks that a better solution.
I see somewhere that next() was available but you remove it, why ? in that sort of case it's still more clean (I think) to do it with the next().

**Comment by adrilo** [comment]
`next()` is technically still present (see https://github.com/box/spout/blob/master/src/Spout/Reader/XLSX/RowIterator.php#L179-L186). However I don't guarantee that the implementation is 100% compliant with what's expected. I had to do a few hacks to get the streaming part working. I can guarantee that the foreach approach works, but can't for the hasNext/next/current approach
