### ISSUE TITLE
Decimal not converted to numbers

### ISSUE THREAD

**Issue by renciebautista** [box/spout#98]
Decimal value from database is treated as string not number
![untitled](https://cloud.githubusercontent.com/assets/1759005/9514392/4d023062-4ccc-11e5-86ce-c67e191ecbb4.png)

**Comment by adrilo** [comment]
@renciebautista, can you please give me more details on what the error is exactly? Are you writing a CSV or XLSX file?

**Comment by anmoroz** [comment]
Hello.
I insert the following data:
![](http://pavlovsk36.ru/screenshot/Mozilla_Firefox_1BB2B1D1.png)

I receive a file XLSX:
![](http://pavlovsk36.ru/screenshot/Формат_ячеек_и_illiquid_export_23_09_2015_xlsx_1BB2B0E7.png)

The format of the cell must be numeric, but it turns out a text.

**Comment by adrilo** [comment]
Tested and verified. If anyone wants to give a try fixing that one, please do so :) I'll be happy to help!

**Comment by adrilo** [comment]
@renciebautista, @anmoroz, can you please give me more info on how this is problematic for you?

By default, values are treated as numbers so "Standard" actually means "number" (int or float). Also, if you read the generated file, it will give you a float back, not a string.

**Comment by anmoroz** [comment]
I need to add pivot table, which is located in a separate file. But pivot table is destroyed
For standard cell type, I can not use the formula without conversion.

I have studied the documentation of Microsoft - seem your code is correct. But the data in the cell is not a number.
I do not know what the problem.

**Comment by adrilo** [comment]
You should be able to use standard cells as numeric values without any conversion. This is what happens when you manually create an Excel spreadsheet and don't specify the cell format. You can also use pivot table without specifying the cell format.

I think that your problem is not linked to this. By the way, I'm not sure how you create you pivot table but this is not supported by Spout. Closing this issue as it's not a actual issue.

**Comment by jaspal747** [comment]
Facing this same issue. Spout will prefix ' to the number in xlsx (when I open the file in LibreOffice, it shows this character. In excel, it adds the green flag to the top left corner of the cell. When we remove the ' and save the file, Excel correctly formats the cell as a number). Nothing related to pivoting. This is just a general issue.
![Screenshot 2020-03-04 at 8 34 35 PM](https://user-images.githubusercontent.com/1780300/75939331-dfe95d00-5e57-11ea-8965-d2f0e0ea0642.png)

**Comment by jaspal747** [comment]
We found a solution for this. In the WriterEntityFactory.php, in the createRowFromArray() fn, we added a check for is_numeric and casted numbers to doubles.
`public static function createRowFromArray(array $cellValues = [], Style $rowStyle = null) {
		$cells = array_map(function ($cellValue) {
			/**
			 * Case the $cellValue to the correct type based on the value
			 */
            if (is_numeric($cellValue)) {
                $cellValue = (double)$cellValue;
            }
			/**
			 * 
			 */
			return new Cell($cellValue);
			/**
			 * 
			 */
		}, $cellValues);

		return new Row($cells, $rowStyle);
	}`

**Comment by jaspal747** [comment]
We found a solution for this. In the WriterEntityFactory.php, in the createRowFromArray() fn, we added a check for is_numeric and casted numbers to doubles.
So the updated function looks like this now:

```
public static function createRowFromArray(array $cellValues = [], Style $rowStyle = null) {

    $cells = array_map(function ($cellValue) {
        /**
         * Cast the $cellValue to the correct type based on the value
         */
        if (is_numeric($cellValue)) {
              $cellValue = (double)$cellValue;
        }

        return new Cell($cellValue);
        
    }, $cellValues);

    return new Row($cells, $rowStyle);
}
```

**Comment by jaspal747** [comment]
The deeper issue is here:
```
    public static function isNumeric($value)
    {
        $valueType = gettype($value);

        return ($valueType === 'integer' || $valueType === 'double');
    }
```
The CellTypeHelper strictly checks that numbers are only ints and doubles.
This should be updated to the simple:
```
    public static function isNumeric($value)
    {
        return is_numeric($value);
    }
```

**Comment by adrilo** [comment]
I *think* the initial code was what you proposed but it was changed to checking type directly. While using `is_numeric` works for your use case, it breaks other cases (I think some people expect `"123"` to not be numeric but a string.

**Comment by jaspal747** [comment]
isNumeric() should mean is_numeric.. I don't see why outputting "123" (string) as 123 (number) in xslx would cause some people's excels to break.
